Repository matter-js/matter.js, pull requests merged in 2023-12, with the labels that each got.

#552 Handle Message extensions and Secured extensions correctly
  packages/matter-node.js/test/session/SecureSessionTest.ts
  packages/matter.js/src/codec/MessageCodec.ts
  packages/matter.js/src/protocol/ExchangeManager.ts
  packages/matter.js/src/protocol/MessageExchange.ts
  packages/matter.js/src/session/SecureSession.ts
  packages/matter.js/src/session/Session.ts
  packages/matter.js/src/session/UnsecureSession.ts
  packages/matter.js/test/codec/MessageTest.ts
Labels: review - approved

#551 Respect UDP packet maximum size
  packages/matter-node.js/src/net/UdpChannelNode.ts
  packages/matter.js/src/spec/Specifications.ts
Labels: review - approved

#554 [NIGHTLY DEV RELEASE] 0.7.2-alpha.0-20231202-8054e34e
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#555 Fix TemperatureMeasurement definition
  models/src/local/TemperatureMeasurementOverrides.ts
  models/src/local/index.ts
  packages/matter.js/src/cluster/definitions/TemperatureMeasurementCluster.ts
Labels: review - approved

#556 Fix TemperatureMeasurement definition (again)
  CHANGELOG.md
  models/src/local/TemperatureMeasurementOverrides.ts
  packages/matter.js/src/cluster/definitions/TemperatureMeasurementCluster.ts
  packages/matter.js/src/model/standard/elements/TemperatureMeasurement.ts
Labels: review - approved

#557 [NIGHTLY DEV RELEASE] 0.7.2-alpha.0-20231202-4c5a6707
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#565 [NIGHTLY DEV RELEASE] 0.7.3-alpha.0-20231205-f58a8489
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#566 Add CASE Authenticated Tags support
  packages/matter-node.js/test/IntegrationTest.ts
  packages/matter-node.js/test/certificate/CertificateManagerTest.ts
  packages/matter.js/src/CommissioningController.ts
  packages/matter.js/src/MatterController.ts
  packages/matter.js/src/certificate/CertificateManager.ts
  packages/matter.js/src/certificate/RootCertificateManager.ts
  packages/matter.js/src/datatype/CaseAuthenticatedTag.ts
  packages/matter.js/src/datatype/NodeId.ts
  packages/matter.js/src/datatype/export.ts
  packages/matter.js/src/fabric/Fabric.ts
  packages/matter.js/src/protocol/interaction/InteractionProtocol.ts
  packages/matter.js/src/session/SecureSession.ts
  packages/matter.js/src/tlv/TlvArray.ts
  packages/matter.js/src/tlv/TlvObject.ts
  packages/matter.js/test/datatype/CaseAuthenticatedTagTest.ts
  packages/matter.js/test/datatype/NodeIdTests.ts
  packages/matter.js/test/tlv/TlvObjectTest.ts
Labels: review - approved

#576 Update deps
  codegen/package.json
  codegen/src/mom/spec/translate-table.ts
  package-lock.json
  package.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node-shell.js/src/shell/cmd_commission.ts
  packages/matter-node-shell.js/src/shell/cmd_discover.ts
  packages/matter-node.js-examples/package.json
  packages/matter-node.js-examples/src/examples/ControllerNode.ts
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
  packages/matter.js/src/cluster/Cluster.ts
  packages/matter.js/src/cluster/server/ClusterServerTypes.ts
  packages/matter.js/src/util/Type.ts
Labels: review - approved

#577 Fix message size check
  packages/matter-node.js/src/net/UdpChannelNode.ts
  packages/matter.js/src/codec/MessageCodec.ts
  packages/matter.js/src/protocol/ExchangeManager.ts
Labels: review - approved

#580 Add validation handling to Invoke processing
  packages/matter-node.js/test/IntegrationTest.ts
  packages/matter-node.js/test/cluster/GroupsServerTest.ts
  packages/matter-node.js/test/cluster/ScenesServerTest.ts
  packages/matter-node.js/test/interaction/InteractionProtocolTest.ts
  packages/matter.js-tools/.gitignore
  packages/matter.js/src/MatterDevice.ts
  packages/matter.js/src/cluster/client/ClusterClient.ts
  packages/matter.js/src/cluster/definitions/GroupsCluster.ts
  packages/matter.js/src/cluster/definitions/ScenesCluster.ts
  packages/matter.js/src/cluster/server/AdministratorCommissioningServer.ts
  packages/matter.js/src/cluster/server/AttributeServer.ts
  packages/matter.js/src/cluster/server/CommandServer.ts
  packages/matter.js/src/cluster/server/GeneralCommissioningServer.ts
  packages/matter.js/src/cluster/server/GroupsServer.ts
  packages/matter.js/src/cluster/server/OperationalCredentialsServer.ts
  packages/matter.js/src/cluster/server/ScenesServer.ts
  packages/matter.js/src/common/MatterError.ts
  packages/matter.js/src/common/ValidationError.ts
  packages/matter.js/src/common/export.ts
  packages/matter.js/src/datatype/CaseAuthenticatedTag.ts
  packages/matter.js/src/device/PairedNode.ts
  packages/matter.js/src/protocol/MessageExchange.ts
  packages/matter.js/src/protocol/interaction/InteractionClient.ts
  packages/matter.js/src/protocol/interaction/InteractionMessenger.ts
  packages/matter.js/src/protocol/interaction/InteractionProtocol.ts
  packages/matter.js/src/protocol/interaction/InteractionServer.ts
  packages/matter.js/src/protocol/interaction/StatusCode.ts
  packages/matter.js/src/protocol/interaction/SubscriptionHandler.ts
  packages/matter.js/src/protocol/interaction/export.ts
  packages/matter.js/src/tlv/TlvAny.ts
  packages/matter.js/src/tlv/TlvArray.ts
  packages/matter.js/src/tlv/TlvBoolean.ts
  packages/matter.js/src/tlv/TlvNumber.ts
  packages/matter.js/src/tlv/TlvObject.ts
  packages/matter.js/src/tlv/TlvString.ts
  packages/matter.js/src/tlv/TlvVoid.ts
  packages/matter.js/test/cluster/AttributeServerTest.ts
  packages/matter.js/test/tlv/TlvAnyTest.ts
  packages/matter.js/test/tlv/TlvBooleanTest.ts
  packages/matter.js/test/tlv/TlvComplexTest.ts
  packages/matter.js/test/tlv/TlvNumberTest.ts
  packages/matter.js/test/tlv/TlvStringTest.ts
  packages/matter.js/test/tlv/TlvVoidTest.ts
Labels: review - approved

#581 [NIGHTLY DEV RELEASE] 0.7.3-alpha.0-20231215-b41f44f7
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#582 High level API fixes December 23
  CHANGELOG.md
  packages/matter-node-shell.js/src/shell/cmd_nodes.ts
  packages/matter-node.js-examples/src/examples/ControllerNode.ts
  packages/matter-node.js/test/IntegrationTest.ts
  packages/matter.js/src/CommissioningController.ts
  packages/matter.js/src/CommissioningServer.ts
  packages/matter.js/src/MatterServer.ts
  packages/matter.js/src/device/PairedNode.ts
Labels: review - approved

#584 [NIGHTLY DEV RELEASE] 0.7.3-alpha.0-20231217-383ffe47
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#583 Update README.md
  README.md
Labels: review - approved

#590 Session Refactoring to bring logic more near to specs
  CHANGELOG.md
  packages/matter-node.js/test/fabric/FabricTest.ts
  packages/matter-node.js/test/session/SecureSessionTest.ts
  packages/matter-node.js/test/session/SessionManagerTest.ts
  packages/matter.js/src/MatterController.ts
  packages/matter.js/src/MatterDevice.ts
  packages/matter.js/src/codec/MessageCodec.ts
  packages/matter.js/src/protocol/ExchangeManager.ts
  packages/matter.js/src/protocol/MessageCounter.ts
  packages/matter.js/src/protocol/MessageExchange.ts
  packages/matter.js/src/protocol/MessageReceptionState.ts
  packages/matter.js/src/protocol/export.ts
  packages/matter.js/src/session/SecureSession.ts
  packages/matter.js/src/session/Session.ts
  packages/matter.js/src/session/SessionManager.ts
  packages/matter.js/src/session/UnsecureSession.ts
  packages/matter.js/src/session/case/CaseClient.ts
  packages/matter.js/src/session/case/CaseServer.ts
  packages/matter.js/src/session/pase/PaseClient.ts
  packages/matter.js/src/session/pase/PaseServer.ts
  packages/matter.js/test/mdns/MdnsTest.ts
  packages/matter.js/test/protocol/MessageCounterTest.ts
  packages/matter.js/test/protocol/MessageReceptionStateTest.ts
Labels: review - approved

#594 [NIGHTLY DEV RELEASE] 0.7.4-alpha.0-20231223-ec1d465a
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#600 [NIGHTLY DEV RELEASE] 0.7.4-alpha.0-20231226-ae0424c2
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#595 Upgrade Interaction protocol revision to 11 (Matter 1.2) - Redone
  CHANGELOG.md
  packages/matter-node.js/test/IntegrationTest.ts
  packages/matter-node.js/test/interaction/InteractionProtocolTest.ts
  packages/matter.js-tools/src/testing/mocks/time.ts
  packages/matter.js/src/protocol/interaction/EventHandler.ts
  packages/matter.js/src/protocol/interaction/InteractionEndpointStructure.ts
  packages/matter.js/src/protocol/interaction/InteractionServer.ts
  packages/matter.js/src/protocol/interaction/SubscriptionHandler.ts
Labels: review - approved

#602 Add mising ColorControl overrides
  codegen/package.json
  codegen/src/clusters/TlvGenerator.ts
  models/src/local/ColorControlOverrides.ts
  package-lock.json
  packages/matter.js/src/cluster/definitions/ColorControlCluster.ts
  packages/matter.js/src/cluster/definitions/GroupsCluster.ts
  packages/matter.js/src/cluster/definitions/ScenesCluster.ts
  packages/matter.js/src/model/standard/elements/ColorControl.ts
Labels: review - approved

#603 [NIGHTLY DEV RELEASE] 0.7.4-alpha.0-20231227-954da7aa
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#605 Revamp and update readme
  KNOWN_ISSUES.md
  README.md
Labels: review - approved

#607 Update README.md
  README.md
Labels: review - pending
