Repository matter-js/matter.js, pull requests merged in 2023-11, with the labels that each got.

#469 [NIGHTLY DEV RELEASE] 0.6.1-alpha.0-20231101-4ef32c9
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js/package.json
  tools/package.json
Labels: automated pr

#471 Fix special case with channel replacement to fix tests
  .github/workflows/chip-tool-tests.yml
  chip-testing/src/DeviceTestInstance.ts
  chip-testing/test/ChipTest.ts
  packages/matter.js/src/protocol/ChannelManager.ts
  packages/matter.js/src/protocol/ExchangeManager.ts
  packages/matter.js/src/protocol/MessageExchange.ts
  packages/matter.js/src/session/Session.ts
  packages/matter.js/src/session/UnsecureSession.ts
Labels: hotfix

#472 [NIGHTLY DEV RELEASE] 0.6.1-alpha.0-20231102-e09231e
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js/package.json
  tools/package.json
Labels: automated pr

#458 Really remove text QRCode being returned
  packages/matter.js/src/CommissioningServer.ts
Labels: enhancement, review - approved

#478 Update README.md
  README.md
Labels: review - approved

#480 Always log build errors
  .github/actions/prepare-env/action.yml
Labels: review - approved

#487 take out macos tests till upstream fixes come in
  .github/actions/prepare-env/action.yml
  .github/workflows/build-test.js.yml
  packages/matter-node.js/test/IntegrationTest.ts
Labels: review - approved

#490 [NIGHTLY DEV RELEASE] 0.6.1-alpha.0-20231106-8322fa6
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js/package.json
  tools/package.json
Labels: automated pr

#473 Scanner, Discovery and Controller enhancements
  CHANGELOG.md
  packages/matter-node-ble.js/src/ble/BleScanner.ts
  packages/matter-node-shell.js/src/MatterNode.ts
  packages/matter-node-shell.js/src/app.ts
  packages/matter-node-shell.js/src/shell/Shell.ts
  packages/matter-node-shell.js/src/shell/cmd_commission.ts
  packages/matter-node-shell.js/src/shell/cmd_config.ts
  packages/matter-node-shell.js/src/shell/cmd_discover.ts
  packages/matter-node-shell.js/src/shell/cmd_identify.ts
  packages/matter-node-shell.js/src/shell/cmd_lock.ts
  packages/matter-node-shell.js/src/shell/cmd_nodes.ts
  packages/matter-node-shell.js/src/shell/cmd_onoff.ts
  packages/matter-node-shell.js/src/shell/cmd_session.ts
  packages/matter-node-shell.js/src/shell/cmd_subscribe.ts
  packages/matter-node.js-examples/src/examples/ControllerNode.ts
  packages/matter-node.js/test/IntegrationTest.ts
  packages/matter.js/src/CommissioningController.ts
  packages/matter.js/src/MatterController.ts
  packages/matter.js/src/cluster/server/AdministratorCommissioningServer.ts
  packages/matter.js/src/common/Scanner.ts
  packages/matter.js/src/device/PairedNode.ts
  packages/matter.js/src/mdns/MdnsScanner.ts
  packages/matter.js/src/protocol/ControllerDiscovery.ts
  packages/matter.js/src/util/Cache.ts
  packages/matter.js/src/util/Promises.ts
  packages/matter.js/test/mdns/MdnsTest.ts
Labels: review - approved

#475 Use Netinterface limitation also for scanner
  CHANGELOG.md
  packages/matter-node-shell.js/src/MatterNode.ts
  packages/matter-node-shell.js/src/app.ts
  packages/matter-node.js-examples/README.md
  packages/matter-node.js-examples/src/examples/BridgedDevicesNode.ts
  packages/matter-node.js-examples/src/examples/ComposedDeviceNode.ts
  packages/matter-node.js-examples/src/examples/DeviceNode.ts
  packages/matter-node.js-examples/src/examples/MultiDeviceNode.ts
  packages/matter.js/src/MatterServer.ts
Labels: review - approved

#492 [NIGHTLY DEV RELEASE] 0.6.1-alpha.0-20231107-8ef79b7
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js/package.json
  tools/package.json
Labels: automated pr

#493 Fix missing cjs usage in examples
  packages/matter-node-ble.js/package.json
  packages/matter-node-ble.js/require/package.json
  packages/matter-node.js-examples/package.json
Labels: review - approved

#494 [NIGHTLY DEV RELEASE] 0.6.1-alpha.0-20231107-3cab6a1
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js/package.json
  tools/package.json
Labels: automated pr

#495 Restore deleted require/package.json for Node.js 12 & before compatibility
  packages/matter-node-ble.js/require/package.json
Labels: review - approved

#496 [NIGHTLY DEV RELEASE] 0.6.1-alpha.0-20231107-ecff055
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js/package.json
  tools/package.json
Labels: automated pr

#421 Fix incorrect net interface zone for UdpChannelNode on Windows
  packages/matter-node.js/src/net/NetworkNode.ts
  packages/matter-node.js/src/net/UdpChannelNode.ts
Labels: review - approved

#497 Switch network cleanup to beforeExit
  packages/matter-node.js-examples/src/examples/BridgedDevicesNode.ts
  packages/matter-node.js-examples/src/examples/ComposedDeviceNode.ts
  packages/matter-node.js-examples/src/examples/ControllerNode.ts
  packages/matter-node.js-examples/src/examples/DeviceNode.ts
  packages/matter-node.js-examples/src/examples/MultiDeviceNode.ts
  packages/matter-node.js/src/net/register.ts
Labels: review - approved

#498 [NIGHTLY DEV RELEASE] 0.6.1-alpha.0-20231108-f1d82f9
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js/package.json
  tools/package.json
Labels: automated pr

#499 Finalize for next version
  CHANGELOG.md
  packages/matter.js/src/MatterDevice.ts
  packages/matter.js/src/device/PairedNode.ts
Labels: review - approved

#500 Fix package.jsons from recent changes
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node.js-examples/package.json
Labels: review - approved

#501 Publish the tools package to npm
  tools/package.json
Labels: review - pending, hotfix

#502 Fix tools package and mergify config for hotfix
  .mergify.yml
  tools/package.json
Labels: hotfix

#503 [NIGHTLY DEV RELEASE] 0.6.1-alpha.0-20231109-9f2ed08
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js/package.json
  tools/package.json
Labels: automated pr

#504 Reactivate macos testing by downgrading python in github runner
  .github/workflows/build-test.js.yml
  .github/workflows/release-npm.yml
Labels: review - approved

#506 [NIGHTLY DEV RELEASE] 0.6.1-alpha.0-20231110-7da3804
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#507 [NIGHTLY DEV RELEASE] 0.6.1-alpha.0-20231110-2ec0f70
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#508 Optimize Port determination
  packages/matter.js/src/MatterServer.ts
Labels: review - approved

#509 MatterServer node start optimizations
  CHANGELOG.md
  chip-testing/src/DeviceTestInstance.ts
  packages/matter-node-shell.js/src/MatterNode.ts
  packages/matter-node.js-examples/src/examples/BridgedDevicesNode.ts
  packages/matter-node.js-examples/src/examples/ComposedDeviceNode.ts
  packages/matter-node.js-examples/src/examples/ControllerNode.ts
  packages/matter-node.js-examples/src/examples/DeviceNode.ts
  packages/matter-node.js-examples/src/examples/MultiDeviceNode.ts
  packages/matter-node.js/test/IntegrationTest.ts
  packages/matter.js/src/CommissioningController.ts
  packages/matter.js/src/CommissioningServer.ts
  packages/matter.js/src/MatterNode.ts
  packages/matter.js/src/MatterServer.ts
Labels: review - approved

#510 More robust tooling bootstrap
  packages/matter.js-tools/src/util/bootstrap.mjs
Labels: review - approved

#511 Increase retries for automerge logic for releases
  .github/workflows/release-npm.yml
Labels: review - approved

#512 [NIGHTLY DEV RELEASE] 0.6.1-alpha.0-20231111-0f49576
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#519 [NIGHTLY DEV RELEASE] 0.7.1-alpha.0-20231115-c92b1b1
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#520 [NIGHTLY DEV RELEASE] 0.7.1-alpha.0-20231116-47f3a17
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#523 Add some convenience methods for controller/pairedNode
  CHANGELOG.md
  packages/matter.js/src/device/PairedNode.ts
Labels: review - approved

#521 Optimize Exchange deletion
  packages/matter.js/src/protocol/ExchangeManager.ts
Labels: review - approved

#522 Add method to cancel discovery of commissionable devices
  packages/matter.js/src/CommissioningController.ts
Labels: review - approved

#525 [NIGHTLY DEV RELEASE] 0.7.1-alpha.0-20231118-0ebd1ae
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#538 [NIGHTLY DEV RELEASE] 0.7.1-alpha.0-20231122-117f4c6
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#540 [NIGHTLY DEV RELEASE] 0.7.1-alpha.0-20231123-ba19d42
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#541 [NIGHTLY DEV RELEASE] 0.7.1-alpha.0-20231123-a7b3779
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr
