Repository matter-js/matter.js, pull requests merged in 2024-12, with the labels that each got.

#1467 Expand details on flic ecosystem
  docs/ECOSYSTEMS.md
Labels: review - approved

#1470 [NIGHTLY DEV RELEASE] 0.11.9-alpha.0-20241203-06077d82e
  version.txt
Labels: automated pr

#1471 Readme and Compatibility info cleanup
  README.md
  docs/MATTER_COMPATIBILITY.md
Labels: review - approved

#1469 Removes default value from attribute ColorMode of ColorControl cluster because feature specific enum value was used
  CHANGELOG.md
  models/src/local/ColorControlOverrides.ts
  packages/model/src/standard/elements/ColorControl.ts
  packages/node/src/behavior/state/validation/assertions.ts
  packages/node/src/behaviors/color-control/ColorControlServer.ts
  packages/types/src/clusters/color-control.ts
Labels: review - approved

#1472 Upgrades to TypeScript 5.7
  package-lock.json
  package.json
  packages/create/package.json
  packages/general/src/util/DeepCopy.ts
  packages/protocol/src/certificate/CertificateAuthority.ts
  packages/react-native/package.json
  packages/testing/package.json
  packages/tools/package.json
Labels: review - approved

#1479 [NIGHTLY DEV RELEASE] 0.11.9-alpha.0-20241205-ccf69a00a
  version.txt
Labels: automated pr

#1477 Optimize decommissioning
  CHANGELOG.md
  packages/matter.js/src/CommissioningController.ts
  packages/matter.js/src/device/PairedNode.ts
Labels: review - approved

#1481 Retry next address also open channel establishment error
  CHANGELOG.md
  packages/protocol/src/peer/ControllerCommissioner.ts
Labels: review - approved

#1482 Fix endpoint codegen & run
  codegen/src/clusters/GeneratorScope.ts
  packages/node/src/behaviors/refrigerator-alarm/RefrigeratorAlarmInterface.ts
  packages/node/src/behaviors/rvc-operational-state/RvcOperationalStateInterface.ts
Labels: review - approved

#1483 Allow to use Deprecated fields
  CHANGELOG.md
  codegen/src/clusters/ClusterComponentGenerator.ts
  codegen/src/clusters/TlvGenerator.ts
  codegen/src/endpoints/TypeGenerator.ts
  codegen/src/util/TsFile.ts
  models/src/local/PumpConfigurationAndControlOverrides.ts
  models/src/local/WindowCoveringOverrides.ts
  packages/model/src/logic/DefaultValue.ts
  packages/model/src/logic/Scope.ts
  packages/model/src/standard/elements/PumpConfigurationAndControl.ts
  packages/model/src/standard/elements/WindowCovering.ts
  packages/node/src/behavior/state/managed/values/BitmapManager.ts
  packages/node/src/behavior/state/managed/values/ValueCaster.ts
  packages/node/src/behavior/state/validation/ValueValidator.ts
  packages/node/test/behaviors/fan-control/FanControlTest.ts
  packages/types/src/clusters/fan-control.ts
  packages/types/src/clusters/pump-configuration-and-control.ts
  packages/types/src/clusters/thermostat.ts
Labels: review - approved

#1486 [NIGHTLY DEV RELEASE] 0.11.9-alpha.0-20241206-22f233334
  version.txt
Labels: automated pr

#1484 WindowCovering default implementation enhancement
  CHANGELOG.md
  packages/node/src/behaviors/window-covering/WindowCoveringServer.ts
Labels: review - approved

#1487 [NIGHTLY DEV RELEASE] 0.11.9-alpha.0-20241207-b604cfa44
  version.txt
Labels: automated pr

#1488 Optimizes reconnection handling in Controller API
  CHANGELOG.md
  packages/matter.js/src/device/PairedNode.ts
Labels: review - approved

#1489 [NIGHTLY DEV RELEASE] 0.11.9-alpha.0-20241208-09ad57f78
  version.txt
Labels: automated pr

#1495 More MDNS optimizations
  CHANGELOG.md
  packages/protocol/src/interaction/ServerSubscription.ts
  packages/protocol/src/mdns/MdnsScanner.ts
  packages/protocol/test/mdns/MdnsTest.ts
Labels: review - approved

#1497 [NIGHTLY DEV RELEASE] 0.11.9-alpha.0-20241209-06a8040e1
  version.txt
Labels: automated pr

#1498 Adjust config to simulate not yet existing scripts
  .github/workflows/chip-tool-tests.yml
Labels: review - pending

#1509 [OFFICIAL RELEASE] 0.11.9
  CHANGELOG.md
  version.txt
Labels: automated pr

#1500 Minor tooling updates
  .vscode/extensions.json
  .vscode/launch.json
  codegen/src/generate-vscode.ts
  packages/tools/package.json
  packages/tools/src/building/project.ts
  packages/tools/src/index.ts
  packages/tools/src/running/cli.ts
  packages/tools/src/running/ensure-compiled.ts
  packages/tools/src/util/bootstrap.mjs
  packages/tools/src/util/progress.ts
Labels: review - approved

#1502 Event persistence
  CHANGELOG.md
  packages/matter.js/src/CommissioningServer.ts
  packages/matter.js/src/cluster/server/ClusterServer.ts
  packages/matter.js/src/cluster/server/GroupKeyManagementServer.ts
  packages/matter.js/src/compat/interaction.ts
  packages/matter.js/src/device/LegacyInteractionServer.ts
  packages/matter.js/test/cluster/ClusterServerTest.ts
  packages/node/src/behavior/system/events/EventsBehavior.ts
  packages/node/src/behavior/system/events/index.ts
  packages/node/src/endpoint/server/BehaviorServer.ts
  packages/node/src/node/ServerNode.ts
  packages/node/src/node/server/TransactionalInteractionServer.ts
  packages/nodejs/test/interaction/InteractionProtocolTest.ts
  packages/protocol/src/certificate/DeviceCertification.ts
  packages/protocol/src/cluster/server/ClusterDatasource.ts
  packages/protocol/src/cluster/server/EventServer.ts
  packages/protocol/src/events/BaseEventStore.ts
  packages/protocol/src/events/EventStore.ts
  packages/protocol/src/events/NonvolatileEventStore.ts
  packages/protocol/src/events/Occurrence.ts
  packages/protocol/src/events/OccurrenceManager.ts
  packages/protocol/src/events/VolatileEventStore.ts
  packages/protocol/src/events/index.ts
  packages/protocol/src/index.ts
  packages/protocol/src/interaction/EventHandler.ts
  packages/protocol/src/interaction/InteractionServer.ts
  packages/protocol/src/interaction/ServerSubscription.ts
  packages/protocol/src/interaction/index.ts
  packages/protocol/src/mdns/MdnsBroadcaster.ts
  packages/protocol/src/mdns/MdnsScanner.ts
Labels: review - approved

#1503 Handful of batch invoke fixes
  CHANGELOG.md
  packages/nodejs/test/interaction/InteractionProtocolTest.ts
  packages/protocol/src/interaction/InteractionServer.ts
Labels: review - approved

#1508 Configurable commissioning window extents
  packages/node/src/behaviors/administrator-commissioning/AdministratorCommissioningServer.ts
Labels: review - approved

#1501 Container for CHIP
  chip/Dockerfile
  chip/README.md
  chip/build
  chip/publish
  chip/pull
  chip/rebuild
  chip/shell
  chip/tool
  chip/ubuntu-arm64.sources
  packages/testing/chip/Dockerfile
Labels: review - approved

#1512 Add MutableEndpoint.withBehaviors implementation
  CHANGELOG.md
  packages/node/src/endpoint/type/MutableEndpoint.ts
Labels: review - approved

#1504 GeneralDiagnostics fixes for TC_DGGEN_2_4
  packages/general/src/time/Time.ts
  packages/node/src/behaviors/general-diagnostics/GeneralDiagnosticsServer.ts
  packages/nodejs/src/index.ts
  packages/nodejs/src/net/NodeJsUdpChannel.ts
  packages/nodejs/src/time/index.ts
  packages/nodejs/src/time/startup.ts
  packages/testing/src/mocks/time.ts
Labels: review - approved

#1513 [NIGHTLY DEV RELEASE] 0.12.0-alpha.0-20241211-6d80d8b5c
  version.txt
Labels: automated pr

#1506 Updates for Operational Credentials cert tests
  packages/node/src/behaviors/operational-credentials/OperationalCredentialsServer.ts
  packages/protocol/src/common/FailsafeContext.ts
  packages/protocol/src/fabric/Fabric.ts
Labels: review - approved

#1514 Remove WIP tests from chip-testing
  chip-testing/test/AccessCheckerTest.ts
  chip-testing/test/AceTest.ts
  chip-testing/test/AclTest.ts
  chip-testing/test/CadminTest.ts
  chip-testing/test/CgenTest.ts
  chip-testing/test/DaTest.ts
  chip-testing/test/DeviceBasicCompositionTest.ts
  chip-testing/test/DggenTest.ts
  chip-testing/test/IdmTest.ts
  chip-testing/test/OpcredsTest.ts
  chip-testing/test/PwrtlTest.ts
  chip-testing/test/README.md
  chip-testing/test/ScTest.ts
  chip-testing/test/SwtchTest.ts
  chip-testing/test/TestEventTriggerTest.ts
Labels: review - approved

#1517 [NIGHTLY DEV RELEASE] 0.12.0-alpha.0-20241213-fcd71a96d
  version.txt
Labels: automated pr

#1520 Update typedocs of SwitchServer
  packages/node/src/behaviors/switch/SwitchServer.ts
Labels: review - approved

#1521 Fix load of event reservation end
  packages/node/src/behavior/system/events/EventsBehavior.ts
  packages/protocol/src/events/BaseEventStore.ts
Labels: review - approved

#1523 Minor tweaks to @matter/general
  packages/general/src/environment/Environmental.ts
  packages/general/src/environment/RuntimeService.ts
  packages/general/src/storage/Storage.ts
  packages/general/src/storage/StorageBackendMemory.ts
  packages/general/src/util/Construction.ts
  packages/general/src/util/String.ts
Labels: review - approved

#1522 Workaround for node bug 56219
  packages/general/src/codec/Base64Codec.ts
Labels: review - approved

#1524 [NIGHTLY DEV RELEASE] 0.12.0-alpha.0-20241216-01bff7bc4
  version.txt
Labels: automated pr

#1530 MDNS FIxes and small stuff
  CHANGELOG.md
  packages/general/src/util/PromiseQueue.ts
  packages/nodejs/test/IntegrationTest.ts
  packages/protocol/src/cluster/server/AttributeServer.ts
  packages/protocol/src/common/FailsafeContext.ts
  packages/protocol/src/interaction/InteractionServer.ts
  packages/protocol/src/mdns/MdnsScanner.ts
  packages/protocol/src/peer/PeerSet.ts
Labels: review - approved

#1531 Ignore TestUserLabelClusterConstraints
  .github/workflows/chip-tool-tests.yml
  .github/workflows/nightly-dev-release.yml
  .github/workflows/official-release.yml
Labels: review - approved

#1533 [NIGHTLY DEV RELEASE] 0.12.0-alpha.0-20241218-de74d9dc7
  version.txt
Labels: automated pr

#1532 Improve construction error handling
  packages/general/src/log/Diagnostic.ts
  packages/general/src/log/Logger.ts
  packages/general/src/util/Construction.ts
  packages/general/test/log/LoggerTest.ts
  packages/node/src/behavior/internal/BehaviorBacking.ts
  packages/node/src/endpoint/properties/Behaviors.ts
  packages/node/test/endpoint/EndpointTest.ts
  packages/node/test/endpoint/type/MutableEndpointTest.ts
  packages/testing/src/cli.ts
Labels: review - approved

#1535 [NIGHTLY DEV RELEASE] 0.12.0-alpha.0-20241219-af74a6a14
  version.txt
Labels: automated pr

#1539 Metadata extractor for CHIP tests
  chip/Dockerfile
  chip/generate-test-descriptor
Labels: review - approved

#1538 Additional utilities for managing containers
  packages/testing/src/docker/composition.ts
  packages/testing/src/docker/container.ts
  packages/testing/src/docker/docker.ts
  packages/testing/src/docker/edit.ts
  packages/testing/src/docker/errors.ts
  packages/testing/src/docker/index.ts
  packages/testing/src/docker/network.ts
  packages/testing/src/docker/terminal.ts
  packages/testing/src/docker/volume.ts
  packages/testing/src/index.ts
  packages/testing/src/util/text.ts
Labels: review - approved

#1537 Generalize glob implementation
  chip-testing/src/cluster/TestWindowCoveringServer.ts
  package-lock.json
  packages/node/src/behaviors/color-control/ColorControlServer.ts
  packages/node/src/behaviors/general-diagnostics/GeneralDiagnosticsServer.ts
  packages/node/src/behaviors/identify/IdentifyServer.ts
  packages/node/src/behaviors/level-control/LevelControlServer.ts
  packages/node/src/behaviors/on-off/OnOffServer.ts
  packages/node/src/behaviors/switch/SwitchServer.ts
  packages/node/src/behaviors/window-covering/WindowCoveringServer.ts
  packages/tools/package.json
  packages/tools/src/building/docs.ts
  packages/tools/src/index.ts
  packages/tools/src/util/file.ts
  packages/tools/src/util/glob.ts
  packages/tools/src/util/index.ts
  packages/tools/src/util/package.ts
Labels: review - approved

#1541 [NIGHTLY DEV RELEASE] 0.12.0-alpha.0-20241220-ad0dea627
  version.txt
Labels: automated pr

#1536 MDNS and Reconnection optimizations
  .github/workflows/chip-tool-tests.yml
  CHANGELOG.md
  packages/matter.js/src/CommissioningController.ts
  packages/matter.js/src/MatterController.ts
  packages/matter.js/src/device/PairedNode.ts
  packages/protocol/src/certificate/CertificateAuthority.ts
  packages/protocol/src/interaction/InteractionMessenger.ts
  packages/protocol/src/mdns/MdnsScanner.ts
  packages/protocol/src/mdns/MdnsServer.ts
  packages/protocol/src/peer/ControllerDiscovery.ts
  packages/protocol/src/peer/PeerSet.ts
  packages/protocol/src/protocol/MessageExchange.ts
Labels: review - approved

#1540 CHIP test harness
  chip-testing/test/test.config.ts
  package-lock.json
  packages/testing/bin/test.js
  packages/testing/package.json
  packages/testing/src/chip/accessory-server.ts
  packages/testing/src/chip/chip-test-common.ts
  packages/testing/src/chip/chip.ts
  packages/testing/src/chip/command-pipe.ts
  packages/testing/src/chip/config.ts
  packages/testing/src/chip/container-command-pipe.ts
  packages/testing/src/chip/index.ts
  packages/testing/src/chip/manual-test.ts
  packages/testing/src/chip/matter-js-pics.properties
  packages/testing/src/chip/pics-expression.ts
  packages/testing/src/chip/pics-file.ts
  packages/testing/src/chip/python-test.ts
  packages/testing/src/chip/state.ts
  packages/testing/src/chip/support.ts
  packages/testing/src/chip/yaml-test.ts
  packages/testing/src/cli.ts
  packages/testing/src/device/backchannel.ts
  packages/testing/src/device/index.ts
  packages/testing/src/device/subject.ts
  packages/testing/src/device/test.ts
  packages/testing/src/global-declarations.ts
  packages/testing/src/global-definitions.ts
  packages/testing/src/index.ts
  packages/testing/src/inspect.ts
  packages/testing/src/mocha.ts
  packages/testing/src/mocks/logging.ts
  packages/testing/src/nodejs.ts
  packages/testing/src/reporter.ts
  packages/testing/src/runner.ts
  packages/testing/src/test-descriptor.ts
  packages/testing/src/tsconfig.json
Labels: review - approved

#1542 Allow to manually trigger nightlies without chip tests
  .github/workflows/nightly-dev-release.yml
Labels: review - approved

#1543 [NIGHTLY DEV RELEASE] 0.12.0-alpha.0-20241220-c66941cd7
  version.txt
Labels: automated pr

#1546 [NIGHTLY DEV RELEASE] 0.12.0-alpha.0-20241220-2c53108aa
  version.txt
Labels: automated pr

#1548 [NIGHTLY DEV RELEASE] 0.12.0-alpha.0-20241220-755393a73
  version.txt
Labels: automated pr

#1550 Use data type definitions from Model for Controller Device type definitions
  CHANGELOG.md
  packages/matter.js/src/device/DeviceTypes.ts
  packages/matter.js/src/device/PairedNode.ts
Labels: review - approved

#1556 Fix package lock
  CHANGELOG.md
  package-lock.json
Labels: review - pending

#1561 [NIGHTLY DEV RELEASE] 0.12.0-alpha.0-20241225-902d76201
  version.txt
Labels: automated pr

#1560 Fix hang on exit of AllClustersTestApp
  chip-testing/src/NamedPipeCommandHandler.ts
Labels: review - approved

#1559 Remove workspace dependency from CHIP testing
  packages/testing/src/chip/config.ts
  packages/testing/src/chip/state.ts
Labels: review - approved

#1557 Fix inspection of MatterAggregateError
  packages/general/src/MatterError.ts
Labels: review - approved

#1564 [NIGHTLY DEV RELEASE] 0.12.0-alpha.0-20241226-0f5b0fe87
  version.txt
Labels: automated pr

#1565 Fixes for CHIP command pipe handling
  chip-testing/src/AllClustersTestInstance.ts
  chip-testing/src/NamedPipeCommandHandler.ts
  chip-testing/test/app-fast/SWTCH.test.ts
  packages/testing/src/chip/chip.ts
  packages/testing/src/chip/command-pipe.ts
  packages/testing/src/chip/config.ts
  packages/testing/src/chip/container-command-pipe.ts
  packages/testing/src/chip/state.ts
  packages/testing/src/device/backchannel.ts
  packages/testing/src/docker/terminal.ts
Labels: review - approved

#1567 Ignore SWTCH python test error for now
  .github/workflows/chip-tool-tests.yml
Labels: review - approved

#1566 Optimize New-Session-Reconnect handling
  packages/matter.js/src/device/PairedNode.ts
  packages/protocol/src/session/SecureSession.ts
Labels: review - approved

#1569 Workarounds for fifo weirdness
  chip-testing/src/NamedPipeCommandHandler.ts
  packages/testing/src/chip/command-pipe.ts
  packages/testing/src/chip/container-command-pipe.ts
  packages/testing/src/docker/container.ts
  packages/testing/src/docker/terminal.ts
  packages/testing/src/util/text.ts
Labels: review - approved

#1563 Arm failsafe on PASE establishment
  CHANGELOG.md
  packages/node/src/behaviors/general-commissioning/GeneralCommissioningServer.ts
Labels: review - approved

#1562 Adds FabricLabel support to Controller
  CHANGELOG.md
  compat/matter-node.js-examples/src/examples/ControllerNodeLegacy.ts
  packages/examples/src/controller/ControllerNode.ts
  packages/examples/src/controller/README.md
  packages/matter.js/src/CommissioningController.ts
  packages/matter.js/src/MatterController.ts
  packages/matter.js/src/PaseCommissioner.ts
  packages/matter.js/src/device/PairedNode.ts
  packages/node/src/behavior/system/controller/ControllerBehavior.ts
  packages/nodejs-shell/src/MatterNode.ts
  packages/nodejs-shell/src/shell/cmd_config.ts
  packages/nodejs/test/IntegrationTest.ts
  packages/protocol/src/fabric/Fabric.ts
  packages/protocol/src/fabric/FabricAuthority.ts
  packages/protocol/src/peer/ControllerCommissioningFlow.ts
Labels: review - approved

#1571 [NIGHTLY DEV RELEASE] 0.12.0-alpha.0-20241227-9e7d81837
  version.txt
Labels: automated pr

#1572 initialize Storage before accessing it
  packages/nodejs-shell/src/MatterNode.ts
Labels: review - approved

#1575 [NIGHTLY DEV RELEASE] 0.12.0-alpha.0-20241228-9f74a0273
  version.txt
Labels: automated pr

#1580 Correctly check object for events
  packages/protocol/src/events/OccurrenceManager.ts
Labels: review - approved

#1574 No Resubscribe after disconnect
  CHANGELOG.md
  packages/matter.js/src/device/PairedNode.ts
  packages/protocol/src/peer/PeerSet.ts
  packages/protocol/src/session/SecureSession.ts
Labels: review - approved

#1576 Fix tool paths in launch.json
  .vscode/launch.json
Labels: review - approved

#1578 Model diff tool
  packages/cli-tool/src/cli.ts
  packages/cli-tool/src/commands/cat.ts
  packages/cli-tool/src/commands/cd.ts
  packages/cli-tool/src/commands/command.ts
  packages/cli-tool/src/commands/diff-spec.ts
  packages/cli-tool/src/commands/help.ts
  packages/cli-tool/src/commands/index.ts
  packages/cli-tool/src/commands/ls.ts
  packages/cli-tool/src/commands/rm.ts
  packages/cli-tool/src/commands/set.ts
  packages/cli-tool/src/domain.ts
  packages/cli-tool/src/parser.ts
  packages/general/src/log/Diagnostic.ts
  packages/general/src/log/LogFormat.ts
  packages/model/src/common/FieldValue.ts
  packages/model/src/common/Metatype.ts
  packages/model/src/common/Specification.ts
  packages/model/src/logic/ModelDiff.ts
  packages/model/src/logic/index.ts
  packages/node/src/behavior/state/managed/values/ValueCaster.ts
Labels: review - approved

#1579 Resurrect web tests with `npm test` at root
  package.json
  packages/testing/src/cli.ts
  packages/tools/src/util/package.ts
Labels: review - approved

#1573 Catch UDP errors that are thrown directly
  packages/general/src/util/Error.ts
  packages/nodejs/src/net/NodeJsUdpChannel.ts
  packages/protocol/src/peer/ControllerCommissioningFlow.ts
  packages/react-native/src/net/UdpChannelReactNative.ts
Labels: review - approved

#1577 Remove dump-model-names utility
  codegen/bin/dump-model-names.js
  codegen/package.json
  codegen/src/dump-model-names.ts
Labels: review - approved

#1581 Update Fan Support in supported ecosystems
  docs/ECOSYSTEMS.md
Labels: review - approved

#1582 [NIGHTLY DEV RELEASE] 0.12.0-alpha.0-20241229-9d9c99934
  version.txt
Labels: automated pr

#1583 Add expression support to constraint AST
  packages/model/src/aspects/Constraint.ts
  packages/model/src/common/FieldValue.ts
Labels: review - approved

#1584 New constraint parser
  CHANGELOG.md
  packages/model/src/aspects/Constraint.ts
  packages/model/src/common/FieldValue.ts
  packages/model/src/logic/definition-validation/ValueValidator.ts
  packages/model/src/parser/Lexer.ts
  packages/model/src/parser/Token.ts
  packages/model/src/parser/TokenStream.ts
  packages/model/test/MatterTest.ts
  packages/model/test/aspects/ConstraintTest.ts
  packages/node/test/behavior/state/validation/constraintTest.ts
Labels: review - approved

#1592 Matter 1.4 constraint support
  CHANGELOG.md
  packages/model/src/aspects/Constraint.ts
  packages/model/src/parser/Lexer.ts
  packages/model/src/parser/Token.ts
  packages/model/test/aspects/ConstraintTest.ts
  packages/node/src/behavior/state/validation/constraint.ts
  packages/node/test/behavior/state/validation/constraintTest.ts
Labels: review - approved

#1593 Increase spec generator heap size
  .vscode/launch.json
  codegen/bin/generate-spec.js
  codegen/src/generate-vscode.ts
  packages/tools/src/running/cli.ts
  packages/tools/src/running/execute.ts
Labels: review - approved

#1586 Shutdown and promise optimizations
  CHANGELOG.md
  packages/general/src/MatterError.ts
  packages/general/src/net/UdpMulticastServer.ts
  packages/general/src/storage/StorageContext.ts
  packages/general/src/util/Promises.ts
  packages/node/src/behavior/system/controller/ControllerBehavior.ts
  packages/node/src/behavior/system/controller/discovery/Discovery.ts
  packages/node/src/behavior/system/network/NetworkRuntime.ts
  packages/node/src/behavior/system/network/ServerNetworkRuntime.ts
  packages/node/src/node/storage/ClientStoreService.ts
  packages/nodejs/src/storage/StorageBackendDiskAsync.ts
  packages/protocol/src/cluster/server/EventServer.ts
  packages/protocol/src/events/NonvolatileEventStore.ts
  packages/protocol/src/events/OccurrenceManager.ts
  packages/protocol/src/interaction/InteractionServer.ts
  packages/protocol/src/interaction/ServerSubscription.ts
  packages/protocol/src/mdns/MdnsServer.ts
  packages/protocol/src/mdns/MdnsService.ts
  packages/protocol/src/protocol/DeviceAdvertiser.ts
  packages/protocol/src/protocol/ExchangeManager.ts
  packages/protocol/src/session/SessionManager.ts
  packages/protocol/test/mdns/MdnsTest.ts
Labels: review - approved

#1594 Ignore invalid partslist entries
  packages/matter.js/src/device/PairedNode.ts
Labels: review - approved

#1596 [NIGHTLY DEV RELEASE] 0.12.0-alpha.0-20241231-14ac774ba
  version.txt
Labels: automated pr

#1595 Tighten up endpoint logic
  packages/node/src/endpoint/server/EndpointServer.ts
Labels: review - approved

#1597 [NIGHTLY DEV RELEASE] 0.12.0-alpha.0-20241231-9ac20db97
  version.txt
Labels: automated pr

#1599 Update Noble and Add "empty" Log flag for subscriptions
  package-lock.json
  packages/nodejs-ble/package.json
  packages/protocol/src/interaction/InteractionMessenger.ts
Labels: review - approved
