Repository matter-js/matter.js, pull requests merged in 2024-11, with the labels that each got.

#1346 [NIGHTLY DEV RELEASE] 0.11.2-alpha.0-20241101-15d283a0e
  version.txt
Labels: automated pr

#1347 Documentation generator
  compat/matter-node-ble.js/package.json
  compat/matter-node.js/package.json
  package-lock.json
  package.json
  packages/matter.js/package.json
  packages/model/src/models/MatterModel.ts
  packages/node/src/endpoint/Endpoint.ts
  packages/node/src/endpoint/properties/EndpointInitializer.ts
  packages/nodejs-ble/package.json
  packages/react-native/package.json
  packages/tools/README.md
  packages/tools/package.json
  packages/tools/src/building/builder.ts
  packages/tools/src/building/cli.ts
  packages/tools/src/building/docs.ts
  packages/tools/src/index.ts
  packages/tools/src/util/file.ts
  packages/tools/src/util/index.ts
  packages/tools/src/util/package.ts
  packages/tools/src/util/progress.ts
Labels: review - approved

#1349 [NIGHTLY DEV RELEASE] 0.11.2-alpha.0-20241102-aa282dab8
  version.txt
Labels: automated pr

#1350 Fixes some compatibility re-exports that got screwed up since 0.11.0
  CHANGELOG.md
  packages/matter.js/package.json
  packages/nodejs-shell/src/shell/cmd_tlv.ts
Labels: review - approved

#1351 Automatically lock state on invoke
  CHANGELOG.md
  packages/node/src/behavior/Behavior.ts
  packages/node/src/behavior/cluster/ClusterBehavior.ts
  packages/node/src/behavior/internal/ClusterServerBacking.ts
  packages/node/src/behavior/state/transaction/Resource.ts
  packages/node/src/behaviors/administrator-commissioning/AdministratorCommissioningServer.ts
  packages/node/src/behaviors/general-commissioning/GeneralCommissioningServer.ts
  packages/protocol/src/protocol/DeviceCommissioner.ts
Labels: review - approved

#1352 [OFFICIAL RELEASE] 0.11.2
  CHANGELOG.md
  version.txt
Labels: automated pr

#1353 Documentation Links fix
  docs/MIGRATION_GUIDE_08.md
Labels: review - approved

#1358 Optimize Async Storage
  CHANGELOG.md
  packages/main/README.md
  packages/node/src/endpoint/storage/EndpointStore.ts
  packages/nodejs-shell/src/MatterNode.ts
  packages/nodejs/src/storage/StorageBackendDiskAsync.ts
Labels: review - approved

#1359 [NIGHTLY DEV RELEASE] 0.11.3-alpha.0-20241105-ecad0373d
  version.txt
Labels: automated pr

#1361 Documentation: adding macOS requirements for Bluetooth using
  docs/TROUBLESHOOTING.md
  packages/nodejs-ble/README.md
Labels: review - approved

#1360 Fix import in compat package
  CHANGELOG.md
  compat/matter-node.js/package.json
  compat/matter-node.js/src/tsconfig.json
  compat/matter-node.js/src/util/CommandLine.ts
Labels: review - approved

#1362 Update controller example to use events
  packages/examples/src/controller/ControllerNode.ts
Labels: review - approved

#1368 [NIGHTLY DEV RELEASE] 0.11.3-alpha.0-20241106-39bacbc00
  version.txt
Labels: automated pr

#1366 No BLE scan stop when never started
  CHANGELOG.md
  packages/nodejs-ble/src/NobleBleClient.ts
Labels: review - approved

#1367 Make attributes/events optional in params
  packages/protocol/src/interaction/InteractionClient.ts
Labels: review - pending

#1370 Temporarily Adjust MoveToLevel
  CHANGELOG.md
  models/src/local/LevelControlOverrides.ts
  packages/model/src/standard/elements/LevelControl.ts
  packages/node/src/behaviors/level-control/LevelControlServer.ts
  packages/types/src/clusters/level-control.ts
Labels: review - approved

#1372 [OFFICIAL RELEASE] 0.11.4
  CHANGELOG.md
  version.txt
Labels: automated pr

#1374 0.10.7 into changelog
  CHANGELOG.md
Labels: review - pending

#1375 Fine-grained node.js boostrap configuration
  CHANGELOG.md
  packages/nodejs/package.json
  packages/nodejs/src/config.ts
  packages/nodejs/src/environment/NodeJsEnvironment.ts
Labels: review - approved

#1376 [NIGHTLY DEV RELEASE] 0.11.5-alpha.0-20241108-c38ea9922
  version.txt
Labels: automated pr

#1377 Documentation: adding network troubleshooting steps for mDNS connectivity
  docs/TROUBLESHOOTING.md
Labels: review - approved

#1379 More descriptive "with" functions
  packages/node/src/behavior/cluster/ClusterBehavior.ts
  packages/node/src/endpoint/type/MutableEndpoint.ts
Labels: review - approved

#1380 [NIGHTLY DEV RELEASE] 0.11.5-alpha.0-20241109-2e3dccaa9
  version.txt
Labels: automated pr

#1386 Fix commissioning on server restart
  CHANGELOG.md
  packages/node/src/behavior/system/commissioning/CommissioningServer.ts
  packages/node/src/behavior/system/network/ServerNetworkRuntime.ts
Labels: review - approved

#1388 [NIGHTLY DEV RELEASE] 0.11.5-alpha.0-20241112-858f60251
  version.txt
Labels: automated pr

#1387 Fix typo in README.md
  README.md
Labels: review - approved

#1389 Reverts MoveToLevel workaround from 0.11.4
  CHANGELOG.md
  models/src/local/LevelControlOverrides.ts
  packages/model/src/standard/elements/LevelControl.ts
  packages/node/src/behaviors/level-control/LevelControlServer.ts
  packages/types/src/clusters/level-control.ts
Labels: review - approved

#1391 [NIGHTLY DEV RELEASE] 0.11.5-alpha.0-20241113-eb222f7fe
  version.txt
Labels: automated pr

#1395 [NIGHTLY DEV RELEASE] 0.11.5-alpha.0-20241114-6af665cdd
  version.txt
Labels: automated pr

#1396 Fix generated import path on Windows
  codegen/src/util/TsFile.ts
Labels: review - approved

#1398 Replace fragile regexp for build config output
  packages/tools/src/building/project.ts
Labels: review - approved

#1400 Fix bitrot in model docs
  packages/model/README.md
Labels: review - approved

#1401 A couple of quick tweaks
  .vscode/launch.json
  codegen/src/generate-vscode.ts
  packages/model/src/models/Model.ts
Labels: review - approved

#1399 Ignore persisted values when features change
  CHANGELOG.md
  packages/model/src/logic/ModelTraversal.ts
  packages/node/src/behavior/state/managed/Datasource.ts
  packages/node/test/node/ServerNodeTest.ts
Labels: review - approved

#1402 [NIGHTLY DEV RELEASE] 0.11.5-alpha.0-20241116-c923f6d75
  version.txt
Labels: automated pr

#1403 Collection of minor adjustments and refactorings
  packages/matter.js/src/device/PairedNode.ts
  packages/nodejs-shell/README.md
  packages/protocol/src/interaction/InteractionEndpointStructure.ts
  packages/protocol/src/interaction/ServerSubscription.ts
  packages/protocol/src/protocol/ExchangeManager.ts
Labels: review - approved

#1404 [NIGHTLY DEV RELEASE] 0.11.5-alpha.0-20241117-8798960f0
  version.txt
Labels: automated pr

#1405 Check before getting fabric
  packages/protocol/src/common/FailsafeContext.ts
  packages/protocol/src/fabric/FabricManager.ts
Labels: review - approved

#1406 [NIGHTLY DEV RELEASE] 0.11.5-alpha.0-20241118-a637d8bb8
  version.txt
Labels: automated pr

#1411 [NIGHTLY DEV RELEASE] 0.11.5-alpha.0-20241119-d0be98137
  version.txt
Labels: automated pr

#1412 Fix collection
  docs/TROUBLESHOOTING.md
  packages/node/src/behaviors/color-control/ColorConversionUtils.ts
  packages/node/src/behaviors/general-diagnostics/GeneralDiagnosticsServer.ts
  packages/nodejs/src/storage/StorageBackendDiskAsync.ts
  packages/nodejs/test/storage/StorageBackendDiskAsyncTest.ts
  packages/nodejs/test/storage/StorageBackendDiskTest.ts
Labels: review - approved

#1413 [NIGHTLY DEV RELEASE] 0.11.5-alpha.0-20241121-c31bc6998
  version.txt
Labels: automated pr

#1414 Pre-allocate numbers when stores are loaded
  CHANGELOG.md
  packages/node/src/endpoint/storage/EndpointStore.ts
  packages/node/src/node/storage/EndpointStoreService.ts
Labels: review - approved

#1415 Update matterbridge plugins with shelly plugin
  README.md
Labels: review - approved

#1416 Mark "next number" for future persistence on reset
  packages/node/src/node/storage/EndpointStoreService.ts
Labels: review - approved

#1417 Thermostat cluster override
  CHANGELOG.md
  models/src/local/ThermostatOverrides.ts
  packages/model/src/common/FieldValue.ts
  packages/model/src/standard/elements/Thermostat.ts
  packages/types/src/clusters/thermostat.ts
Labels: review - approved

#1421 [NIGHTLY DEV RELEASE] 0.11.5-alpha.0-20241122-e3f909a1c
  version.txt
Labels: automated pr

#1422 Cut network name to 32 in legacy Server
  packages/matter.js/src/cluster/server/GeneralDiagnosticsServer.ts
Labels: review - pending

#1424 [NIGHTLY DEV RELEASE] 0.11.5-alpha.0-20241123-e56e38864
  version.txt
Labels: automated pr

#1426 Dataversionfilter shortening fix
  CHANGELOG.md
  packages/nodejs/test/interaction/InteractionClientMessengerTest.ts
  packages/nodejs/test/interaction/InteractionTestUtils.ts
  packages/protocol/src/interaction/InteractionMessenger.ts
Labels: review - approved

#1428 [NIGHTLY DEV RELEASE] 0.11.5-alpha.0-20241124-6e969cda5
  version.txt
Labels: automated pr

#1427 Fix endpoint allocation
  packages/node/src/node/storage/EndpointStoreService.ts
  packages/node/test/endpoint/mock-endpoint.ts
  packages/node/test/endpoints/BridgedNodeEndpointTest.ts
  packages/node/test/node/mock-server-node.ts
Labels: review - approved

#1429 [NIGHTLY DEV RELEASE] 0.11.5-alpha.0-20241124-c836aa892
  version.txt
Labels: automated pr

#1425 Update `DummyWifiNetworkCommissioningServer.ts` reference
  README.md
Labels: review - approved

#1430 Further dynamic endpoint adjustments
  packages/node/src/endpoint/Endpoint.ts
  packages/node/src/endpoint/properties/EndpointInitializer.ts
  packages/node/src/node/client/ClientEndpointInitializer.ts
  packages/node/src/node/server/ServerEndpointInitializer.ts
  packages/node/src/node/storage/EndpointStoreService.ts
  packages/node/test/endpoints/BridgedNodeEndpointTest.ts
  packages/node/test/node/mock-node.ts
Labels: review - approved

#1431 [NIGHTLY DEV RELEASE] 0.11.5-alpha.0-20241124-7fd6096ba
  version.txt
Labels: automated pr

#1437 [OFFICIAL RELEASE] 0.11.5
  CHANGELOG.md
  version.txt
Labels: automated pr

#1442 [NIGHTLY DEV RELEASE] 0.11.6-alpha.0-20241126-d77503abd
  version.txt
Labels: automated pr

#1443 Typo fix and rounding
  CHANGELOG.md
  packages/node/src/behaviors/color-control/ColorConversionUtils.ts
  packages/nodejs/src/net/register.ts
Labels: review - approved

#1445 Optimize Handling of compression-loops in DNS-SD QName parsing
  CHANGELOG.md
  packages/general/src/codec/DerCodec.ts
  packages/general/src/codec/DnsCodec.ts
  packages/general/src/util/DataReader.ts
  packages/general/test/codec/DnsCodecTest.ts
  packages/protocol/src/ble/BtpSessionHandler.ts
  packages/protocol/src/codec/BtpCodec.ts
  packages/protocol/src/codec/MessageCodec.ts
  packages/protocol/src/securechannel/SecureChannelStatusMessageSchema.ts
Labels: review - approved

#1447 Adds missing subscription update when endpoint structure changes
  CHANGELOG.md
  packages/protocol/src/interaction/ServerSubscription.ts
Labels: review - approved

#1449 Do not use revisions of 0 for Unknown fallbacks
  CHANGELOG.md
  packages/matter.js/src/device/DeviceTypes.ts
  packages/matter.js/src/device/PairedNode.ts
Labels: review - approved

#1453 Prevent committing delayed ACL updates too early
  CHANGELOG.md
  packages/node/src/behaviors/access-control/AccessControlServer.ts
  packages/node/src/node/server/TransactionalInteractionServer.ts
Labels: review - approved

#1454 [OFFICIAL RELEASE] 0.11.7
  CHANGELOG.md
  version.txt
Labels: automated pr

#1458 Correctly parse DataReports with duplicate non-Array data entries
  CHANGELOG.md
  packages/protocol/src/interaction/AttributeDataDecoder.ts
  packages/protocol/src/interaction/InteractionServer.ts
  packages/protocol/test/protocol/interaction/AttributeDataDecoderTest.ts
Labels: review - approved

#1457 Fix LevelControl extensionpoint defs
  CHANGELOG.md
  chip-testing/src/cluster/TestLevelControlServer.ts
  packages/node/src/behaviors/level-control/LevelControlServer.ts
Labels: review - approved

#1459 [OFFICIAL RELEASE] 0.11.8
  CHANGELOG.md
  version.txt
Labels: automated pr
