Repository matter-js/matter.js, pull requests merged in 2024-09, with the labels that each got.

#1153 [NIGHTLY DEV RELEASE] 0.10.1-alpha.0-20240903-7cffa11d
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#1146 Update and Streamline READMEs
  README.md
  packages/matter-node-ble.js/README.md
  packages/matter-node-shell.js/README.md
  packages/matter-node.js-examples/README.md
  packages/matter-node.js/README.md
  packages/matter.js-react-native/README.md
  packages/matter.js-tools/README.md
  packages/matter.js/README.md
Labels: review - approved

#1157 [NIGHTLY DEV RELEASE] 0.10.1-alpha.0-20240904-3e59b2c4
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#1159 Add AllClustersApp as LockApp for Python Tests
  .github/workflows/chip-tool-tests.yml
Labels: review - pending

#1160 Enhance readme for certification relevance
  README.md
Labels: review - approved

#1163 ColorControl logic optimizations
  packages/matter.js/src/behavior/definitions/color-control/ColorControlServer.ts
Labels: review - approved

#1164 [NIGHTLY DEV RELEASE] 0.10.1-alpha.0-20240905-4da41044
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#1165 Messagetiming
  CHANGELOG.md
  packages/matter-node.js/test/session/SessionManagerTest.ts
  packages/matter.js/src/MatterController.ts
  packages/matter.js/src/MatterDevice.ts
  packages/matter.js/src/protocol/ExchangeManager.ts
  packages/matter.js/src/protocol/MessageExchange.ts
  packages/matter.js/src/protocol/ProtocolHandler.ts
  packages/matter.js/src/protocol/interaction/InteractionMessenger.ts
  packages/matter.js/src/protocol/securechannel/SecureChannelMessenger.ts
  packages/matter.js/src/session/InsecureSession.ts
  packages/matter.js/src/session/SecureSession.ts
  packages/matter.js/src/session/Session.ts
  packages/matter.js/src/session/SessionManager.ts
  packages/matter.js/src/session/pase/PaseMessenger.ts
Labels: review - approved

#1166 [NIGHTLY DEV RELEASE] 0.10.1-alpha.0-20240906-86b97420
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#1168 Exchange optimizations
  packages/matter.js/src/protocol/ExchangeManager.ts
  packages/matter.js/src/protocol/interaction/InteractionMessenger.ts
Labels: review - approved

#1169 [NIGHTLY DEV RELEASE] 0.10.1-alpha.0-20240908-13ba5e28
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#1170 [OFFICIAL RELEASE] 0.10.1
  CHANGELOG.md
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#1171 Initialize 0.11.0 version for nightlies
  lerna.json
Labels: review - pending

#1172 Versioning support
  chip-testing/package.json
  codegen/package.json
  models/package.json
  package-lock.json
  package.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/bin/prepare-chip.js
  packages/matter.js-tools/bin/version.js
  packages/matter.js-tools/package.json
  packages/matter.js-tools/src/util/package.ts
  packages/matter.js-tools/src/util/progress.ts
  packages/matter.js-tools/src/versioning/cli.ts
  packages/matter.js-tools/src/versioning/versioner.ts
  packages/matter.js/package.json
  version.txt
Labels: review - approved

#1182 [NIGHTLY DEV RELEASE] 0.11.0-alpha.0-20240909-b3b29745
  version.txt
Labels: automated pr

#1184 Fix versioning
  package.json
  packages/matter.js/src/cluster/Cluster.ts
  packages/matter.js/src/cluster/server/ClusterServerTypes.ts
Labels: review - approved

#1186 [NIGHTLY DEV RELEASE] 0.11.0-alpha.0-20240911-db8f7c80
  version.txt
Labels: automated pr

#1193 [OFFICIAL RELEASE] 0.10.2
  CHANGELOG.md
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#1195 Fix typo in mergify config
  .mergify.yml
Labels: review - pending

#1196 [OFFICIAL RELEASE] 0.10.3
  CHANGELOG.md
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#1200 Fix PowerTopology implementation and Device type adding logic
  packages/node/src/behaviors/descriptor/DescriptorServer.ts
  packages/node/src/behaviors/power-topology/PowerTopologyServer.ts
Labels: review - approved

#1192 Limits the parallel open exchanges to 5
  CHANGELOG.md
  packages/protocol/src/protocol/ExchangeManager.ts
  packages/protocol/src/protocol/MessageExchange.ts
Labels: review - approved

#1197 Allow to read attributes remotely in shell
  CHANGELOG.md
  packages/nodejs-shell/README.md
  packages/nodejs-shell/src/shell/cmd_cluster-attributes.ts
  packages/nodejs-shell/src/shell/cmd_nodes.ts
Labels: review - approved

#1190 Controller reconnect optimizations
  CHANGELOG.md
  packages/matter.js/src/CommissioningController.ts
  packages/matter.js/src/MatterController.ts
  packages/matter.js/src/device/PairedNode.ts
  packages/nodejs/src/net/NodeJsUdpChannel.ts
  packages/nodejs/test/IntegrationTest.ts
  packages/protocol/src/common/Scanner.ts
  packages/protocol/src/interaction/InteractionMessenger.ts
  packages/protocol/src/interaction/SubscriptionHandler.ts
  packages/protocol/src/mdns/MdnsScanner.ts
  packages/protocol/src/protocol/ChannelManager.ts
  packages/protocol/src/protocol/ControllerDiscovery.ts
  packages/protocol/src/protocol/MessageExchange.ts
  packages/protocol/src/securechannel/SecureChannelMessenger.ts
  packages/protocol/src/session/case/CaseClient.ts
Labels: review - approved

#1213 [NIGHTLY DEV RELEASE] 0.11.0-alpha.0-20240919-8dcf8977
  version.txt
Labels: automated pr

#1215 [NIGHTLY DEV RELEASE] 0.11.0-alpha.0-20240919-89f6a6e7
  version.txt
Labels: automated pr

#1217 Add Tlv decoding tools to the Shell app
  CHANGELOG.md
  packages/nodejs-shell/README.md
  packages/nodejs-shell/package.json
  packages/nodejs-shell/src/shell/Shell.ts
  packages/nodejs-shell/src/shell/cmd_tlv.ts
  packages/types/src/tlv/TlvAny.ts
  packages/types/test/tlv/TlvAnyTest.ts
Labels: review - approved

#1216 Enhance subscription time calculation
  CHANGELOG.md
  package.json
  packages/nodejs/test/interaction/InteractionProtocolTest.ts
  packages/protocol/src/interaction/InteractionClient.ts
  packages/protocol/src/interaction/InteractionMessenger.ts
  packages/protocol/src/protocol/MessageExchange.ts
  packages/protocol/src/session/SessionManager.ts
Labels: review - approved

#1220 Enhances some ACL related logging
  packages/protocol/src/interaction/AccessControlManager.ts
  packages/protocol/src/session/case/CaseServer.ts
Labels: review - approved

#1222 [OFFICIAL RELEASE] 0.10.5
  CHANGELOG.md
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#1219 Store 1000 history lines for shell app
  CHANGELOG.md
  package-lock.json
  packages/nodejs-shell/package.json
  packages/nodejs-shell/src/app.ts
  packages/nodejs-shell/src/shell/Shell.ts
Labels: review - approved

#1223 Bypasses ACL checks when updating fabric scoped attributes in a sub
  packages/matter.js/src/device/LegacyInteractionServer.ts
  packages/node/src/node/server/TransactionalInteractionServer.ts
  packages/protocol/src/interaction/InteractionServer.ts
  packages/protocol/src/interaction/SubscriptionHandler.ts
  packages/protocol/src/session/SecureSession.ts
Labels: review - approved

#1226 [OFFICIAL RELEASE] 0.10.6
  CHANGELOG.md
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#1225 Maintain tsconfig references automatically
  chip-testing/src/tsconfig.json
  chip-testing/test/tsconfig.json
  codegen/src/tsconfig.json
  compat/matter-node-ble.js/src/tsconfig.json
  compat/matter-node.js-examples/src/tsconfig.json
  compat/matter-node.js/src/log/export.ts
  compat/matter-node.js/src/tsconfig.json
  models/src/tsconfig.json
  package.json
  packages/examples/src/tsconfig.json
  packages/general/test/tsconfig.json
  packages/main/src/tsconfig.json
  packages/matter.js/src/tsconfig.json
  packages/matter.js/test/tsconfig.json
  packages/model/src/tsconfig.json
  packages/model/test/tsconfig.json
  packages/node/src/tsconfig.json
  packages/node/test/tsconfig.json
  packages/nodejs-ble/src/tsconfig.json
  packages/nodejs-shell/src/shell/cmd_tlv.ts
  packages/nodejs-shell/src/tsconfig.json
  packages/nodejs/src/tsconfig.json
  packages/nodejs/test/tsconfig.json
  packages/protocol/src/tsconfig.json
  packages/protocol/test/tsconfig.json
  packages/react-native/src/tsconfig.json
  packages/tools/src/building/cli.ts
  packages/tools/src/building/tsconfig.ts
  packages/tools/test/tsconfig.json
  packages/types/src/tsconfig.json
  packages/types/test/tsconfig.json
Labels: review - approved

#1229 Typescript and Package updates
  codegen/package.json
  compat/matter-node-ble.js/package.json
  compat/matter-node.js-examples/README.md
  compat/matter-node.js-examples/package.json
  compat/matter-node.js/package.json
  examples/web/README.md
  examples/web/index.html
  package-lock.json
  package.json
  packages/examples/README.md
  packages/examples/package.json
  packages/general/package.json
  packages/general/src/MatterError.ts
  packages/general/test/MatterErrorTest.ts
  packages/main/package.json
  packages/matter.js/package.json
  packages/model/package.json
  packages/model/src/parser/Lexer.ts
  packages/node/package.json
  packages/node/src/behavior/state/managed/values/ListManager.ts
  packages/node/src/behavior/system/network/NetworkBehavior.ts
  packages/node/src/behaviors/basic-information/BasicInformationServer.ts
  packages/node/src/node/Node.ts
  packages/nodejs-ble/package.json
  packages/nodejs-shell/package.json
  packages/nodejs/package.json
  packages/protocol/package.json
  packages/react-native/package.json
  packages/tools/package.json
  packages/types/package.json
Labels: review - approved

#1233 [NIGHTLY DEV RELEASE] 0.11.0-alpha.0-20240923-9eed78d0c
  version.txt
Labels: automated pr

#1234 Do not limit exchanges for PASE/CASE session id 0
  packages/protocol/src/protocol/ExchangeManager.ts
Labels: review - approved

#1235 [NIGHTLY DEV RELEASE] 0.11.0-alpha.0-20240923-508e6b1e1
  version.txt
Labels: automated pr

#1237 Remove existing Subs earlier when keepSubscriptions=== false
  .github/workflows/chip-tool-tests.yml
  CHANGELOG.md
  packages/protocol/src/interaction/InteractionServer.ts
Labels: review - approved

#1240 [NIGHTLY DEV RELEASE] 0.11.0-alpha.0-20240926-407400ecb
  version.txt
Labels: automated pr

#1243 Rename Queue to DataReadQueue
  packages/general/src/util/DataReadQueue.ts
  packages/general/src/util/index.ts
  packages/matter.js/src/compat/util.ts
  packages/nodejs/test/interaction/InteractionTestUtils.ts
  packages/protocol/src/protocol/MessageExchange.ts
Labels: review - approved

#1244 Allow Nightly with version increase
  .github/workflows/nightly-dev-release.yml
Labels: review - approved

#1245 [NIGHTLY DEV RELEASE] 0.11.0-alpha.0-20240928-08865c2ce
  version.txt
Labels: automated pr
