Repository matter-js/matter.js, pull requests merged in 2024-07, with the labels that each got.

#982 PASE Commissioner
  CHANGELOG.md
  packages/matter-node-shell.js/src/shell/cmd_commission.ts
  packages/matter-node.js/test/IntegrationTest.ts
  packages/matter.js/src/CommissioningController.ts
  packages/matter.js/src/MatterController.ts
  packages/matter.js/src/PaseCommissioner.ts
  packages/matter.js/src/certificate/RootCertificateManager.ts
  packages/matter.js/src/export.ts
  packages/matter.js/src/protocol/ControllerCommissioner.ts
Labels: review - approved

#989 [NIGHTLY DEV RELEASE] 0.10.0-alpha.0-20240702-367a66c2
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#990 Fix MaybeAsyncStorage using in new API
  packages/matter-node.js/src/storage/StorageBackendDisk.ts
  packages/matter.js/src/node/server/storage/ServerPartStore.ts
Labels: review - approved

#991 [NIGHTLY DEV RELEASE] 0.10.0-alpha.0-20240706-499c48e8
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#994 Fix Controller with AsyncStorage
  packages/matter.js/src/MatterController.ts
Labels: review - approved

#995 [NIGHTLY DEV RELEASE] 0.10.0-alpha.0-20240707-ccb2eb3c
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#1002 Add optional diagnostic name for offline tx
  packages/matter.js/src/behavior/definitions/general-commissioning/ServerNodeFailsafeContext.ts
  packages/matter.js/src/behavior/definitions/general-diagnostics/GeneralDiagnosticsServer.ts
  packages/matter.js/src/behavior/definitions/operational-credentials/OperationalCredentialsServer.ts
  packages/matter.js/src/behavior/state/managed/values/StructManager.ts
  packages/matter.js/src/behavior/system/network/NetworkRuntime.ts
  packages/matter.js/src/behavior/system/network/ServerNetworkRuntime.ts
  packages/matter.js/src/endpoint/Endpoint.ts
  packages/matter.js/src/endpoint/properties/Behaviors.ts
  packages/matter.js/src/node/ServerNode.ts
  packages/matter.js/src/util/Error.ts
  packages/matter.js/src/util/Mutex.ts
Labels: review - approved

#1003 [NIGHTLY DEV RELEASE] 0.10.0-alpha.0-20240709-9d45732c
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#988 Adjust React-Native NetworkInterface handling
  CHANGELOG.md
  package-lock.json
  packages/matter.js-react-native/README.md
  packages/matter.js-react-native/package.json
  packages/matter.js-react-native/src/net/NetworkReactNative.ts
  packages/matter.js-react-native/src/net/UdpChannelReactNative.ts
  packages/matter.js/src/CommissioningServer.ts
  packages/matter.js/src/behavior/definitions/general-diagnostics/GeneralDiagnosticsServer.ts
  packages/matter.js/src/behavior/system/network/ServerNetworkRuntime.ts
  packages/matter.js/src/cluster/server/GeneralDiagnosticsServer.ts
  packages/matter.js/src/crypto/Key.ts
  packages/matter.js/src/mdns/MdnsBroadcaster.ts
  packages/matter.js/src/mdns/MdnsServer.ts
  packages/matter.js/src/net/Network.ts
  packages/matter.js/src/net/UdpMulticastServer.ts
  packages/matter.js/src/util/Cache.ts
  packages/matter.js/test/mdns/MdnsServerTest.ts
  packages/matter.js/test/mdns/MdnsTest.ts
Labels: review - approved

#1006 Bump react-native-quick-crypto and typescript
  codegen/package.json
  package-lock.json
  package.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-react-native/src/net/UdpChannelReactNative.ts
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: review - approved

#1007 [NIGHTLY DEV RELEASE] 0.10.0-alpha.0-20240710-9f38895c
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#1010 React native Timer do not have ref/unref
  packages/matter.js-react-native/src/time/TimeReactNative.ts
Labels: review - approved

#1012 [NIGHTLY DEV RELEASE] 0.10.0-alpha.0-20240711-7e908482
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#1011 Fix Subscription clearing
  packages/matter.js/src/MatterDevice.ts
  packages/matter.js/src/protocol/interaction/InteractionServer.ts
  packages/matter.js/src/session/SessionManager.ts
Labels: review - approved

#1020 [NIGHTLY DEV RELEASE] 0.10.0-alpha.0-20240715-a2d7875c
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#1023 [NIGHTLY DEV RELEASE] 0.10.0-alpha.0-20240716-446c872f
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#1009 Add new Python test for OPCREDS_3_1 to CI
  .github/workflows/chip-tool-tests.yml
  packages/matter-node.js/src/crypto/CryptoNode.ts
  packages/matter-node.js/test/interaction/InteractionProtocolTest.ts
  packages/matter.js/src/CommissioningServer.ts
  packages/matter.js/src/MatterDevice.ts
  packages/matter.js/src/behavior/AccessControl.ts
  packages/matter.js/src/behavior/definitions/general-commissioning/ServerNodeFailsafeContext.ts
  packages/matter.js/src/behavior/definitions/operational-credentials/OperationalCredentialsServer.ts
  packages/matter.js/src/certificate/CertificateManager.ts
  packages/matter.js/src/certificate/CertificationDeclarationManager.ts
  packages/matter.js/src/cluster/server/AccessControlServer.ts
  packages/matter.js/src/cluster/server/AttributeServer.ts
  packages/matter.js/src/cluster/server/ClusterServer.ts
  packages/matter.js/src/cluster/server/ClusterServerTypes.ts
  packages/matter.js/src/cluster/server/EventServer.ts
  packages/matter.js/src/cluster/server/OperationalCredentialsServer.ts
  packages/matter.js/src/common/FailsafeContext.ts
  packages/matter.js/src/crypto/Crypto.ts
  packages/matter.js/src/device/LegacyInteractionServer.ts
  packages/matter.js/src/fabric/Fabric.ts
  packages/matter.js/src/fabric/FabricManager.ts
  packages/matter.js/src/model/models/EventModel.ts
  packages/matter.js/src/model/models/FieldModel.ts
  packages/matter.js/src/node/server/TransactionalInteractionServer.ts
  packages/matter.js/src/protocol/interaction/AttributeDataEncoder.ts
  packages/matter.js/src/protocol/interaction/EventHandler.ts
  packages/matter.js/src/protocol/interaction/InteractionClient.ts
  packages/matter.js/src/protocol/interaction/InteractionEndpointStructure.ts
  packages/matter.js/src/protocol/interaction/InteractionMessenger.ts
  packages/matter.js/src/protocol/interaction/InteractionServer.ts
  packages/matter.js/src/protocol/interaction/SubscriptionHandler.ts
  packages/matter.js/src/tlv/TlvArray.ts
  packages/matter.js/src/tlv/TlvNullable.ts
  packages/matter.js/src/tlv/TlvObject.ts
  packages/matter.js/src/tlv/TlvSchema.ts
  packages/matter.js/src/tlv/TlvWrapper.ts
  packages/matter.js/test/behavior/internal/ClusterServerBackingTest.ts
  packages/matter.js/test/node/ServerNodeTest.ts
  packages/matter.js/test/protocol/interaction/AttributeDataEncoderTest.ts
  packages/matter.js/test/tlv/TlvObjectTest.ts
Labels: review - approved

#1031 Better handle Async subscription updates
  CHANGELOG.md
  packages/matter.js/src/protocol/interaction/SubscriptionHandler.ts
Labels: review - approved

#1030 Fixes for two Controller issues
  CHANGELOG.md
  packages/matter.js/src/MatterController.ts
  packages/matter.js/src/device/PairedNode.ts
  packages/matter.js/src/protocol/ChannelManager.ts
  packages/matter.js/src/protocol/ExchangeManager.ts
Labels: review - approved

#1034 Add changelog of 0.9.4
  CHANGELOG.md
Labels: review - pending

#1028 Add Metro configuration instructions for React Native
  packages/matter.js-react-native/README.md
Labels: review - approved

#1035 Dependency updates
  package-lock.json
  package.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/src/shell/cmd_nodes.ts
  packages/matter-node.js-examples/src/examples/ControllerNode.ts
  packages/matter.js-react-native/package.json
  packages/matter.js-react-native/src/net/UdpChannelReactNative.ts
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
  packages/matter.js/src/CommissioningServer.ts
  packages/matter.js/src/cluster/server/EventServer.ts
  packages/matter.js/src/net/fake/UdpChannelFake.ts
  packages/matter.js/src/session/SecureSession.ts
Labels: review - approved

#1036 Restore some ColoControl tests to pre 1.4
  chip-testing/PATCHED_TESTS_INFO.md
  chip-testing/patched-test-files/certification/Test_TC_CC_3_2.yaml
  chip-testing/patched-test-files/certification/Test_TC_CC_3_3.yaml
  chip-testing/patched-test-files/certification/Test_TC_CC_4_2.yaml
  chip-testing/patched-test-files/certification/Test_TC_CC_4_3.yaml
  chip-testing/patched-test-files/certification/Test_TC_CC_5_2.yaml
  chip-testing/patched-test-files/certification/Test_TC_CC_5_3.yaml
  chip-testing/patched-test-files/certification/Test_TC_CC_6_2.yaml
  chip-testing/patched-test-files/certification/Test_TC_CC_6_3.yaml
  chip-testing/patched-test-files/certification/Test_TC_CC_7_2.yaml
  chip-testing/patched-test-files/certification/Test_TC_CC_7_3.yaml
Labels: review - pending

#1037 Restore Level Control 4.1 tests to pre 1.4
  chip-testing/PATCHED_TESTS_INFO.md
  chip-testing/patched-test-files/certification/Test_TC_LVL_4_1.yaml
Labels: review - pending

#1038 [NIGHTLY DEV RELEASE] 0.10.0-alpha.0-20240720-471dea8c
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#1045 [NIGHTLY DEV RELEASE] 0.10.0-alpha.0-20240722-39f917c1
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#1046 Fix: Ensure all controllerStorage.get calls are properly awaited
  packages/matter-node.js-examples/src/examples/ControllerNode.ts
Labels: review - approved

#1049 Ignore missing ClusterServer elements for Controller
  packages/matter.js/src/cluster/server/ClusterServer.ts
  packages/matter.js/src/device/PairedNode.ts
Labels: review - approved

#1050 [NIGHTLY DEV RELEASE] 0.10.0-alpha.0-20240724-23170eb4
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#1052 Exclude some tests
  .github/workflows/chip-tool-tests.yml
  .github/workflows/nightly-dev-release.yml
  .github/workflows/official-release.yml
  chip-testing/PATCHED_TESTS_INFO.md
Labels: review - approved

#1062 Try real hard to surface error details
  .github/workflows/build-test.js.yml
  .github/workflows/release-npm.yml
  packages/matter-node.js/src/environment/NodeJsEnvironment.ts
  packages/matter-node.js/src/environment/ProcessManager.ts
  packages/matter.js/src/MatterDevice.ts
  packages/matter.js/src/common/MatterError.ts
  packages/matter.js/src/log/Diagnostic.ts
  packages/matter.js/src/log/Format.ts
  packages/matter.js/src/log/Logger.ts
  packages/matter.js/test/common/MatterErrorTest.ts
  packages/matter.js/test/log/LoggerTest.ts
Labels: review - approved

#1063 Activate tests for Node.js 22
  .github/workflows/build-test.js.yml
  .github/workflows/release-npm.yml
Labels: review - approved

#1064 [NIGHTLY DEV RELEASE] 0.10.0-alpha.0-20240730-cd430956
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#1066 Revert test yaml files to matter 1.3
  chip-testing/PATCHED_TESTS_INFO.md
  chip-testing/patched-test-files/certification/Test_TC_SWTCH_1_1.yaml
Labels: review - pending

#1060 Update React native logic
  package-lock.json
  package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-react-native/src/crypto/CryptoReactNative.ts
  packages/matter.js-react-native/src/environment/register.ts
  packages/matter.js-react-native/src/net/NetworkReactNative.ts
  packages/matter.js-react-native/src/time/TimeReactNative.ts
  packages/matter.js/src/behavior/state/transaction/Tx.ts
  packages/matter.js/src/cluster/server/ClusterServer.ts
  packages/matter.js/src/util/Construction.ts
  packages/matter.js/test/behavior/cluster/ClusterBehaviorTest.ts
  packages/matter.js/test/behavior/cluster/ClusterEventsTest.ts
Labels: review - approved
