Repository matter-js/matter.js, pull requests merged in 2024-05, with the labels that each got.

#859 [NIGHTLY DEV RELEASE] 0.8.2-alpha.0-20240501-e6e1fe7e
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#860 Switch cluster
  CHANGELOG.md
  README.md
  chip-testing/src/AllClustersTestInstance.ts
  packages/matter.js/README.md
  packages/matter.js/src/behavior/definitions/switch/SwitchServer.ts
  packages/matter.js/src/endpoint/Endpoint.ts
  packages/matter.js/test/behavior/definitions/switch/SwitchServerTest.ts
  packages/matter.js/test/endpoint/mock-endpoint.ts
Labels: review - approved

#862 [NIGHTLY DEV RELEASE] 0.8.2-alpha.0-20240503-22b8f7e5
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#869 [NIGHTLY DEV RELEASE] 0.8.2-alpha.0-20240508-ae043b81
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#867 Fix conformance expression handling
  CHANGELOG.md
  packages/matter.js/src/behavior/internal/Reactors.ts
  packages/matter.js/src/behavior/state/validation/conformance-compiler.ts
  packages/matter.js/src/behavior/state/validation/conformance-util.ts
  packages/matter.js/test/behavior/state/validation/conformanceTest.ts
  packages/matter.js/test/endpoint/mock-endpoint.ts
  packages/matter.js/test/environment/VariableServiceTest.ts
Labels: review - approved

#871 [NIGHTLY DEV RELEASE] 0.8.2-alpha.0-20240509-f36dbf54
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#872 Update readme.MD
  README.md
Labels: review - approved

#870 Colorcontrol Default Implementation
  .github/workflows/chip-tool-tests.yml
  .github/workflows/nightly-dev-release.yml
  .github/workflows/official-release.yml
  CHANGELOG.md
  chip-testing/patched-test-files/certification/Test_TC_CC_1_1.yaml
  chip-testing/patched-test-files/certification/ci-pics-values
  chip-testing/src/AllClustersTestInstance.ts
  models/src/local/ColorControlOverrides.ts
  packages/matter-node.js-examples/src/examples/IlluminatedRollerShade.ts
  packages/matter.js/src/behavior/definitions/color-control/ColorControlServer.ts
  packages/matter.js/src/behavior/definitions/color-control/ColorConversionUtils.ts
  packages/matter.js/src/behavior/definitions/color-control/kelvinToXy.ts
  packages/matter.js/src/behavior/definitions/level-control/LevelControlServer.ts
  packages/matter.js/src/cluster/definitions/ColorControlCluster.ts
  packages/matter.js/src/model/standard/elements/ColorControl.ts
  packages/matter.js/src/util/Number.ts
  packages/matter.js/test/behavior/definitions/color-control/ColorConversionUtilsTest.ts
Labels: review - approved

#874 Adjust GHA SlowApp tests
  .github/workflows/chip-tool-tests.yml
Labels: review - approved

#879 [NIGHTLY DEV RELEASE] 0.8.2-alpha.0-20240511-497cd590
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#876 Log params with objects correctly for invokes
  packages/matter.js/src/log/Format.ts
Labels: review - approved

#887 [NIGHTLY DEV RELEASE] 0.8.2-alpha.0-20240513-927b1bb5
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#881 Example fixes and docs
  docs/MIGRATION_GUIDE_08.md
  packages/matter-node.js-examples/src/examples/IlluminatedRollerShade.ts
  packages/matter-node.js-examples/src/examples/cluster/MyFancyOwnFunctionality.ts
Labels: review - approved

#877 Enhance General Diagnostics Cluster
  CHANGELOG.md
  packages/matter-node.js/src/net/NetworkNode.ts
  packages/matter.js/src/CommissioningServer.ts
  packages/matter.js/src/behavior/cluster/ClusterBehavior.ts
  packages/matter.js/src/behavior/definitions/general-diagnostics/GeneralDiagnosticsServer.ts
  packages/matter.js/src/behavior/definitions/operational-credentials/OperationalCredentialsServer.ts
  packages/matter.js/src/behavior/system/network/ServerNetworkRuntime.ts
  packages/matter.js/src/cluster/server/GeneralDiagnosticsServer.ts
  packages/matter.js/src/device/Device.ts
  packages/matter.js/src/environment/Environment.ts
  packages/matter.js/src/environment/MdnsService.ts
  packages/matter.js/src/environment/VariableService.ts
  packages/matter.js/src/mdns/MdnsBroadcaster.ts
  packages/matter.js/src/mdns/MdnsServer.ts
  packages/matter.js/src/net/Network.ts
  packages/matter.js/src/net/UdpMulticastServer.ts
  packages/matter.js/src/net/fake/NetworkFake.ts
  packages/matter.js/src/net/fake/UdpChannelFake.ts
  packages/matter.js/src/util/Ip.ts
  packages/matter.js/test/behavior/cluster/ClusterBehaviorTest.ts
  packages/matter.js/test/environment/VariableServiceTest.ts
  packages/matter.js/test/mdns/MdnsTest.ts
  packages/matter.js/test/util/IpTest.ts
Labels: review - approved

#888 [NIGHTLY DEV RELEASE] 0.8.2-alpha.0-20240513-d472746b
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#904 [NIGHTLY DEV RELEASE] 0.9.1-alpha.0-20240525-152ae273
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#910 [NIGHTLY DEV RELEASE] 0.9.1-alpha.0-20240528-fdff69d8
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#902 Refactor Channel management
  .github/workflows/chip-tool-tests.yml
  CHANGELOG.md
  chip-testing/src/storage/StorageBackendAsyncJsonFile.ts
  packages/matter-node.js/src/storage/StorageBackendDisk.ts
  packages/matter-node.js/src/storage/StorageBackendJsonFile.ts
  packages/matter-node.js/test/IntegrationTest.ts
  packages/matter.js/src/CommissioningServer.ts
  packages/matter.js/src/MatterController.ts
  packages/matter.js/src/MatterDevice.ts
  packages/matter.js/src/behavior/system/commissioning/CommissioningBehavior.ts
  packages/matter.js/src/behavior/system/network/ServerNetworkRuntime.ts
  packages/matter.js/src/device/PairedNode.ts
  packages/matter.js/src/protocol/ChannelManager.ts
  packages/matter.js/src/protocol/ExchangeManager.ts
  packages/matter.js/src/protocol/MessageExchange.ts
  packages/matter.js/src/protocol/interaction/InteractionClient.ts
  packages/matter.js/src/storage/Storage.ts
  packages/matter.js/src/storage/StorageBackendMemory.ts
  packages/matter.js/src/storage/StorageManager.ts
  packages/matter.js/test/node/ServerNodeTest.ts
Labels: review - approved

#911 [NIGHTLY DEV RELEASE] 0.9.1-alpha.0-20240528-420d2437
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#912 Fix CAT parsing
  packages/matter.js/src/datatype/NodeId.ts
  packages/matter.js/test/datatype/NodeIdTests.ts
Labels: review - pending, hotfix

#914 [NIGHTLY DEV RELEASE] 0.9.1-alpha.0-20240531-2954e66d
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#915 Enhance ACL version communication
  CHANGELOG.md
  packages/matter.js/src/CommissioningServer.ts
  packages/matter.js/src/behavior/definitions/access-control/AccessControlServer.ts
Labels: review - approved
