Repository matter-js/matter.js, pull requests merged in 2024-03, with the labels that each got.

#717 [NIGHTLY DEV RELEASE] 0.8.0-alpha.1-20240308-033110a3
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#718 Re-package network errors and handle in subscription cases
  CHANGELOG.md
  packages/matter-node.js/src/net/UdpChannelNode.ts
  packages/matter.js/src/protocol/interaction/SubscriptionHandler.ts
Labels: review - approved

#722 Remove all code related to persistent versioning
  packages/matter.js/src/behavior/Behavior.ts
  packages/matter.js/src/behavior/cluster/ClusterBehavior.ts
  packages/matter.js/src/behavior/context/server/OfflineContext.ts
  packages/matter.js/src/behavior/internal/BehaviorBacking.ts
  packages/matter.js/src/behavior/state/managed/Datasource.ts
  packages/matter.js/src/behavior/supervision/ValueSupervisor.ts
  packages/matter.js/src/endpoint/Endpoint.ts
  packages/matter.js/src/endpoint/properties/Behaviors.ts
  packages/matter.js/test/behavior/definitions/descriptor/DescriptorServerTest.ts
  packages/matter.js/test/behavior/state/managed/DatasourceTest.ts
Labels: review - approved

#726 Decode empty data types that are nullable with constrains as null
  CHANGELOG.md
  models/src/local/NetworkCommissioningOverrides.ts
  models/src/local/index.ts
  packages/matter.js/src/cluster/definitions/NetworkCommissioningCluster.ts
  packages/matter.js/src/model/standard/elements/NetworkCommissioning.ts
  packages/matter.js/src/tlv/TlvArray.ts
  packages/matter.js/src/tlv/TlvNullable.ts
  packages/matter.js/src/tlv/TlvString.ts
  packages/matter.js/test/tlv/TlvNullableTest.ts
Labels: review - approved

#719 Add documentation for included cluster implementations
  packages/matter.js/README.md
Labels: review - approved

#725 Also remove Data version persistence in legacy code path
  CHANGELOG.md
  packages/matter-node.js/test/IntegrationTest.ts
  packages/matter.js/src/CommissioningServer.ts
Labels: review - approved

#728 [NIGHTLY DEV RELEASE] 0.8.0-alpha.0-20240310-474da21a
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#729 Add convenience infos for node implementors
  docs/MIGRATION_GUIDE_08.md
  packages/matter-node.js-examples/src/examples/DeviceNodeFull.ts
  packages/matter.js/src/behavior/system/commissioning/CommissioningBehavior.ts
  packages/matter.js/src/node/ServerNode.ts
Labels: review - approved

#733 [NIGHTLY DEV RELEASE] 0.8.0-alpha.0-20240311-5db51a2e
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#734 [NIGHTLY DEV RELEASE] 0.8.0-alpha.0-20240311-6006c732
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#736 [NIGHTLY DEV RELEASE] 0.8.0-alpha.0-20240311-6a811d05
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#738 Model analysis optimizations
  packages/matter.js-tools/src/testing/node.ts
  packages/matter.js/src/behavior/state/validation/assertions.ts
  packages/matter.js/src/model/logic/ModelTraversal.ts
  packages/matter.js/src/model/logic/definition-validation/ValueValidator.ts
  packages/matter.js/src/model/models/Aspects.ts
  packages/matter.js/src/model/models/AttributeModel.ts
  packages/matter.js/src/model/models/Children.ts
  packages/matter.js/src/model/models/ClusterModel.ts
  packages/matter.js/src/model/models/CommandModel.ts
  packages/matter.js/src/model/models/DatatypeModel.ts
  packages/matter.js/src/model/models/DeviceTypeModel.ts
  packages/matter.js/src/model/models/EndpointModel.ts
  packages/matter.js/src/model/models/EventModel.ts
  packages/matter.js/src/model/models/FabricModel.ts
  packages/matter.js/src/model/models/FieldModel.ts
  packages/matter.js/src/model/models/MatterModel.ts
  packages/matter.js/src/model/models/Model.ts
  packages/matter.js/src/model/models/NodeModel.ts
  packages/matter.js/src/model/models/RequirementModel.ts
  packages/matter.js/src/model/models/ValueModel.ts
  packages/matter.js/src/util/AsyncConstruction.ts
Labels: review - approved

#739 [NIGHTLY DEV RELEASE] 0.8.0-alpha.0-20240313-a06243dc
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#743 Make IndexBehavior dependency of DescriptorServer
  packages/matter.js/src/behavior/definitions/descriptor/DescriptorServer.ts
Labels: review - approved

#742 Good times with TypeScript
  .eslintrc.json
  codegen/package.json
  package-lock.json
  package.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
  packages/matter.js/src/behavior/Behavior.ts
  packages/matter.js/src/behavior/cluster/ClusterBehaviorUtil.ts
  packages/matter.js/src/behavior/cluster/ClusterEvents.ts
  packages/matter.js/src/behavior/system/network/ServerNetworkRuntime.ts
  packages/matter.js/src/cluster/ClusterType.ts
  packages/matter.js/src/cluster/mutation/ClusterComposer.ts
  packages/matter.js/src/endpoint/Endpoint.ts
  packages/matter.js/src/node/Node.ts
  packages/matter.js/test/behavior/cluster/ClusterBehaviorTest.ts
  packages/matter.js/test/behavior/cluster/ClusterEventsTest.ts
  packages/matter.js/test/tsconfigs/nonstrict/lenientTest.ts
  packages/matter.js/test/tsconfigs/nonstrict/tsconfig.json
Labels: review - approved

#740 Add Thread based docs
  USAGE_THREAD.md
  docs/MIGRATION_GUIDE_08.md
  packages/matter-node.js-examples/src/examples/cluster/DummyThreadNetworkCommissioningServer.ts
  packages/matter-node.js/src/environment/NodeJsEnvironment.ts
  packages/matter.js/README.md
Labels: review - approved

#744 [NIGHTLY DEV RELEASE] 0.8.0-alpha.0-20240314-ed7b831b
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#746 Additional tests and a fix
  packages/matter.js/src/MatterDevice.ts
  packages/matter.js/src/behavior/definitions/basic-information/BasicInformationServer.ts
  packages/matter.js/src/behavior/definitions/general-commissioning/ServerNodeFailsafeContext.ts
  packages/matter.js/src/behavior/definitions/operational-credentials/OperationalCredentialsServer.ts
  packages/matter.js/src/behavior/internal/ClusterServerBacking.ts
  packages/matter.js/src/behavior/system/network/ServerNetworkRuntime.ts
  packages/matter.js/test/behavior/internal/ClusterServerBackingTest.ts
  packages/matter.js/test/node/ServerNodeTest.ts
Labels: review - approved

#748 Adjust endpoint state type to read-only
  packages/matter.js/src/behavior/definitions/general-commissioning/ServerNodeFailsafeContext.ts
  packages/matter.js/src/endpoint/Endpoint.ts
  packages/matter.js/src/endpoint/properties/Behaviors.ts
  packages/matter.js/src/util/Type.ts
Labels: review - approved

#747 Prevent async reaction to sync observables
  packages/matter.js/src/behavior/Reactor.ts
  packages/matter.js/src/behavior/definitions/operational-credentials/OperationalCredentialsServer.ts
  packages/matter.js/src/behavior/internal/Reactors.ts
  packages/matter.js/test/behavior/internal/ReactorsTest.ts
Labels: review - approved

#749 Storage conversion and some enhancements
  packages/matter-node.js-examples/README.md
  packages/matter-node.js-examples/package.json
  packages/matter-node.js-examples/src/examples/ControllerNode.ts
  packages/matter-node.js-examples/src/examples/DeviceNode.ts
  packages/matter-node.js-examples/src/examples/LegacyStorageConverter.ts
  packages/matter.js/README.md
Labels: review - approved

#750 [NIGHTLY DEV RELEASE] 0.8.0-alpha.0-20240317-b07eaba6
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#753 Fix a couple of bugs in Model and codegen
  codegen/src/generate-model.ts
  codegen/src/mom/spec/translate-device.ts
  codegen/src/util/TsFile.ts
  models/src/local/ColorControlOverrides.ts
  packages/matter.js/src/endpoint/definitions/device/ColorDimmerSwitchDevice.ts
  packages/matter.js/src/endpoint/definitions/device/ControlBridgeDevice.ts
  packages/matter.js/src/endpoint/definitions/device/DimmerSwitchDevice.ts
  packages/matter.js/src/endpoint/definitions/device/DoorLockControllerDevice.ts
  packages/matter.js/src/endpoint/definitions/device/OnOffLightSwitchDevice.ts
  packages/matter.js/src/endpoint/definitions/device/OnOffSensorDevice.ts
  packages/matter.js/src/endpoint/definitions/device/PumpControllerDevice.ts
  packages/matter.js/src/endpoint/definitions/device/PumpDevice.ts
  packages/matter.js/src/endpoint/definitions/device/ThermostatDevice.ts
  packages/matter.js/src/endpoint/definitions/device/WindowCoveringControllerDevice.ts
  packages/matter.js/src/model/logic/MergedModel.ts
  packages/matter.js/src/model/logic/ModelVariantTraversal.ts
  packages/matter.js/src/model/logic/index.ts
  packages/matter.js/src/model/models/Children.ts
  packages/matter.js/src/model/models/CommandModel.ts
  packages/matter.js/src/model/models/Model.ts
  packages/matter.js/src/model/models/RequirementModel.ts
  packages/matter.js/src/model/standard/elements/ColorDimmerSwitchDT.ts
  packages/matter.js/src/model/standard/elements/ControlBridgeDT.ts
  packages/matter.js/src/model/standard/elements/DimmerSwitchDT.ts
  packages/matter.js/src/model/standard/elements/DoorLockControllerDT.ts
  packages/matter.js/src/model/standard/elements/OnOffLightSwitchDT.ts
  packages/matter.js/src/model/standard/elements/OnOffSensorDT.ts
  packages/matter.js/src/model/standard/elements/PumpControllerDT.ts
  packages/matter.js/src/model/standard/elements/PumpDT.ts
  packages/matter.js/src/model/standard/elements/ThermostatDT.ts
  packages/matter.js/src/model/standard/elements/WindowCoveringControllerDT.ts
  packages/matter.js/test/model/logic/MergeModelsTest.ts
  packages/matter.js/test/model/models/ModelTest.ts
Labels: review - approved

#754 [NIGHTLY DEV RELEASE] 0.8.0-alpha.0-20240319-3d88df96
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#757 Added moveToLevel command handler to LevelControlServer.ts.
  package-lock.json
  packages/matter.js/src/behavior/definitions/level-control/LevelControlServer.ts
Labels: review - approved

#758 [NIGHTLY DEV RELEASE] 0.8.0-alpha.0-20240323-0dec5662
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#760 Make sure to stay in TS minor ranges
  codegen/package.json
  package-lock.json
  package.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: review - approved

#759 Use real fabrics on commissioning check
  packages/matter-node.js-examples/README.md
  packages/matter.js/src/behavior/system/commissioning/CommissioningBehavior.ts
Labels: review - approved

#756 Add some Migration guide FAQ entries
  docs/MIGRATION_GUIDE_08.md
Labels: review - approved

#765 [NIGHTLY DEV RELEASE] 0.8.0-alpha.0-20240325-38a92dd1
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#770 [NIGHTLY DEV RELEASE] 0.8.0-alpha.0-20240328-f7f45db5
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#771 Remove debug logging again
  packages/matter.js/src/crypto/Spake2p.ts
  packages/matter.js/src/session/pase/PaseClient.ts
  packages/matter.js/src/session/pase/PaseServer.ts
Labels: review - pending

#773 Rename BridgedDeviceNode file as expected
  packages/matter-node.js-examples/src/examples/BridgedDevicesNode.ts
Labels: review - approved

#774 [NIGHTLY DEV RELEASE] 0.8.0-alpha.0-20240328-858ab599
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#775 Increase default Subscription time to 60s
  packages/matter.js/src/device/PairedNode.ts
Labels: review - approved

#776 [NIGHTLY DEV RELEASE] 0.8.0-alpha.0-20240329-133f426f
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#777 Adjust typedoc and add missing new API endpoints
  packages/matter-node.js/src/tsconfig.json
  packages/matter.js/package.json
  packages/matter.js/src/cluster/mutation/ClusterComposer.ts
  packages/matter.js/src/node/ServerNode.ts
  packages/matter.js/src/tsconfig.docs.json
  packages/matter.js/src/tsconfig.json
  packages/matter.js/src/util/Type.ts
Labels: review - pending

#781 Makes Identify default custer server more convenient
  CHANGELOG.md
  packages/matter-node.js-examples/src/examples/BridgedDevicesNode.ts
  packages/matter-node.js-examples/src/examples/ComposedDeviceNode.ts
  packages/matter-node.js-examples/src/examples/DeviceNode.ts
  packages/matter-node.js-examples/src/examples/DeviceNodeFull.ts
  packages/matter-node.js-examples/src/examples/MultiDeviceNode.ts
  packages/matter.js/README.md
  packages/matter.js/src/behavior/definitions/identify/IdentifyServer.ts
Labels: review - approved

#782 Optimize OnOff Server default implementation
  packages/matter.js/README.md
  packages/matter.js/src/behavior/definitions/on-off/OnOffServer.ts
Labels: review - approved
