Repository matter-js/matter.js, pull requests merged in 2024-02, with the labels that each got.

#685 [NIGHTLY DEV RELEASE] 0.7.5-alpha.0-20240207-b8ba7c4f
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#674 Improve FabricIndex handling for Client usages
  CHANGELOG.md
  packages/matter.js/src/cluster/client/AttributeClient.ts
  packages/matter.js/src/datatype/FabricIndex.ts
  packages/matter.js/src/protocol/interaction/InteractionClient.ts
  packages/matter.js/src/tlv/TlvAny.ts
  packages/matter.js/src/tlv/TlvArray.ts
  packages/matter.js/src/tlv/TlvNullable.ts
  packages/matter.js/src/tlv/TlvObject.ts
  packages/matter.js/src/tlv/TlvSchema.ts
  packages/matter.js/src/tlv/TlvWrapper.ts
  packages/matter.js/test/tlv/TlvObjectTest.ts
Labels: review - approved

#675 Validate the request when invoking a command from Client
  CHANGELOG.md
  packages/matter.js/src/protocol/interaction/InteractionClient.ts
Labels: review - approved

#671 Shell enhancements for Attributes, Events and Comments
  CHANGELOG.md
  packages/matter-node-shell.js/README.md
  packages/matter-node-shell.js/src/shell/Shell.ts
  packages/matter-node-shell.js/src/shell/cmd_cluster-attributes.ts
  packages/matter-node-shell.js/src/shell/cmd_cluster-commands.ts
  packages/matter-node-shell.js/src/shell/cmd_cluster-events.ts
  packages/matter-node-shell.js/src/shell/cmd_config.ts
  packages/matter-node-shell.js/src/shell/cmd_lock.ts
  packages/matter-node-shell.js/src/shell/cmd_onoff.ts
  packages/matter-node-shell.js/src/shell/cmd_subscribe.ts
  packages/matter-node-shell.js/src/util/Json.ts
  packages/matter-node-shell.js/src/util/String.ts
  packages/matter-node.js/test/cluster/GroupsServerTest.ts
  packages/matter-node.js/test/cluster/ScenesServerTest.ts
  packages/matter.js/src/cluster/server/AttributeServer.ts
  packages/matter.js/src/common/ValidationError.ts
  packages/matter.js/src/protocol/interaction/InteractionServer.ts
  packages/matter.js/src/tlv/TlvArray.ts
  packages/matter.js/src/tlv/TlvObject.ts
  packages/matter.js/test/tlv/TlvArrayTest.ts
  packages/matter.js/test/tlv/TlvComplexTest.ts
  packages/matter.js/test/tlv/TlvObjectTest.ts
Labels: review - approved

#672 Allow multiple loggers and add File Logger
  CHANGELOG.md
  codegen/src/util/setup.ts
  packages/matter-node-shell.js/src/app.ts
  packages/matter-node-shell.js/src/shell/cmd_config.ts
  packages/matter-node.js/package.json
  packages/matter-node.js/src/log/FileLogger.ts
  packages/matter-node.js/src/log/export.ts
  packages/matter.js/src/log/Logger.ts
  packages/matter.js/test/log/LoggerTest.ts
  packages/matter.js/test/support/logging.ts
Labels: review - approved

#673 Added a quote aware command line parser to shell
  CHANGELOG.md
  packages/matter-node-shell.js/src/shell/Shell.ts
  packages/matter.js/src/util/CommandlineParser.ts
  packages/matter.js/src/util/export.ts
Labels: review - approved

#700 [NIGHTLY DEV RELEASE] 0.7.5-alpha.0-20240222-8567d1b1
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#701 Make NetworkCommissioningCluster optional
  CHANGELOG.md
  packages/matter.js/src/CommissioningServer.ts
  packages/matter.js/src/common/FailSafeManager.ts
  packages/matter.js/src/protocol/ControllerCommissioner.ts
Labels: review - approved

#702 [NIGHTLY DEV RELEASE] 0.7.5-alpha.0-20240222-8696097f
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#703 Update official-release.yml
  .github/workflows/official-release.yml
Labels: review - pending
