Repository matter-js/matter.js, pull requests merged in 2024-04, with the labels that each got.

#785 [NIGHTLY DEV RELEASE] 0.8.1-alpha.0-20240401-c87f2ece
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#791 Add test for default selection
  packages/matter.js/test/behavior/cluster/ClusterBehaviorTest.ts
Labels: review - approved

#796 [NIGHTLY DEV RELEASE] 0.8.1-alpha.0-20240403-811441fb
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#797 Fix interrupt handling and polyfill Symbol.dispose
  packages/matter-node.js/src/environment/ProcessManager.ts
  packages/matter.js-tools/src/running/cli.ts
  packages/matter.js/src/behavior/Behavior.ts
  packages/matter.js/src/behavior/cluster/ClusterBehaviorUtil.ts
  packages/matter.js/src/environment/Environment.ts
  packages/matter.js/src/polyfills/disposable.ts
  packages/matter.js/test/behavior/cluster/ClusterBehaviorTest.ts
Labels: review - approved

#805 [NIGHTLY DEV RELEASE] 0.8.1-alpha.0-20240409-ac152f0e
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#804 Add minimal DoorLock capabilities
  packages/matter.js/src/behavior/definitions/door-lock/DoorLockServer.ts
Labels: review - approved

#806 Adding Matterbridge and Matterbridge zigbee2mqtt plugin to README.md
  README.md
Labels: review - approved

#807 [NIGHTLY DEV RELEASE] 0.8.1-alpha.0-20240410-343bac39
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#798 Update Events in subscriptions
  packages/matter-node-ble.js/src/ble/BleScanner.ts
  packages/matter-node.js-examples/src/examples/ControllerNode.ts
  packages/matter-node.js-examples/src/examples/ControllerNodeLegacy.ts
  packages/matter-node.js/test/IntegrationTest.ts
  packages/matter-node.js/test/interaction/InteractionProtocolTest.ts
  packages/matter.js/src/MatterController.ts
  packages/matter.js/src/cluster/client/EventClient.ts
  packages/matter.js/src/cluster/server/ClusterServer.ts
  packages/matter.js/src/datatype/EventNumber.ts
  packages/matter.js/src/device/PairedNode.ts
  packages/matter.js/src/mdns/MdnsScanner.ts
  packages/matter.js/src/protocol/interaction/EventDataDecoder.ts
  packages/matter.js/src/protocol/interaction/EventHandler.ts
  packages/matter.js/src/protocol/interaction/InteractionClient.ts
  packages/matter.js/src/protocol/interaction/InteractionProtocol.ts
  packages/matter.js/src/protocol/interaction/InteractionServer.ts
  packages/matter.js/src/protocol/interaction/SubscriptionHandler.ts
  packages/matter.js/test/protocol/interaction/EventDataDecoderTest.ts
Labels: review - approved

#808 Remove invalid length assumption in Sigma2
  packages/matter.js/src/session/case/CaseMessages.ts
Labels: review - approved

#809 [NIGHTLY DEV RELEASE] 0.8.1-alpha.0-20240411-d2dc275b
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#795 LevelControl and other simple Cluster implementations and tests
  .github/workflows/chip-tool-tests.yml
  .github/workflows/nightly-dev-release.yml
  .github/workflows/official-release.yml
  CHANGELOG.md
  chip-testing/patched-test-files/certification/Test_TC_DGGEN_1_1.yaml
  chip-testing/patched-test-files/certification/Test_TC_OCC_1_1.yaml
  chip-testing/patched-test-files/certification/Test_TC_PS_1_1.yaml
  chip-testing/patched-test-files/certification/Test_TC_PS_2_1.yaml
  chip-testing/patched-test-files/certification/Test_TC_TMP_2_1.yaml
  chip-testing/patched-test-files/certification/Test_TC_WAKEONLAN_1_5.yaml
  chip-testing/patched-test-files/certification/ci-pics-values
  chip-testing/src/AllClustersTestInstance.ts
  chip-testing/src/TvTestApp.ts
  chip-testing/src/TvTestInstance.ts
  chip-testing/src/cluster/TestIdentifyServer.ts
  chip-testing/src/cluster/TestLowPowerServer.ts
  codegen/src/clusters/TlvGenerator.ts
  models/src/local/LocalizationConfigurationOverrides.ts
  models/src/local/TimeFormatLocalizationOverrides.ts
  models/src/local/index.ts
  packages/matter-node.js-examples/src/examples/BridgedDevicesNode.ts
  packages/matter-node.js-examples/src/examples/DeviceNodeFull.ts
  packages/matter-node.js-examples/src/examples/SensorDeviceNode.ts
  packages/matter.js/README.md
  packages/matter.js/src/behavior/definitions/boolean-state/BooleanStateServer.ts
  packages/matter.js/src/behavior/definitions/general-diagnostics/GeneralDiagnosticsServer.ts
  packages/matter.js/src/behavior/definitions/identify/IdentifyServer.ts
  packages/matter.js/src/behavior/definitions/level-control/LevelControlServer.ts
  packages/matter.js/src/behavior/definitions/on-off/OnOffServer.ts
  packages/matter.js/src/behavior/state/validation/ValueValidator.ts
  packages/matter.js/src/behavior/state/validation/constraint.ts
  packages/matter.js/src/model/aspects/Constraint.ts
  packages/matter.js/src/model/models/MatterModel.ts
  packages/matter.js/src/model/standard/elements/LocalizationConfiguration.ts
  packages/matter.js/src/model/standard/elements/TimeFormatLocalization.ts
  packages/matter.js/test/behavior/definitions/time-format-localization/TimeFormatLocalizationServerTest.ts
  packages/matter.js/test/behavior/state/managed/DatasourceTest.ts
  packages/matter.js/test/behavior/state/validation/constraintTest.ts
  packages/matter.js/test/behavior/state/validation/validation-test-utils.ts
Labels: review - pending

#816 Implement certificate checks
  CHANGELOG.md
  packages/matter-node-shell.js/src/shell/cmd_cluster-attributes.ts
  packages/matter-node.js/test/IntegrationTest.ts
  packages/matter-node.js/test/certificate/CertificateManagerTest.ts
  packages/matter-node.js/test/certificate/TestCertificates.ts
  packages/matter-node.js/test/cluster/GroupsServerTest.ts
  packages/matter-node.js/test/cluster/ScenesServerTest.ts
  packages/matter-node.js/test/fabric/FabricTestingUtil.ts
  packages/matter.js-tools/src/testing/mocks/crypto.ts
  packages/matter.js/src/MatterController.ts
  packages/matter.js/src/behavior/definitions/operational-credentials/OperationalCredentialsServer.ts
  packages/matter.js/src/certificate/AttestationCertificateManager.ts
  packages/matter.js/src/certificate/CertificateDerTypes.ts
  packages/matter.js/src/certificate/CertificateManager.ts
  packages/matter.js/src/certificate/RootCertificateManager.ts
  packages/matter.js/src/certificate/export.ts
  packages/matter.js/src/cluster/ClusterHelper.ts
  packages/matter.js/src/cluster/client/ClusterClient.ts
  packages/matter.js/src/cluster/server/OperationalCredentialsServer.ts
  packages/matter.js/src/codec/DerCodec.ts
  packages/matter.js/src/common/FailsafeContext.ts
  packages/matter.js/src/crypto/Key.ts
  packages/matter.js/src/datatype/NodeId.ts
  packages/matter.js/src/device/EndpointStructureLogger.ts
  packages/matter.js/src/device/PairedNode.ts
  packages/matter.js/src/fabric/Fabric.ts
  packages/matter.js/src/fabric/FabricManager.ts
  packages/matter.js/src/log/Diagnostic.ts
  packages/matter.js/src/protocol/interaction/AttributeDataDecoder.ts
  packages/matter.js/src/protocol/interaction/EventDataDecoder.ts
  packages/matter.js/src/protocol/interaction/InteractionServer.ts
  packages/matter.js/src/session/case/CaseClient.ts
  packages/matter.js/src/session/case/CaseServer.ts
  packages/matter.js/src/tlv/TlvObject.ts
  packages/matter.js/src/util/Number.ts
  packages/matter.js/test/behavior/internal/ClusterServerBackingTest.ts
  packages/matter.js/test/codec/DerTest.ts
  packages/matter.js/test/node/ServerNodeTest.ts
  packages/matter.js/test/tlv/TlvObjectTest.ts
Labels: review - approved

#826 [NIGHTLY DEV RELEASE] 0.8.2-alpha.0-20240418-809d0493
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#827 Generate Endpoints by default too
  codegen/package.json
Labels: review - approved

#822 Adds additional logging information for PASE and CASE
  CHANGELOG.md
  packages/matter.js/src/protocol/securechannel/SecureChannelMessenger.ts
  packages/matter.js/src/session/case/CaseClient.ts
  packages/matter.js/src/session/case/CaseMessenger.ts
  packages/matter.js/src/session/case/CaseServer.ts
  packages/matter.js/src/session/pase/PaseClient.ts
  packages/matter.js/src/session/pase/PaseMessenger.ts
Labels: review - approved

#831 [NIGHTLY DEV RELEASE] 0.8.2-alpha.0-20240419-cba17ec8
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#830 Fix upper bound for constant-value ranges
  codegen/src/clusters/TlvGenerator.ts
Labels: review - approved

#829 Support immediate event registration
  packages/matter.js/src/behavior/internal/BackingEvents.ts
  packages/matter.js/src/behavior/internal/BehaviorBacking.ts
  packages/matter.js/src/endpoint/Endpoint.ts
  packages/matter.js/src/endpoint/properties/Behaviors.ts
  packages/matter.js/src/util/GeneratedClass.ts
  packages/matter.js/src/util/Observable.ts
  packages/matter.js/test/behavior/BehaviorTest.ts
  packages/matter.js/test/behavior/cluster/ClusterBehaviorTest.ts
Labels: review - approved

#824 Conditionally enable Reachable event on BasicInfo
  .github/workflows/chip-tool-tests.yml
  .github/workflows/nightly-dev-release.yml
  .github/workflows/official-release.yml
  CHANGELOG.md
  chip-testing/patched-test-files/certification/ci-pics-values
  chip-testing/src/AllClustersTestInstance.ts
  chip-testing/src/AllClustersTestInstanceLegacy.ts
  docs/MIGRATION_GUIDE_08.md
  packages/matter.js/src/behavior/cluster/ValidatedElements.ts
  packages/matter.js/src/behavior/definitions/basic-information/BasicInformationServer.ts
  packages/matter.js/src/behavior/internal/ClusterServerBacking.ts
Labels: review - approved

#833 [NIGHTLY DEV RELEASE] 0.8.2-alpha.0-20240420-dd52aa2b
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#834 Corrects errors for two commands on OperationalCredentials
  .github/workflows/chip-tool-tests.yml
  CHANGELOG.md
  packages/matter.js/src/behavior/definitions/operational-credentials/OperationalCredentialsServer.ts
  packages/matter.js/src/cluster/server/OperationalCredentialsServer.ts
Labels: review - approved

#835 [NIGHTLY DEV RELEASE] 0.8.2-alpha.0-20240422-9dfc13ee
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#836 Rename fieldName$Change to fieldName$Changed
  CHANGELOG.md
  packages/matter-node.js-examples/src/examples/BridgedDevicesNode.ts
  packages/matter-node.js-examples/src/examples/ComposedDeviceNode.ts
  packages/matter-node.js-examples/src/examples/DeviceNode.ts
  packages/matter-node.js-examples/src/examples/DeviceNodeFull.ts
  packages/matter-node.js-examples/src/examples/IlluminatedRollerShade.ts
  packages/matter-node.js-examples/src/examples/LightDevice.ts
  packages/matter-node.js-examples/src/examples/MultiDeviceNode.ts
  packages/matter-node.js-examples/src/tutorial/example04.ts
  packages/matter.js/src/behavior/cluster/ClusterBehaviorUtil.ts
  packages/matter.js/src/behavior/cluster/ClusterEvents.ts
  packages/matter.js/src/behavior/cluster/ValidatedElements.ts
  packages/matter.js/src/behavior/definitions/basic-information/BasicInformationServer.ts
  packages/matter.js/src/behavior/definitions/boolean-state/BooleanStateServer.ts
  packages/matter.js/src/behavior/definitions/bridged-device-basic-information/BridgedDeviceBasicInformationServer.ts
  packages/matter.js/src/behavior/definitions/identify/IdentifyServer.ts
  packages/matter.js/src/behavior/definitions/level-control/LevelControlServer.ts
  packages/matter.js/src/behavior/internal/ClusterServerBacking.ts
  packages/matter.js/src/behavior/state/managed/Datasource.ts
  packages/matter.js/test/behavior/BehaviorTest.ts
  packages/matter.js/test/behavior/cluster/ClusterBehaviorTest.ts
  packages/matter.js/test/behavior/cluster/ClusterEventsTest.ts
  packages/matter.js/test/behavior/definitions/descriptor/DescriptorServerTest.ts
  packages/matter.js/test/behavior/state/managed/DatasourceTest.ts
  packages/matter.js/test/behavior/state/managed/values/value-utils.ts
  packages/matter.js/test/node/ServerNodeTest.ts
Labels: review - pending

#837 Add async support for "$Change" events
  CHANGELOG.md
  packages/matter.js/src/behavior/cluster/ClusterBehaviorUtil.ts
  packages/matter.js/src/behavior/state/managed/Datasource.ts
Labels: review - approved

#838 Add another workaround for TS 27965
  CHANGELOG.md
  packages/matter.js/src/behavior/cluster/ClusterBehavior.ts
  packages/matter.js/src/behavior/cluster/ClusterBehaviorUtil.ts
  packages/matter.js/src/behavior/cluster/ClusterInterface.ts
  packages/matter.js/test/behavior/cluster/ClusterBehaviorTest.ts
Labels: review - approved

#840 [NIGHTLY DEV RELEASE] 0.8.2-alpha.0-20240426-18f8d2df
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#839 Fix bounds check with references to null fields
  CHANGELOG.md
  packages/matter.js/src/model/aspects/Constraint.ts
  packages/matter.js/test/behavior/state/validation/constraintTest.ts
  packages/matter.js/test/behavior/state/validation/validation-test-utils.ts
Labels: review - approved

#842 Implement new "fieldName$Changing" event
  CHANGELOG.md
  packages/matter.js/src/behavior/cluster/ClusterBehaviorUtil.ts
  packages/matter.js/src/behavior/cluster/ClusterEvents.ts
  packages/matter.js/src/behavior/internal/BackingEvents.ts
  packages/matter.js/src/behavior/state/managed/Datasource.ts
  packages/matter.js/src/behavior/state/transaction/Participant.ts
  packages/matter.js/src/behavior/state/transaction/Tx.ts
  packages/matter.js/src/common/FailsafeContext.ts
  packages/matter.js/src/common/FailsafeTimer.ts
  packages/matter.js/src/util/DeepCopy.ts
  packages/matter.js/src/util/DeepEqual.ts
  packages/matter.js/src/util/Observable.ts
  packages/matter.js/test/behavior/cluster/ClusterBehaviorTest.ts
  packages/matter.js/test/behavior/cluster/ClusterEventsTest.ts
  packages/matter.js/test/behavior/definitions/descriptor/DescriptorServerTest.ts
  packages/matter.js/test/behavior/state/managed/DatasourceTest.ts
Labels: review - approved

#844 WindowCovering Implementation, LevelControl and Docs update
  .github/actions/prepare-env/action.yml
  .github/workflows/chip-tool-tests.yml
  .github/workflows/nightly-dev-release.yml
  .github/workflows/official-release.yml
  CHANGELOG.md
  chip-testing/patched-test-files/certification/ci-pics-values
  chip-testing/src/AllClustersTestInstance.ts
  chip-testing/src/cluster/TestLevelControlServer.ts
  chip-testing/src/cluster/TestWindowCoveringServer.ts
  docs/MIGRATION_GUIDE_08.md
  models/src/local/WindowCoveringOverrides.ts
  packages/matter.js/src/behavior/definitions/level-control/LevelControlServer.ts
  packages/matter.js/src/behavior/definitions/window-covering/WindowCoveringServer.ts
  packages/matter.js/src/model/standard/elements/WindowCovering.ts
Labels: review - approved

#847 [NIGHTLY DEV RELEASE] 0.8.2-alpha.0-20240427-a2b56dc5
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#845 Enum value conformance
  CHANGELOG.md
  packages/matter.js/src/behavior/definitions/administrator-commissioning/AdministratorCommissioningServer.ts
  packages/matter.js/src/behavior/state/validation/conformance-compiler.ts
  packages/matter.js/src/behavior/state/validation/conformance-util.ts
  packages/matter.js/test/behavior/state/validation/conformanceTest.ts
  packages/matter.js/test/behavior/state/validation/validation-test-utils.ts
Labels: review - approved

#849 PASE log enhance
  .github/workflows/chip-tool-tests.yml
  packages/matter.js/src/session/pase/PaseServer.ts
Labels: review - approved

#850 [NIGHTLY DEV RELEASE] 0.8.2-alpha.0-20240428-df272e50
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#851 ModeSelect cluster implementation, Endpoint.ownerOfType and OTA Management for Level/OnOff, LowPower Optimization
  .github/workflows/chip-tool-tests.yml
  .github/workflows/nightly-dev-release.yml
  .github/workflows/official-release.yml
  CHANGELOG.md
  chip-testing/patched-test-files/certification/Test_TC_MOD_1_1.yaml
  chip-testing/src/AllClustersTestInstance.ts
  chip-testing/src/cluster/TestLowPowerServer.ts
  models/src/local/ModeSelectOverrides.ts
  packages/matter.js/API.md
  packages/matter.js/README.md
  packages/matter.js/src/behavior/definitions/general-diagnostics/GeneralDiagnosticsServer.ts
  packages/matter.js/src/behavior/definitions/level-control/LevelControlServer.ts
  packages/matter.js/src/behavior/definitions/low-power/LowPowerServer.ts
  packages/matter.js/src/behavior/definitions/mode-select/ModeSelectServer.ts
  packages/matter.js/src/behavior/definitions/on-off/OnOffServer.ts
  packages/matter.js/src/endpoint/Endpoint.ts
  packages/matter.js/src/model/standard/elements/ModeSelect.ts
Labels: review - approved

#854 [NIGHTLY DEV RELEASE] 0.8.2-alpha.0-20240429-87252f3d
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#855 Makes various config variables apply dynamically
  CHANGELOG.md
  packages/matter-node.js/src/environment/NodeJsActionTracer.ts
  packages/matter-node.js/src/environment/NodeJsEnvironment.ts
  packages/matter-node.js/src/environment/ProcessManager.ts
  packages/matter.js/src/behavior/system/network/NetworkServer.ts
  packages/matter.js/src/endpoint/Endpoint.ts
  packages/matter.js/src/environment/Environment.ts
  packages/matter.js/src/environment/VariableService.ts
  packages/matter.js/src/node/server/TransactionalInteractionServer.ts
  packages/matter.js/test/environment/VariableServiceTest.ts
Labels: review - approved

#858 Remove custom enum validation
  packages/matter.js/src/behavior/definitions/window-covering/WindowCoveringServer.ts
Labels: review - approved

#856 Datasource tests and bitmap value management
  .github/workflows/chip-tool-tests.yml
  chip-testing/README.md
  codegen/src/clusters/ClusterComponentGenerator.ts
  codegen/src/clusters/DefaultValueGenerator.ts
  codegen/src/clusters/TlvGenerator.ts
  codegen/src/endpoints/TypeGenerator.ts
  packages/matter-node-shell.js/src/util/Json.ts
  packages/matter-node.js/src/behavior/instrumentation.ts
  packages/matter.js/src/behavior/definitions/window-covering/WindowCoveringServer.ts
  packages/matter.js/src/behavior/internal/ClusterServerBacking.ts
  packages/matter.js/src/behavior/state/managed/Datasource.ts
  packages/matter.js/src/behavior/state/managed/values/BitmapManager.ts
  packages/matter.js/src/behavior/state/managed/values/StructManager.ts
  packages/matter.js/src/behavior/state/managed/values/ValueManager.ts
  packages/matter.js/src/behavior/state/transaction/Tx.ts
  packages/matter.js/src/behavior/state/validation/ValueValidator.ts
  packages/matter.js/src/behavior/supervision/BehaviorSupervisor.ts
  packages/matter.js/src/behavior/supervision/RootSupervisor.ts
  packages/matter.js/src/model/logic/definition-validation/ValueValidator.ts
  packages/matter.js/src/model/models/ValueModel.ts
  packages/matter.js/src/util/Observable.ts
  packages/matter.js/test/behavior/definitions/window-covering/WindowCoveringServerTest.ts
  packages/matter.js/test/behavior/state/StateTypeTest.ts
  packages/matter.js/test/behavior/state/managed/DatasourceTest.ts
  packages/matter.js/test/endpoint/mock-endpoint.ts
Labels: review - approved
