Repository matter-js/matter.js, pull requests merged in 2024-08, with the labels that each got.

#1068 [NIGHTLY DEV RELEASE] 0.10.0-alpha.0-20240801-644afa31
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#1069 [NIGHTLY DEV RELEASE] 0.10.0-alpha.0-20240802-4403f787
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#1073 Update existing Application Clusters for Matter 1.3
  .github/workflows/chip-tool-tests.yml
  packages/matter.js/README.md
  packages/matter.js/src/behavior/definitions/boolean-state/BooleanStateServer.ts
  packages/matter.js/src/behavior/definitions/mode-select/ModeSelectServer.ts
  packages/matter.js/src/behavior/definitions/on-off/OnOffServer.ts
Labels: review - approved

#1074 Fixes offline factory reset
  packages/matter.js/src/endpoint/properties/Behaviors.ts
  packages/matter.js/src/node/ServerNode.ts
  packages/matter.js/test/node/ServerNodeTest.ts
Labels: review - approved

#1072 Fix React native Time Utility flag
  packages/matter.js-react-native/src/time/TimeReactNative.ts
Labels: review - approved

#1070 Always read attributes that are not reported by subscriptions
  CHANGELOG.md
  packages/matter-node.js-examples/src/examples/ControllerNode.ts
  packages/matter.js/src/cluster/Cluster.ts
  packages/matter.js/src/cluster/client/AttributeClient.ts
  packages/matter.js/src/cluster/client/EventClient.ts
Labels: review - approved

#1071 Allow device re-announces
  packages/matter.js/src/MatterDevice.ts
Labels: review - approved

#1075 [NIGHTLY DEV RELEASE] 0.10.0-alpha.0-20240803-f4969d2b
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#1076 Add tests for AirQuality and Resource Monitoring 1.3 clusters
  .github/workflows/chip-tool-tests.yml
  chip-testing/src/AllClustersTestInstance.ts
  chip-testing/src/cluster/TestActivatedCarbonFilterMonitoringServer.ts
  chip-testing/src/cluster/TestHEPAFilterMonitoringServer.ts
  packages/matter.js/README.md
  packages/matter.js/src/behavior/internal/ClusterServerBacking.ts
  packages/matter.js/src/cluster/definitions/ActivatedCarbonFilterMonitoringCluster.ts
  packages/matter.js/src/cluster/definitions/CarbonDioxideConcentrationMeasurementCluster.ts
  packages/matter.js/src/cluster/definitions/CarbonMonoxideConcentrationMeasurementCluster.ts
  packages/matter.js/src/cluster/definitions/FormaldehydeConcentrationMeasurementCluster.ts
  packages/matter.js/src/cluster/definitions/HepaFilterMonitoringCluster.ts
  packages/matter.js/src/cluster/definitions/NitrogenDioxideConcentrationMeasurementCluster.ts
  packages/matter.js/src/cluster/definitions/OzoneConcentrationMeasurementCluster.ts
  packages/matter.js/src/cluster/definitions/Pm10ConcentrationMeasurementCluster.ts
  packages/matter.js/src/cluster/definitions/Pm1ConcentrationMeasurementCluster.ts
  packages/matter.js/src/cluster/definitions/Pm2Cluster.ts
  packages/matter.js/src/cluster/definitions/RadonConcentrationMeasurementCluster.ts
  packages/matter.js/src/cluster/definitions/TotalVolatileOrganicCompoundsConcentrationMeasurementCluster.ts
  packages/matter.js/src/model/models/ClusterModel.ts
Labels: review - approved

#1078 Update the Python test execution and simplify like chip
  .github/workflows/chip-tool-tests.yml
  chip-testing/src/AllClustersTestInstance.ts
  chip-testing/src/AllClustersTestInstanceLegacy.ts
  chip-testing/src/cluster/TestGeneralDiagnosticsServer.ts
  packages/matter.js/src/behavior/definitions/basic-information/BasicInformationServer.ts
  packages/matter.js/src/behavior/internal/ClusterServerBacking.ts
  packages/matter.js/test/behavior/internal/ClusterServerBackingTest.ts
Labels: review - approved

#1077 Add Power Topology verification and tests
  .github/workflows/chip-tool-tests.yml
  chip-testing/src/AllClustersTestInstance.ts
  packages/matter.js/README.md
  packages/matter.js/src/behavior/definitions/power-topology/PowerTopologyServer.ts
Labels: review - approved

#1082 [NIGHTLY DEV RELEASE] 0.10.0-alpha.0-20240805-89458ce1
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#1083 [NIGHTLY DEV RELEASE] 0.10.0-alpha.0-20240806-cae61852
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#1085 [NIGHTLY DEV RELEASE] 0.10.0-alpha.0-20240808-bb365a45
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#1079 Enhance Tests to add Switch tests
  .github/workflows/chip-tool-tests.yml
  chip-testing/src/AllClustersTestInstance.ts
  chip-testing/src/NamedPipeCommandHandler.ts
  chip-testing/src/NamedPipeCommands.ts
  chip-testing/src/simulators/SwitchSimulator.ts
  models/src/local/index.ts
  models/src/local/namespace.ts
  models/src/local/semtag.ts
  models/src/local/tag.ts
  packages/matter.js/src/behavior/definitions/switch/SwitchServer.ts
  packages/matter.js/src/model/standard/elements/namespace.ts
  packages/matter.js/src/model/standard/elements/semtag.ts
  packages/matter.js/src/model/standard/elements/tag.ts
  packages/matter.js/test/behavior/definitions/switch/SwitchServerTest.ts
Labels: review - approved

#1089 Freeze operational schema
  packages/matter.js/src/behavior/cluster/ClusterBehaviorUtil.ts
  packages/matter.js/src/behavior/definitions/general-diagnostics/GeneralDiagnosticsServer.ts
  packages/matter.js/src/behavior/definitions/switch/SwitchServer.ts
  packages/matter.js/src/behavior/supervision/BehaviorSupervisor.ts
  packages/matter.js/src/model/aspects/Aspect.ts
  packages/matter.js/src/model/aspects/Conformance.ts
  packages/matter.js/src/model/aspects/Constraint.ts
  packages/matter.js/src/model/models/Children.ts
  packages/matter.js/src/model/models/ClusterModel.ts
  packages/matter.js/src/model/models/Model.ts
  packages/matter.js/src/model/models/ValueModel.ts
  packages/matter.js/test/behavior/definitions/concentration-measurement/ConcentrationMeasurementServerTest.ts
Labels: review - approved

#1090 Add tests for Resource Monitoring and Concentration Clusters
  .github/workflows/chip-tool-tests.yml
  chip-testing/patched-test-files/certification/ci-pics-values
  chip-testing/src/AllClustersTestInstance.ts
  chip-testing/src/cluster/TestActivatedCarbonFilterMonitoringServer.ts
  chip-testing/src/cluster/TestHEPAFilterMonitoringServer.ts
  packages/matter.js/README.md
Labels: review - approved

#1096 [NIGHTLY DEV RELEASE] 0.10.0-alpha.0-20240812-5ae22fff
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#1097 [NIGHTLY DEV RELEASE] 0.10.0-alpha.0-20240813-10402111
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#1098 Handful of small improvements & fixes
  CHANGELOG.md
  chip-testing/src/NamedPipeCommandHandler.ts
  chip-testing/src/simulators/SwitchSimulator.ts
  codegen/src/endpoints/RequirementGenerator.ts
  codegen/src/mom/spec/html-translators.ts
  models/src/v1.3/spec.ts
  packages/matter-node.js-examples/src/examples/SensorDeviceNode.ts
  packages/matter.js/src/behavior/cluster/ClusterBehavior.ts
  packages/matter.js/src/behavior/definitions/bridged-device-basic-information/BridgedDeviceBasicInformationServer.ts
  packages/matter.js/src/behavior/definitions/descriptor/DescriptorServer.ts
  packages/matter.js/src/behavior/definitions/ota-software-update-provider/OtaSoftwareUpdateProviderServer.ts
  packages/matter.js/src/behavior/definitions/ota-software-update-requestor/OtaSoftwareUpdateRequestorServer.ts
  packages/matter.js/src/behavior/definitions/power-source/PowerSourceServer.ts
  packages/matter.js/src/behavior/definitions/power-topology/PowerTopologyServer.ts
  packages/matter.js/src/behavior/system/network/NetworkBehavior.ts
  packages/matter.js/src/cluster/definitions/DoorLockCluster.ts
  packages/matter.js/src/endpoint/Agent.ts
  packages/matter.js/src/endpoint/properties/SupportedBehaviors.ts
  packages/matter.js/src/endpoint/storage/PartStore.ts
  packages/matter.js/src/model/standard/elements/DoorLock.ts
  packages/matter.js/test/behavior/definitions/descriptor/DescriptorServerTest.ts
Labels: review - approved

#1101 Dynamically configure Switch Simulator and no Debouncing
  chip-testing/src/NamedPipeCommandHandler.ts
  chip-testing/src/simulators/SwitchSimulator.ts
Labels: review - approved

#1102 A few semantic tag cleanups
  codegen/src/endpoints/SemanticNamespaceFile.ts
  packages/matter.js/package.json
  packages/matter.js/src/endpoint/definitions/tags/ClosureTag.ts
  packages/matter.js/src/endpoint/definitions/tags/CommonClosureTag.ts
  packages/matter.js/src/endpoint/definitions/tags/CommonCompassDirectionTag.ts
  packages/matter.js/src/endpoint/definitions/tags/CommonCompassLocationTag.ts
  packages/matter.js/src/endpoint/definitions/tags/CommonDirectionTag.ts
  packages/matter.js/src/endpoint/definitions/tags/CommonLevelTag.ts
  packages/matter.js/src/endpoint/definitions/tags/CommonLocationTag.ts
  packages/matter.js/src/endpoint/definitions/tags/CommonNumberTag.ts
  packages/matter.js/src/endpoint/definitions/tags/CommonPositionTag.ts
  packages/matter.js/src/endpoint/definitions/tags/CompassDirectionTag.ts
  packages/matter.js/src/endpoint/definitions/tags/CompassLocationTag.ts
  packages/matter.js/src/endpoint/definitions/tags/DirectionTag.ts
  packages/matter.js/src/endpoint/definitions/tags/ElectricalMeasurementTag.ts
  packages/matter.js/src/endpoint/definitions/tags/LaundryTag.ts
  packages/matter.js/src/endpoint/definitions/tags/LevelTag.ts
  packages/matter.js/src/endpoint/definitions/tags/LocationTag.ts
  packages/matter.js/src/endpoint/definitions/tags/NumberTag.ts
  packages/matter.js/src/endpoint/definitions/tags/PositionTag.ts
  packages/matter.js/src/endpoint/definitions/tags/PowerSourceTag.ts
  packages/matter.js/src/endpoint/definitions/tags/RefrigeratorTag.ts
  packages/matter.js/src/endpoint/definitions/tags/RoomAirConditionerTag.ts
  packages/matter.js/src/endpoint/definitions/tags/SwitchesTag.ts
  packages/matter.js/src/endpoint/type/SemanticNamespace.ts
  packages/matter.js/test/endpoint/type/SemanticNamespaceTest.ts
Labels: review - approved

#1103 Finalize 0.10 release
  CHANGELOG.md
  chip-testing/src/AllClustersTestInstance.ts
  packages/matter.js-react-native/README.md
  packages/matter.js/src/behavior/definitions/basic-information/BasicInformationServer.ts
Labels: review - approved

#1104 [NIGHTLY DEV RELEASE] 0.10.0-alpha.0-20240814-09c39cec
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#1105 Makes sure new active queries are also send out and not overridden
  packages/matter.js/src/mdns/MdnsScanner.ts
Labels: review - approved

#1108 [NIGHTLY DEV RELEASE] 0.10.0-alpha.0-20240816-44eb2b57
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#1109 Skip network commissioning when devcie is already on IP network
  packages/matter-node-ble.js/src/ble/BlenoBleServer.ts
  packages/matter-node-ble.js/src/ble/NobleBleChannel.ts
  packages/matter.js-react-native/src/ble/ReactNativeBleChannel.ts
  packages/matter.js/src/ble/Ble.ts
  packages/matter.js/src/common/Channel.ts
  packages/matter.js/src/net/UdpInterface.ts
  packages/matter.js/src/protocol/ControllerCommissioner.ts
  packages/matter.js/src/protocol/ExchangeManager.ts
  packages/matter.js/src/protocol/interaction/InteractionClient.ts
Labels: review - approved

#1110 [NIGHTLY DEV RELEASE] 0.10.0-alpha.0-20240816-7e794c67
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#1112 Prevents reading subscribed attributes from remote if not requested a…
  CHANGELOG.md
  packages/matter.js/src/cluster/ClusterHelper.ts
  packages/matter.js/src/cluster/client/ClusterClient.ts
Labels: review - approved

#1113 [NIGHTLY DEV RELEASE] 0.10.0-alpha.0-20240817-923902e8
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#1111 Update CHANGELOG.md for latest PR
  CHANGELOG.md
Labels: review - pending

#1119 [NIGHTLY DEV RELEASE] 0.10.0-alpha.0-20240820-846ffb01
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#1122 Include attr/event callbacks when resubscribing a paired node.
  packages/matter.js/src/device/PairedNode.ts
Labels: review - approved

#1123 [NIGHTLY DEV RELEASE] 0.10.0-alpha.0-20240825-d5b4ec2c
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#1129 [NIGHTLY DEV RELEASE] 0.10.0-alpha.0-20240827-5e428cb3
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#1131 Adjust the docs links
  docs/README.md
Labels: review - approved

#1132 Reverts files back to 1.3
  CHANGELOG.md
  chip-testing/patched-test-files/certification/Test_TC_CC_2_1.yaml
  chip-testing/patched-test-files/certification/Test_TC_CC_6_5.yaml
Labels: review - pending

#1133 [OFFICIAL RELEASE] 0.10.0
  CHANGELOG.md
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr

#1134 Prevent mergify from merging automated PRs
  .mergify.yml
  CHANGELOG.md
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: review - pending, hotfix

#1135 Allow chip-test-skip on official release
  .github/workflows/official-release.yml
Labels: review - pending

#1136 Use Node.js 20 by default in test envs
  .github/actions/prepare-env/action.yml
Labels: review - approved, hotfix

#1138 Fix changelog placeholder
  .github/workflows/official-release.yml
  CHANGELOG.md
Labels: review - pending

#1139 lets try if 1 0.10.1 would work
  lerna.json
Labels: review - pending

#1140 restore to latest 0.10-alpha
  lerna.json
Labels: review - pending

#1141 Add esbuild-x64 as package
  package-lock.json
  packages/matter.js-tools/package.json
Labels: review - pending, hotfix

#1142 Try another fresh build package-lock
  package-lock.json
Labels: review - pending

#1143 [OFFICIAL RELEASE] 0.10.0
  CHANGELOG.md
  chip-testing/package.json
  codegen/package.json
  lerna.json
  models/package.json
  package-lock.json
  packages/matter-node-ble.js/package.json
  packages/matter-node-shell.js/package.json
  packages/matter-node.js-examples/package.json
  packages/matter-node.js/package.json
  packages/matter.js-react-native/package.json
  packages/matter.js-tools/package.json
  packages/matter.js/package.json
Labels: automated pr
