Repository matter-js/matter.js, pull requests merged in 2025-05, with the labels that each got.

#1971 [NIGHTLY DEV RELEASE] 0.13.1-alpha.0-20250501-80c86b03e
  version.txt
Labels: automated pr

#1973 verify message security on existing exchanges
  packages/node/test/node/mock-exchange.ts
  packages/protocol/src/protocol/ExchangeManager.ts
  packages/protocol/src/protocol/MessageExchange.ts
Labels: review - approved

#1974 Transitions.applyUpdates can be async
  CHANGELOG.md
  packages/node/src/behavior/Transitions.ts
  packages/node/src/behaviors/color-control/ColorControlServer.ts
  packages/node/src/behaviors/level-control/LevelControlServer.ts
Labels: review - approved, automerge

#1975 Refactor Shell and remove legacy leftovers
  packages/nodejs-shell/src/MatterNode.ts
Labels: review - approved

#1976 [NIGHTLY DEV RELEASE] 0.13.1-alpha.0-20250502-43a54f780
  version.txt
Labels: automated pr

#1978 [NIGHTLY DEV RELEASE] 0.13.1-alpha.0-20250504-87f265a2e
  version.txt
Labels: automated pr

#1979 Try to fix BLE crashes on reconnections
  packages/nodejs-ble/src/NobleBleChannel.ts
Labels: review - approved, automerge

#1980 Fix nightly CHIP SHA handling
  .github/workflows/build-test.chip.yml
Labels: review - approved

#1985 patch a test file for controller tests
  .github/workflows/chip-matterjs-tests.yml
  chip-testing/PATCHED_TESTS_INFO.md
  chip-testing/patched-controller-test-files/certification/Test_TC_BINFO_2_1.yaml
Labels: review - approved, automerge

#1986 Allow Standalone Acks for closing exchanges
  packages/protocol/src/protocol/ExchangeManager.ts
Labels: review - approved, automerge

#1988 [NIGHTLY DEV RELEASE] 0.13.1-alpha.0-20250506-f9ad9c3d8
  version.txt
Labels: automated pr

#1987 Async crypto
  CHANGELOG.md
  chip-testing/src/handler/LegacyControllerCommandHandler.ts
  packages/general/src/crypto/Crypto.ts
  packages/general/src/crypto/Spake2p.ts
  packages/matter.js/src/MatterController.ts
  packages/node/src/behaviors/operational-credentials/OperationalCredentialsServer.ts
  packages/node/test/node/ServerNodeTest.ts
  packages/node/test/node/mock-server-node.ts
  packages/node/test/node/node-helpers.ts
  packages/nodejs/test/certificate/CertificateManagerTest.ts
  packages/nodejs/test/crypto/Spake2pTest.ts
  packages/nodejs/test/fabric/FabricTest.ts
  packages/nodejs/test/fabric/FabricTestingUtil.ts
  packages/nodejs/test/session/SessionManagerTest.ts
  packages/nodejs/test/session/secure/PasePairingTest.ts
  packages/protocol/src/certificate/AttestationCertificateManager.ts
  packages/protocol/src/certificate/CertificateAuthority.ts
  packages/protocol/src/certificate/CertificateManager.ts
  packages/protocol/src/certificate/DeviceCertification.ts
  packages/protocol/src/common/FailsafeContext.ts
  packages/protocol/src/fabric/Fabric.ts
  packages/protocol/src/fabric/FabricAuthority.ts
  packages/protocol/src/fabric/FabricManager.ts
  packages/protocol/src/peer/ControllerCommissioningFlow.ts
  packages/protocol/src/session/SessionManager.ts
  packages/protocol/src/session/case/CaseClient.ts
  packages/protocol/src/session/case/CaseServer.ts
  packages/protocol/src/session/pase/PaseClient.ts
  packages/protocol/src/session/pase/PaseServer.ts
Labels: review - approved, automerge

#1991 Adjust testing to chip changes
  .github/workflows/chip-tool-tests.yml
  chip-testing/test/app-fast/LUNIT.test.ts
Labels: review - approved, automerge

#1994 Increase BLE connect timeout from 60s to 120s.
  packages/nodejs-ble/src/NobleBleChannel.ts
Labels: review - approved, automerge

#1993 Try lower wait to 20ms for fabllback channel pythons
  .github/workflows/chip-tool-tests.yml
Labels: review - approved, automerge

#1996 [NIGHTLY DEV RELEASE] 0.13.1-alpha.0-20250508-047aa0277
  version.txt
Labels: automated pr

#1998 [NIGHTLY DEV RELEASE] 0.13.1-alpha.0-20250509-28e1567e1
  version.txt
Labels: automated pr

#1997 Log RecoverableCommissionError as warning
  packages/protocol/src/peer/ControllerCommissioningFlow.ts
Labels: review - approved, automerge

#1989 Migrate Event Reads to EventResponse
  CHANGELOG.md
  packages/general/src/log/LogFormat.ts
  packages/general/test/log/LoggerTest.ts
  packages/model/src/logic/Scope.ts
  packages/node/src/behavior/internal/BehaviorBacking.ts
  packages/node/src/behavior/internal/ClientBehaviorBacking.ts
  packages/node/src/endpoint/properties/Behaviors.ts
  packages/node/src/node/server/InteractionServer.ts
  packages/node/src/node/server/ProtocolService.ts
  packages/node/test/endpoint/server/InteractionProtocolTest.ts
  packages/node/test/node/AttributeResponseTest.ts
  packages/node/test/node/EventResponseTest.ts
  packages/node/test/node/ServerNodeTest.ts
  packages/protocol/src/action/protocols.ts
  packages/protocol/src/action/request/Read.ts
  packages/protocol/src/action/response/ReadResult.ts
  packages/protocol/src/action/server/AttributeResponse.ts
  packages/protocol/src/action/server/DataResponse.ts
  packages/protocol/src/action/server/EventResponse.ts
  packages/protocol/src/action/server/ServerInteraction.ts
  packages/protocol/src/action/server/index.ts
  packages/protocol/src/events/OccurrenceManager.ts
Labels: review - approved, automerge

#1999 Bump CHIP SHA & drop CHIP build scripts
  chip/Dockerfile
  chip/bin/app
  chip/docker-bake.hcl
  chip/sha.txt
  chip/support/bootstrap-chip
  chip/support/build-one
  chip/support/clone-chip
  chip/support/install-chip-python
Labels: review - approved

#2002 Animate progress time
  packages/tools/src/util/progress.ts
Labels: review - approved

#2000 Subscription Wiring to Attribute/EventResponse
  packages/node/src/behavior/cluster/ClusterBehaviorUtil.ts
  packages/node/src/behavior/state/managed/Datasource.ts
  packages/node/src/behavior/supervision/RootSupervisor.ts
  packages/node/src/behavior/system/network/NetworkServer.ts
  packages/node/src/behavior/system/subscription/SubscriptionBehavior.ts
  packages/node/src/node/server/InteractionServer.ts
  packages/node/src/node/server/ProtocolService.ts
  packages/node/src/node/server/ServerSubscription.ts
  packages/node/src/node/server/index.ts
  packages/node/test/endpoint/server/BehaviorServerTest.ts
  packages/node/test/node/AttributeResponseTest.ts
  packages/node/test/node/EventResponseTest.ts
  packages/node/test/node/FilteredAttributeResponseTest.ts
  packages/node/test/node/mock-exchange.ts
  packages/node/test/node/mock-server-node.ts
  packages/node/test/node/node-helpers.ts
  packages/protocol/src/action/protocols.ts
  packages/protocol/src/action/server/AttributeResponse.ts
  packages/protocol/src/action/server/AttributeSubscriptionResponse.ts
  packages/protocol/src/action/server/EventResponse.ts
  packages/protocol/src/action/server/ServerInteraction.ts
  packages/protocol/src/action/server/index.ts
  packages/protocol/src/events/OccurrenceManager.ts
  packages/protocol/src/interaction/InteractionMessenger.ts
  packages/protocol/src/interaction/ServerSubscription.ts
  packages/protocol/src/interaction/index.ts
  packages/protocol/src/protocol/MessageExchange.ts
Labels: review - approved

#2004 Allow undefined for mandatory nullable props
  packages/node/src/behavior/state/validation/conformance-compiler.ts
  packages/node/test/behavior/state/validation/conformanceTest.ts
Labels: review - approved

#2005 [NIGHTLY DEV RELEASE] 0.13.1-alpha.0-20250511-74ef153aa
  version.txt
Labels: automated pr

#2008 Also publish docker when manually triggered
  .github/workflows/build-test.chip.yml
Labels: review - approved

#2007 Update README.md
  packages/examples/README.md
  packages/examples/src/device-onoff/README.md
Labels: review - approved, automerge

#2014 Allow separate automations for NPM and Docker Releases
  .github/workflows/auto-approve-release.yml
  .github/workflows/build-test.chip.yml
  .github/workflows/nightly-dev-release.yml
  .github/workflows/official-release.yml
  .github/workflows/release-docker.yml
  .github/workflows/release-npm.yml
  .mergify.yml
  .pullapprove.yml
Labels: review - approved, automerge

#2016 [NIGHTLY DEV RELEASE] 0.13.1-alpha.0-20250515-a4c61c546
  version.txt
Labels: automated-npm-release

#2013 Write Refactoring and Subscription Fix
  .github/workflows/chip-tool-tests.yml
  .github/workflows/nightly-dev-release.yml
  .github/workflows/official-release.yml
  CHANGELOG.md
  chip-testing/PATCHED_TESTS_INFO.md
  chip-testing/patched-test-files/TestAccessControlCluster.yaml
  chip-testing/patched-test-files/certification/Test_TC_ACL_2_3.yaml
  chip-testing/patched-test-files/certification/Test_TC_ACL_2_4.yaml
  chip-testing/patched-test-files/certification/Test_TC_ACL_2_5.yaml
  chip-testing/patched-test-files/certification/Test_TC_ACL_2_6.yaml
  chip-testing/patched-test-files/certification/Test_TC_ACL_2_8.yaml
  chip-testing/test/core/ACE.test.ts
  chip-testing/test/core/ACL.test.ts
  chip-testing/test/core/IDM.test.ts
  packages/general/test/transaction/TransactionTest.ts
  packages/node/src/behaviors/access-control/AccessControlServer.ts
  packages/node/src/node/server/InteractionServer.ts
  packages/node/src/node/server/OnlineServerInteraction.ts
  packages/node/src/node/server/ProtocolService.ts
  packages/node/src/node/server/ServerSubscription.ts
  packages/node/test/endpoint/server/InteractionProtocolTest.ts
  packages/node/test/node/AttributeReadResponseTest.ts
  packages/node/test/node/AttributeWriteResponseTest.ts
  packages/node/test/node/EventReadResponseTest.ts
  packages/node/test/node/FilteredAttributeResponseTest.ts
  packages/node/test/node/ServerNodeTest.ts
  packages/node/test/node/read-helpers.ts
  packages/protocol/src/action/Interactable.ts
  packages/protocol/src/action/client/ClientInteraction.ts
  packages/protocol/src/action/protocols.ts
  packages/protocol/src/action/request/Write.ts
  packages/protocol/src/action/response/InvokeResult.ts
  packages/protocol/src/action/response/ReadResult.ts
  packages/protocol/src/action/response/WriteResult.ts
  packages/protocol/src/action/server/AccessControl.ts
  packages/protocol/src/action/server/AttributeReadResponse.ts
  packages/protocol/src/action/server/AttributeSubscriptionResponse.ts
  packages/protocol/src/action/server/AttributeWriteResponse.ts
  packages/protocol/src/action/server/DataResponse.ts
  packages/protocol/src/action/server/EventReadResponse.ts
  packages/protocol/src/action/server/ServerInteraction.ts
  packages/protocol/src/action/server/index.ts
  packages/protocol/src/interaction/InteractionClient.ts
  packages/protocol/src/interaction/InteractionMessenger.ts
  packages/testing/src/docker/edit.ts
  packages/types/src/protocol/types/TlvAttributeData.ts
Labels: review - approved

#2017 [NIGHTLY DEV RELEASE] 0.13.1-alpha.0-20250516-6288f3c54
  version.txt
Labels: automated-npm-release

#2019 Updates for CHIP shuffling
  chip/Dockerfile
  chip/sha.txt
  chip/support/install-chip-python
  packages/testing/src/chip/config.ts
Labels: review - approved, automerge

#2022 [NIGHTLY DEV RELEASE] 0.13.1-alpha.0-20250517-99a1e848a
  version.txt
Labels: automated-npm-release

#2036 [CHIP BUILD] ef66cd8f16a542dfae37e90e7189f893d446c27e
  chip/SHA.txt
Labels: automated-docker-release

#2040 [NIGHTLY DEV RELEASE] 0.13.1-alpha.0-20250520-d699cd56d
  version.txt
Labels: automated-npm-release

#2041 [CHIP BUILD] d3df54eef38613bbb6a674e029bc3c3ea8b6df12
  chip/SHA.txt
Labels: automated-docker-release

#2043 Migrating "logEndpoint" to log via Disgnostics
  CHANGELOG.md
  packages/examples/src/device-bridge-onoff/BridgedDevicesNode.ts
  packages/examples/src/device-composed-onoff/ComposedDeviceNode.ts
  packages/examples/src/device-multiple-onoff/MultiDeviceNode.ts
  packages/examples/src/device-onoff-advanced/DeviceNodeFull.ts
  packages/examples/src/device-onoff/DeviceNode.ts
  packages/examples/src/device-sensor/SensorDeviceNode.ts
  packages/matter.js/src/device/Endpoint.ts
  packages/matter.js/src/device/PairedNode.ts
  packages/matter.js/src/device/export.ts
  packages/node/src/endpoint/Endpoint.ts
  packages/node/src/endpoint/properties/Behaviors.ts
  packages/nodejs-shell/src/shell/cmd_nodes.ts
  packages/protocol/src/cluster/client/AttributeClient.ts
  packages/protocol/src/cluster/client/ClusterClientTypes.ts
  packages/protocol/src/endpoint/EndpointStructureLogger.ts
  packages/protocol/src/endpoint/index.ts
  packages/protocol/src/interaction/InteractionClient.ts
Labels: review - approved

#2020 Invoke rewire
  .github/workflows/build-test.chip.yml
  CHANGELOG.md
  chip/SHA.txt
  packages/node/src/behavior/Events.ts
  packages/node/src/endpoint/server/BehaviorServer.ts
  packages/node/src/endpoint/server/EndpointServer.ts
  packages/node/src/node/server/InteractionServer.ts
  packages/node/src/node/server/OnlineServerInteraction.ts
  packages/node/src/node/server/ProtocolService.ts
  packages/node/test/endpoint/server/InteractionProtocolTest.ts
  packages/node/test/node/AttributeReadResponseTest.ts
  packages/node/test/node/CommandInvokeResponseTest.ts
  packages/protocol/src/action/Interactable.ts
  packages/protocol/src/action/client/ClientInteraction.ts
  packages/protocol/src/action/protocols.ts
  packages/protocol/src/action/request/Invoke.ts
  packages/protocol/src/action/request/Read.ts
  packages/protocol/src/action/request/Write.ts
  packages/protocol/src/action/response/InvokeResult.ts
  packages/protocol/src/action/response/ReadResult.ts
  packages/protocol/src/action/server/AttributeReadResponse.ts
  packages/protocol/src/action/server/CommandInvokeResponse.ts
  packages/protocol/src/action/server/EventReadResponse.ts
  packages/protocol/src/action/server/ServerInteraction.ts
  packages/protocol/src/action/server/index.ts
  packages/protocol/src/interaction/InteractionEndpointStructure.ts
  packages/protocol/src/interaction/index.ts
  packages/types/src/protocol/types/TlvCommandPath.ts
  packages/types/src/protocol/types/TlvStatus.ts
Labels: review - approved

#2049 [NIGHTLY DEV RELEASE] 0.14.0-alpha.0-20250521-979eda05d
  version.txt
Labels: automated-npm-release

#2050 [CHIP BUILD] a7cf007ff8107a4d9e8ca332f950264890df7f6e
  chip/sha.txt
Labels: automated-docker-release

#2051 Allow subscriptions for non-associated fabric sessions
  .github/workflows/chip-tool-tests.yml
  packages/node/src/node/server/InteractionServer.ts
  packages/node/src/node/server/ProtocolService.ts
Labels: review - approved, automerge

#2053 Make MDNS aware of what the nodes are interested in
  CHANGELOG.md
  packages/matter.js/src/CommissioningController.ts
  packages/matter.js/src/device/PairedNode.ts
  packages/node/src/behavior/system/network/ServerNetworkRuntime.ts
  packages/protocol/src/mdns/MdnsScanner.ts
  packages/protocol/test/mdns/MdnsTest.ts
Labels: review - approved

#2054 Revive Prio based Event Culling
  packages/protocol/src/events/OccurrenceManager.ts
Labels: review - approved, automerge

#2055 Upgrade noble and bleno
  CHANGELOG.md
  package-lock.json
  packages/nodejs-ble/package.json
Labels: review - approved, automerge

#2057 Remove Legacy Fabricscoped data store on Fabric
  packages/matter.js/src/cluster/server/AttributeServer.ts
  packages/protocol/src/fabric/Fabric.ts
Labels: review - approved, automerge

#2059 [NIGHTLY DEV RELEASE] 0.14.0-alpha.0-20250524-51a7e1721
  version.txt
Labels: automated-npm-release

#1990 Matter Shell WebSocket
  CHANGELOG.md
  package-lock.json
  packages/nodejs-shell/README.md
  packages/nodejs-shell/package.json
  packages/nodejs-shell/src/app.ts
  packages/nodejs-shell/src/shell/Shell.ts
  packages/nodejs-shell/src/shell/cmd_subscribe.ts
  packages/nodejs-shell/src/shell/webassets/WebShell.png
  packages/nodejs-shell/src/shell/webassets/favicon.png
  packages/nodejs-shell/src/shell/webassets/index.html
  packages/nodejs-shell/src/web_plumbing.ts
Labels: review - approved, automerge

#2060 [NIGHTLY DEV RELEASE] 0.14.0-alpha.0-20250525-d6ada0d45
  version.txt
Labels: automated-npm-release

#2061 Fix CHIP tests
  chip-testing/test/core/SC.test.ts
  chip/sha.txt
  chip/support/generate-test-descriptor
  packages/general/src/crypto/Crypto.ts
  packages/nodejs/src/crypto/NodeJsCrypto.ts
  packages/protocol/src/fabric/FabricManager.ts
  packages/protocol/src/session/case/CaseServer.ts
  packages/testing/src/chip/chip.ts
  packages/tools/src/ansi-text/text-writer.ts
  packages/tools/src/ansi-text/wrapper.ts
Labels: review - approved

#2064 Add Gladys Assistant to list of matter.js-based projects in README
  README.md
Labels: review - approved

#2066 [NIGHTLY DEV RELEASE] 0.14.0-alpha.0-20250527-b2a4cc12b
  version.txt
Labels: automated-npm-release

#2069 [NIGHTLY DEV RELEASE] 0.14.0-alpha.0-20250528-ad0054c84
  version.txt
Labels: automated-npm-release

#2070 [CHIP BUILD] 9ff282f94caf0db1807730ce90f57075bd23d4ad
  support/chip/sha.txt
Labels: automated-docker-release

#2072 Add explicit transaction isolation
  packages/general/src/transaction/Transaction.ts
  packages/general/src/transaction/Tx.ts
  packages/general/test/transaction/TransactionTest.ts
  packages/node/src/behavior/context/server/OfflineContext.ts
  packages/node/src/behavior/context/server/OnlineContext.ts
  packages/node/src/behavior/state/managed/Datasource.ts
  packages/testing/src/util/heap.ts
  support/tests/test/subscription-leaks.test.ts
Labels: automerge

#2073 [NIGHTLY DEV RELEASE] 0.14.0-alpha.0-20250528-d6d12ae65
  version.txt
Labels: automated-npm-release

#2075 [CHIP BUILD] 68fb9b5fb730ab341e62976bac402efb7b8e0bfd
  support/chip/sha.txt
Labels: automated-docker-release

#2077 [CHIP BUILD]
  support/chip/sha.txt
Labels: automated-docker-release

#2076 SC 3.4 should normally work now
  support/chip-testing/test/core/SC.test.ts
  support/chip/sha.txt
Labels: review - approved

#2080 [CHIP BUILD] 06cf5b8776054ad7320ffb776c18b8fda3fed058
  support/chip/sha.txt
Labels: automated-docker-release

#2082 [NIGHTLY DEV RELEASE] 0.14.0-alpha.0-20250530-5730c9bd1
  version.txt
Labels: automated-npm-release

#2087 [CHIP BUILD] 855bd8ef7df315d5b55d9ae34fbcec00a14e08ec
  support/chip/sha.txt
Labels: automated-docker-release

#2086 Conformance tweaks and fixes for Occupancy Sensing
  packages/model/src/aspects/Conformance.ts
  packages/node/src/behavior/cluster/ClusterBehaviorUtil.ts
  packages/node/src/behavior/state/validation/conformance-compiler.ts
  packages/node/src/behaviors/occupancy-sensing/OccupancySensingServer.ts
  packages/node/test/behavior/state/validation/conformanceTest.ts
  packages/node/test/behaviors/occupancy-sensing/OccupancySensingServerTest.ts
Labels: review - approved, automerge
