Repository matter-js/matter.js, pull requests merged in 2025-07, with the labels that each got.

#2218 Even more over-engineered SubtleCrypto detection
  packages/general/src/crypto/StandardCrypto.ts
Labels: review - approved, automerge

#2222 [NIGHTLY DEV RELEASE] 0.15.2-alpha.0-20250704-2715344f0
  version.txt
Labels: automated-npm-release

#2234 [NIGHTLY DEV RELEASE] 0.15.2-alpha.0-20250708-b8eb61a5e
  version.txt
Labels: automated-npm-release

#2251 Pass fabric and ca from options to matter.js MatterController class
  packages/matter.js/src/CommissioningController.ts
Labels: review - approved

#2254 [NIGHTLY DEV RELEASE] 0.15.2-alpha.0-20250717-3607eeac6
  version.txt
Labels: automated-npm-release

#2256 Fix attribute generation for [Field] conformance
  packages/model/src/logic/cluster-variance/InferredComponents.ts
  packages/node/test/behavior/state/validation/conformanceTest.ts
  packages/node/test/behaviors/service-area/ServiceAreaServerTest.ts
  packages/types/src/clusters/service-area.ts
  support/chip-testing/src/RvcTestInstance.ts
  support/chip-testing/test/.gitignore
Labels: review - approved

#2253 Flesh out write logic for ClientNode
  packages/general/src/MatterError.ts
  packages/general/src/log/Diagnostic.ts
  packages/general/src/transaction/index.ts
  packages/matter.js/src/device/CachedClientNodeStore.ts
  packages/matter.js/src/device/ClientEndpointStore.ts
  packages/model/src/common/DataModelPath.ts
  packages/node/src/behavior/internal/BehaviorBacking.ts
  packages/node/src/behavior/internal/ClientBehaviorBacking.ts
  packages/node/src/behavior/internal/ServerBehaviorBacking.ts
  packages/node/src/behavior/state/managed/Datasource.ts
  packages/node/src/behavior/supervision/RootSupervisor.ts
  packages/node/src/node/ClientNode.ts
  packages/node/src/node/ServerNode.ts
  packages/node/src/node/client/ClientEndpointInitializer.ts
  packages/node/src/node/client/ClientStructure.ts
  packages/node/src/node/server/ServerEndpointInitializer.ts
  packages/node/src/node/server/ServerEnvironment.ts
  packages/node/src/storage/EndpointStore.ts
  packages/node/src/storage/client/ClientEndpointStore.ts
  packages/node/src/storage/client/ClientNodeStore.ts
  packages/node/src/storage/client/ClientNodeStores.ts
  packages/node/src/storage/client/DatasourceCache.ts
  packages/node/src/storage/client/RemoteWriteParticipant.ts
  packages/node/src/storage/client/RemoteWriter.ts
  packages/node/src/storage/server/DatasourceStore.ts
  packages/node/src/storage/server/ServerEndpointStore.ts
  packages/node/src/storage/server/ServerNodeStore.ts
  packages/node/test/node/ClientNodeTest.ts
  packages/node/test/node/mock-site.ts
  packages/protocol/src/action/errors.ts
  packages/protocol/src/action/response/WriteResult.ts
  packages/protocol/src/common/ExpandedPath.ts
  packages/protocol/src/common/ExpandedStatus.ts
  packages/protocol/src/common/PathError.ts
  packages/protocol/src/common/index.ts
Labels: review - approved

#2259 Fixes ServiceArea validation
  CHANGELOG.md
  packages/node/src/behaviors/service-area/ServiceAreaServer.ts
  packages/node/test/behaviors/service-area/ServiceAreaServerTest.ts
Labels: review - approved, automerge

#2272 [NIGHTLY DEV RELEASE] 0.15.2-alpha.0-20250722-a45cf6d45
  version.txt
Labels: automated-npm-release

#2262 Add enum values for Namespace override and use it
  .gitattributes
  CHANGELOG.md
  README.md
  packages/model/src/standard/elements/mode-select-cluster.element.ts
  packages/model/src/standard/elements/namespace.element.ts
  packages/model/src/standard/resources/namespace.resource.ts
  packages/node/src/endpoint/type/SemanticNamespace.ts
  packages/types/src/clusters/mode-select.ts
  packages/types/src/globals/Namespace.ts
  packages/types/src/globals/Semtag.ts
  packages/types/src/globals/index.ts
  support/codegen/src/util/finalize-model.ts
  support/models/src/local/ModeSelectOverrides.ts
  support/models/src/local/namespace.ts
  support/models/src/local/semtag.ts
Labels: review - approved, automerge

#2278 Initial copilot instructions
  .github/copilot-instructions.md
Labels: review - approved, automerge

#2280 [NIGHTLY DEV RELEASE] 0.15.2-alpha.0-20250726-93c65d182
  version.txt
Labels: automated-npm-release

#2282 [OFFICIAL RELEASE] 0.15.2
  CHANGELOG.md
  version.txt
Labels: automated-npm-release

#2293 [NIGHTLY DEV RELEASE] 0.15.3-alpha.0-20250729-ece625909
  version.txt
Labels: automated-npm-release

#2303 [NIGHTLY DEV RELEASE] 0.15.3-alpha.0-20250731-b0f24a28b
  version.txt
Labels: automated-npm-release
