Repository matter-js/matter.js, pull requests merged in 2025-06, with the labels that each got.

#2093 Retry Case client on NoSharedTrustRoot error
  CHANGELOG.md
  packages/protocol/src/peer/PeerSet.ts
  packages/protocol/src/securechannel/SecureChannelMessenger.ts
  packages/protocol/src/session/SessionManager.ts
  packages/protocol/src/session/case/CaseClient.ts
  packages/protocol/src/session/case/CaseMessenger.ts
Labels: review - approved

#2092 Enhance CommissioningError by Status Enum
  CHANGELOG.md
  packages/general/src/util/Error.ts
  packages/protocol/src/peer/ControllerCommissioner.ts
  packages/protocol/src/peer/ControllerCommissioningFlow.ts
  packages/protocol/src/peer/ControllerDiscovery.ts
  packages/react-native/src/net/UdpChannelReactNative.ts
  support/chip-testing/patched-controller-test-files/certification/Test_TC_BINFO_2_1.yaml
Labels: review - approved, automerge

#2103 Remove some leftover forward files
  packages/matter.js/src/forwards/behaviors/ecosystem-information.ts
  packages/matter.js/src/forwards/behaviors/joint-fabric-pki.ts
  packages/matter.js/src/forwards/behaviors/service-area.ts
  packages/matter.js/src/forwards/behaviors/thread-border-router-management.ts
  packages/matter.js/src/forwards/behaviors/thread-network-directory.ts
  packages/matter.js/src/forwards/behaviors/water-heater-management.ts
  packages/matter.js/src/forwards/behaviors/water-heater-mode.ts
  packages/matter.js/src/forwards/behaviors/water-tank-level-monitoring.ts
  packages/matter.js/src/forwards/behaviors/wi-fi-network-management.ts
  packages/matter.js/src/forwards/devices/BatteryStorageDevice.ts
  packages/matter.js/src/forwards/devices/EnergyEvseDevice.ts
  packages/matter.js/src/forwards/devices/HeatPumpDevice.ts
  packages/matter.js/src/forwards/devices/MountedDimmableLoadControlDevice.ts
  packages/matter.js/src/forwards/devices/MountedOnOffControlDevice.ts
  packages/matter.js/src/forwards/devices/NetworkInfrastructureManagerDevice.ts
  packages/matter.js/src/forwards/devices/WaterHeaterDevice.ts
  packages/matter.js/src/forwards/endpoints/JointFabricAdministratorEndpoint.ts
  packages/matter.js/src/forwards/endpoints/SecondaryNetworkInterfaceEndpoint.ts
  packages/matter.js/src/forwards/tags/AreaNamespaceTag.ts
  packages/matter.js/src/forwards/tags/LandmarkNamespaceTag.ts
  packages/matter.js/src/forwards/tags/RelativePositionTag.ts
Labels: review - approved, automerge

#2107 Add utility method `IndexedSet#mapOf`
  packages/general/src/util/Set.ts
Labels: review - approved

#2110 [NIGHTLY DEV RELEASE] 0.14.1-alpha.0-20250605-9fc134af0
  version.txt
Labels: automated-npm-release

#2114 [NIGHTLY DEV RELEASE] 0.14.1-alpha.0-20250606-a9bcd03f9
  version.txt
Labels: automated-npm-release

#2117 Add ClusterClient get*AttributeFromCache()
  CHANGELOG.md
  packages/protocol/src/cluster/client/ClusterClient.ts
  packages/protocol/src/cluster/client/ClusterClientTypes.ts
Labels: review - approved

#2118 [NIGHTLY DEV RELEASE] 0.14.1-alpha.0-20250607-a93593303
  version.txt
Labels: automated-npm-release

#2119 [CHIP BUILD] 09f6fdf93a7e847a42518c076e487f336877a722
  support/chip/sha.txt
Labels: automated-docker-release

#2134 [CHIP BUILD] f89f1a59edde868f15184d285fe51e66a643e590
  support/chip/sha.txt
Labels: automated-docker-release

#2135 Fix diagnostic formatting bugs
  packages/general/src/log/LogFormat.ts
  packages/general/test/log/LoggerTest.ts
Labels: review - approved

#2116 ACL and behavior event refactoring
  CHANGELOG.md
  packages/node/src/behavior/Events.ts
  packages/node/src/behavior/cluster/ClusterBehaviorUtil.ts
  packages/node/src/behavior/context/server/OnlineContext.ts
  packages/node/src/behavior/state/managed/Datasource.ts
  packages/node/src/behavior/supervision/ValueSupervisor.ts
  packages/node/src/behaviors/access-control/AccessControlServer.ts
  packages/node/src/behaviors/operational-credentials/OperationalCredentialsServer.ts
  packages/node/src/node/server/InteractionServer.ts
  packages/node/src/node/server/ProtocolService.ts
  packages/node/test/behavior/state/managed/values/ListManagerTest.ts
  packages/node/test/behavior/state/managed/values/StructManagerTest.ts
  packages/node/test/behavior/state/managed/values/value-utils.ts
  packages/node/test/endpoint/server/InteractionTestUtils.ts
  packages/node/test/node/AttributeReadResponseTest.ts
  packages/node/test/node/EventReadResponseTest.ts
  packages/node/test/node/ServerNodeTest.ts
  packages/node/test/node/mock-server-node.ts
  packages/protocol/src/fabric/Fabric.ts
  packages/protocol/src/groups/FabricGroups.ts
  packages/protocol/src/groups/index.ts
  packages/protocol/src/interaction/FabricAccessControl.ts
  packages/protocol/src/interaction/index.ts
  packages/protocol/src/protocol/MessageExchange.ts
Labels: review - approved, automerge

#2137 Generate classes without eval
  packages/general/src/util/GeneratedClass.ts
  packages/general/test/util/GeneratedClassTest.ts
Labels: review - approved

#2138 [NIGHTLY DEV RELEASE] 0.15.0-alpha.0-20250612-ddd428561
  version.txt
Labels: automated-npm-release

#2142 Allow BLE Scanner to be cancelable
  CHANGELOG.md
  packages/nodejs-ble/src/BleScanner.ts
  packages/nodejs-ble/src/NobleBleClient.ts
  packages/protocol/src/mdns/MdnsScanner.ts
Labels: review - approved

#2147 [NIGHTLY DEV RELEASE] 0.15.0-alpha.0-20250613-a55f991d4
  version.txt
Labels: automated-npm-release

#2148 Fix CHIP SHA update for manual runs
  .github/workflows/build-test.chip.yml
Labels: review - approved

#2151 [NIGHTLY DEV RELEASE] 0.15.0-alpha.0-20250614-b9829e223
  version.txt
Labels: automated-npm-release

#2162 [NIGHTLY DEV RELEASE] 0.15.0-alpha.0-20250616-4b3754906
  version.txt
Labels: automated-npm-release

#2163 Update ECOSYSTEMS.md
  docs/ECOSYSTEMS.md
Labels: review - approved, automerge

#2165 [NIGHTLY DEV RELEASE] 0.15.0-alpha.0-20250617-f4d4cad23
  version.txt
Labels: automated-npm-release

#2171 [NIGHTLY DEV RELEASE] 0.15.0-alpha.0-20250619-df2264f15
  version.txt
Labels: automated-npm-release

#2172 [CHIP BUILD] bb52874026927ad9d343042d38efae80bb9abeb1
  support/chip/sha.txt
Labels: automated-docker-release

#2174 [NIGHTLY DEV RELEASE] 0.15.0-alpha.0-20250620-16e218ed3
  version.txt
Labels: automated-npm-release

#2175 [CHIP BUILD] 1e7f673abddb99c4e8b95753c22c98c00bfce82b
  support/chip/sha.txt
Labels: automated-docker-release

#2176 Enhances CSR content validation
  CHANGELOG.md
  packages/general/src/codec/DerTypes.ts
  packages/protocol/src/certificate/kinds/X509Base.ts
Labels: review - approved, automerge

#2177 Introduce DCL types and basic fetch functions
  packages/protocol/src/dcl/DclClient.ts
  packages/protocol/src/dcl/DclRestApiTypes.ts
  packages/protocol/src/dcl/index.ts
  packages/protocol/src/index.ts
  packages/types/src/dcl/attestation-certificate.ts
  packages/types/src/dcl/device-attestation-revocation.ts
  packages/types/src/dcl/device-software-compliance.ts
  packages/types/src/dcl/device-software-version.ts
  packages/types/src/dcl/device.ts
  packages/types/src/dcl/index.ts
  packages/types/src/dcl/operational-certificate.ts
  packages/types/src/dcl/vendor.ts
  packages/types/src/index.ts
Labels: review - approved

#2187 [NIGHTLY DEV RELEASE] 0.15.0-alpha.0-20250624-e8c89f458
  version.txt
Labels: automated-npm-release

#2189 Fix DNS-SD encoding of special IPv6 addresses
  CHANGELOG.md
  packages/general/src/codec/DnsCodec.ts
  packages/general/src/util/Ip.ts
  packages/general/test/codec/DnsCodecTest.ts
Labels: review - approved, automerge

#2190 Refactor status
  packages/protocol/src/peer/PeerSet.ts
  packages/protocol/src/protocol/ProtocolStatusMessage.ts
  packages/protocol/src/protocol/index.ts
  packages/protocol/src/securechannel/SecureChannelMessenger.ts
  packages/protocol/src/securechannel/SecureChannelProtocol.ts
  packages/protocol/src/securechannel/SecureChannelStatusMessageSchema.ts
  packages/protocol/src/session/case/CaseClient.ts
  packages/protocol/src/session/case/CaseServer.ts
  packages/protocol/src/session/pase/PaseClient.ts
  packages/protocol/src/session/pase/PaseServer.ts
  packages/types/src/protocol/definitions/general.ts
  packages/types/src/protocol/definitions/index.ts
  packages/types/src/protocol/definitions/secure-channel.ts
Labels: review - approved, automerge

#2191 [NIGHTLY DEV RELEASE] 0.15.0-alpha.0-20250625-4a4b1be1b
  version.txt
Labels: automated-npm-release

#2185 Support Non-Concurrent Commissioning flows and refactor MRP handling
  CHANGELOG.md
  package-lock.json
  package.json
  packages/node/test/behavior/state/managed/values/ListManagerTest.ts
  packages/protocol/src/cluster/client/ClusterClient.ts
  packages/protocol/src/cluster/client/ClusterClientTypes.ts
  packages/protocol/src/interaction/InteractionClient.ts
  packages/protocol/src/interaction/InteractionMessenger.ts
  packages/protocol/src/interaction/SubscriptionClient.ts
  packages/protocol/src/peer/ControllerCommissioner.ts
  packages/protocol/src/peer/ControllerCommissioningFlow.ts
  packages/protocol/src/peer/PeerSet.ts
  packages/protocol/src/protocol/ChannelManager.ts
  packages/protocol/src/protocol/ExchangeManager.ts
  packages/protocol/src/protocol/ExchangeProvider.ts
  packages/protocol/src/protocol/MessageChannel.ts
  packages/protocol/src/protocol/MessageExchange.ts
  packages/protocol/src/protocol/index.ts
  packages/testing/package.json
Labels: review - approved, automerge

#2194 Adjust the timing of some workflow schedules
  .github/workflows/build-test.chip.yml
  .github/workflows/chip-matterjs-tests.yml
  .github/workflows/nightly-dev-release.yml
Labels: review - approved, automerge

#2198 Initialize all behaviors before accessing elements
  packages/node/src/endpoint/properties/Behaviors.ts
Labels: review - approved, automerge

#2199 [NIGHTLY DEV RELEASE] 0.15.0-alpha.0-20250626-fc3a84ce9
  version.txt
Labels: automated-npm-release

#2202 [OFFICIAL RELEASE] 0.15.0
  CHANGELOG.md
  version.txt
Labels: automated-npm-release

#2204 Do not install StandardCrypto without web crypto
  CHANGELOG.md
  packages/general/src/crypto/StandardCrypto.ts
Labels: review - approved

#2216 [NIGHTLY DEV RELEASE] 0.15.1-alpha.0-20250630-daa5888a0
  version.txt
Labels: automated-npm-release
