Repository matter-js/matter.js, pull requests merged in 2025-03, with the labels that each got.

#1747 Rework Session addition to use events
  packages/node/src/behavior/system/sessions/SessionsBehavior.ts
  packages/node/src/behavior/system/subscription/SubscriptionBehavior.ts
  packages/protocol/src/interaction/InteractionServer.ts
  packages/protocol/src/protocol/MessageExchange.ts
Labels: review - approved

#1749 [NIGHTLY DEV RELEASE] 0.12.5-alpha.0-20250301-ea7c45cbc
  version.txt
Labels: automated pr

#1748 Add 1.3 Devices to the Ecosystems Doc
  docs/ECOSYSTEMS.md
Labels: review - approved

#1750 [OFFICIAL RELEASE] 0.12.5
  CHANGELOG.md
  version.txt
Labels: automated pr

#1751 Fix a couple of 404's in the main README
  README.md
Labels: review - approved

#1753 Fix a number of URLs
  packages/model/README.md
Labels: review - approved

#1760 [NIGHTLY DEV RELEASE] 0.12.6-alpha.0-20250304-03716637c
  version.txt
Labels: automated pr

#1759 Fix typos
  docs/CLUSTER_DEFAULT_IMPLEMENTATIONS.md
  docs/ECOSYSTEMS.md
  docs/MIGRATION_GUIDE_08.md
  packages/examples/README.md
  packages/nodejs-shell/README.md
  packages/nodejs-shell/src/shell/cmd_config.ts
Labels: review - approved

#1761 TypeScript 5.8 and more deps
  package-lock.json
  package.json
  packages/create/package.json
  packages/react-native/package.json
  packages/testing/package.json
  packages/testing/src/util/text.ts
  packages/testing/src/web.ts
  packages/tools/package.json
Labels: review - approved

#1762 Fix more 404s
  docs/TROUBLESHOOTING.md
  packages/examples/src/device-bridge-onoff/README.md
  packages/examples/src/device-composed-onoff/README.md
  packages/examples/src/device-composed-wc-light/README.md
  packages/examples/src/device-measuring-socket/README.md
  packages/examples/src/device-multiple-onoff/README.md
  packages/examples/src/device-onoff-advanced/README.md
  packages/examples/src/device-onoff-light/README.md
  packages/examples/src/device-onoff/README.md
  packages/examples/src/device-sensor/README.md
  packages/matter.js/README.md
  packages/testing/README.md
Labels: review - approved

#1687 0.13: Matter 1.4 Protocol
  CHANGELOG.md
  packages/matter.js/src/CommissioningServer.ts
  packages/protocol/src/common/Scanner.ts
  packages/protocol/src/mdns/MdnsBroadcaster.ts
  packages/protocol/src/mdns/MdnsScanner.ts
  packages/protocol/src/peer/ControllerCommissioningFlow.ts
  packages/protocol/src/session/Session.ts
  packages/protocol/src/session/SessionManager.ts
  packages/protocol/src/session/pase/PaseClient.ts
  packages/protocol/src/session/pase/PaseMessages.ts
  packages/protocol/src/session/pase/PaseServer.ts
  packages/types/src/datatype/CommandId.ts
  packages/types/src/schema/PairingCodeSchema.ts
Labels: review - approved

#1763 [NIGHTLY DEV RELEASE] 0.13.0-alpha.0-20250304-d4a7592a4
  version.txt
Labels: automated pr

#1765 exclude some CC teststs for now from nightlies
  .github/workflows/nightly-dev-release.yml
Labels: review - pending

#1766 [NIGHTLY DEV RELEASE] 0.13.0-alpha.0-20250307-ebf84a05a
  version.txt
Labels: automated pr

#1767 Minor spelling fixes and doc update
  docs/MIGRATION_GUIDE_08.md
  packages/examples/README.md
  packages/examples/src/controller/README.md
Labels: review - approved

#1773 Install also libgirepository1.0-dev
  .github/actions/prepare-chip-testing/action.yml
Labels: review - approved

#1774 [NIGHTLY DEV RELEASE] 0.13.0-alpha.0-20250311-3eb0af5f2
  version.txt
Labels: automated pr

#1780 WebSocket Controller testing and Controller Enhancements
  .github/actions/prepare-chip-testing/action.yml
  .github/workflows/chip-matterjs-tests.yml
  .github/workflows/chip-tool-tests.yml
  CHANGELOG.md
  chip-testing/package.json
  chip-testing/src/AllClustersTestApp.ts
  chip-testing/src/AllClustersTestInstance.ts
  chip-testing/src/BridgeTestApp.ts
  chip-testing/src/ChipToolWebSocketHandler.ts
  chip-testing/src/ControllerTestInstance.ts
  chip-testing/src/ControllerWebSocketTestApp.ts
  chip-testing/src/ControllerWebsocketSnifferTestApp.ts
  chip-testing/src/CustomCommissioningFlow.ts
  chip-testing/src/GenericTestApp.ts
  chip-testing/src/NodeTestInstance.ts
  chip-testing/src/TvTestApp.ts
  chip-testing/src/TvTestInstance.ts
  chip-testing/src/handler/CommandHandler.ts
  chip-testing/src/handler/LegacyControllerCommandHandler.ts
  chip-testing/src/storage/StorageBackendAsyncJsonFile.ts
  chip-testing/test/support.ts
  chip/Dockerfile
  package-lock.json
  packages/examples/src/controller/ControllerNode.ts
  packages/general/src/log/Logger.ts
  packages/matter.js/src/CommissioningController.ts
  packages/matter.js/src/MatterController.ts
  packages/matter.js/src/PaseCommissioner.ts
  packages/matter.js/src/device/PairedNode.ts
  packages/nodejs/src/net/NodeJsUdpChannel.ts
  packages/protocol/src/certificate/CertificateAuthority.ts
  packages/protocol/src/cluster/client/ClusterClient.ts
  packages/protocol/src/interaction/AttributeDataDecoder.ts
  packages/protocol/src/interaction/DecodedDataReport.ts
  packages/protocol/src/interaction/EventDataDecoder.ts
  packages/protocol/src/interaction/InteractionClient.ts
  packages/protocol/src/interaction/InteractionMessenger.ts
  packages/protocol/src/interaction/InteractionServer.ts
  packages/protocol/src/peer/ControllerCommissioner.ts
  packages/protocol/src/peer/ControllerCommissioningFlow.ts
  packages/protocol/src/peer/PeerSet.ts
  packages/protocol/src/protocol/ChannelManager.ts
  packages/protocol/test/protocol/interaction/AttributeDataDecoderTest.ts
  packages/types/src/common/StatusCode.ts
  packages/types/src/tlv/TlvObject.ts
Labels: review - approved

#1789 Adjust Logger methods
  CHANGELOG.md
  packages/general/src/log/Logger.ts
Labels: review - approved

#1788 Handle non existing QNames in DNS
  CHANGELOG.md
  packages/general/src/codec/DnsCodec.ts
Labels: review - approved

#1792 Fix update of Fabric label on controller start
  CHANGELOG.md
  packages/nodejs-shell/src/MatterNode.ts
Labels: review - approved

#1790 Improve async storage reliability
  CHANGELOG.md
  packages/nodejs/src/storage/StorageBackendDiskAsync.ts
Labels: review - approved

#1794 Adjust channel destroy logic
  packages/protocol/src/protocol/ChannelManager.ts
  packages/protocol/src/protocol/ExchangeManager.ts
Labels: review - approved

#1795 Forced match for models
  .github/workflows/chip-matterjs-tests.yml
  codegen/src/mom/common/generate-element.ts
  models/src/local/AlarmBaseOverrides.ts
  models/src/local/DoorLockOverrides.ts
  models/src/local/index.ts
  packages/model/src/elements/BaseElement.ts
  packages/model/src/logic/ModelVariantTraversal.ts
  packages/model/src/models/Model.ts
  packages/model/src/standard/elements/AlarmBase.ts
  packages/model/src/standard/elements/DoorLock.ts
  packages/types/src/clusters/alarm-base.ts
  packages/types/src/clusters/dishwasher-alarm.ts
  packages/types/src/clusters/door-lock.ts
  packages/types/src/clusters/refrigerator-alarm.ts
Labels: review - approved

#1800 [OFFICIAL RELEASE] 0.12.6
  CHANGELOG.md
  version.txt
Labels: automated pr

#1787 Support for "Q" quality and improved transitioning
  .gitignore
  CHANGELOG.md
  chip-testing/src/handler/LegacyControllerCommandHandler.ts
  chip-testing/test/app-slow/LVL.test.ts
  codegen/src/clusters/ClusterComponentGenerator.ts
  docs/MIGRATION_GUIDE_08.md
  packages/create/src/build.config.ts
  packages/general/src/time/Time.ts
  packages/general/src/transaction/Participant.ts
  packages/general/src/transaction/Transaction.ts
  packages/general/src/transaction/Tx.ts
  packages/general/src/util/Construction.ts
  packages/general/src/util/DataReadQueue.ts
  packages/general/src/util/Observable.ts
  packages/model/src/aspects/Quality.ts
  packages/model/src/elements/BaseElement.ts
  packages/model/src/elements/ValueElement.ts
  packages/model/src/logic/Scope.ts
  packages/node/src/behavior/Events.ts
  packages/node/src/behavior/Transitions.ts
  packages/node/src/behavior/cluster/ClusterBehavior.ts
  packages/node/src/behavior/cluster/ClusterBehaviorUtil.ts
  packages/node/src/behavior/cluster/ClusterEvents.ts
  packages/node/src/behavior/context/server/OfflineContext.ts
  packages/node/src/behavior/internal/BackingEvents.ts
  packages/node/src/behavior/internal/Reactors.ts
  packages/node/src/behaviors/basic-information/BasicInformationServer.ts
  packages/node/src/behaviors/level-control/LevelControlServer.ts
  packages/node/src/endpoint/Endpoint.ts
  packages/node/src/endpoint/server/BehaviorServer.ts
  packages/node/test/behavior/cluster/ClusterBehaviorTest.ts
  packages/node/test/behavior/cluster/ClusterEventsTest.ts
  packages/node/test/behaviors/level-control/LevelControlServerTest.ts
  packages/node/test/endpoint/server/BehaviorServerTest.ts
  packages/node/test/endpoints/LargeBridgeTest.ts
  packages/node/test/node/mock-exchange.ts
  packages/node/test/node/mock-server-node.ts
  packages/node/test/node/node-helpers.ts
  packages/protocol/src/common/FailsafeContext.ts
  packages/testing/.mocharc.cjs
  packages/testing/src/mocks/time.ts
  packages/testing/src/nodejs-reporter.ts
  packages/testing/src/runner.ts
  packages/tools/src/building/graph.ts
  packages/tools/src/util/package.ts
  packages/tools/src/util/progress.ts
  packages/tools/src/versioning/versioner.ts
Labels: review - approved

#1801 Allow to commission with QR Codes in Shell
  CHANGELOG.md
  packages/nodejs-shell/src/shell/cmd_commission.ts
Labels: review - approved

#1796 Enhance CommissioningFlow config checks
  CHANGELOG.md
  packages/protocol/src/peer/ControllerCommissioningFlow.ts
Labels: review - approved

#1805 Adjust Mergify
  .mergify.yml
Labels: review - approved

#1803 Patch Yamls on releases too
  .github/workflows/nightly-dev-release.yml
  .github/workflows/official-release.yml
Labels: review - approved, automerge

#1806 Enable more Python Cert tests
  .github/workflows/chip-tool-tests.yml
  chip-testing/src/GenericTestApp.ts
  chip-testing/src/storage/StorageBackendAsyncJsonFile.ts
  chip-testing/test/core/OPCREDS.test.ts
  packages/node/src/behaviors/operational-credentials/OperationalCredentialsServer.ts
Labels: review - approved

#1808 [NIGHTLY DEV RELEASE] 0.13.0-alpha.0-20250322-f085fa576
  version.txt
Labels: automated pr

#1809 Codegen fixes
  chip-testing/test/core/DGGEN.test.ts
  chip/Dockerfile
  codegen/bin/generate-chip.js
  codegen/bin/generate-clusters.js
  codegen/bin/generate-endpoints.js
  codegen/bin/generate-forwards.js
  codegen/bin/generate-model.js
  codegen/bin/generate-spec.js
  codegen/bin/generate-vscode.js
  codegen/package.json
  codegen/src/mom/spec/doc-utils.ts
  codegen/src/mom/spec/html-translators.ts
  codegen/src/mom/spec/repairs/default-value-repairs.ts
  codegen/src/util/finalize-model.ts
  eslint.config.mjs
  models/src/v1.4/spec.ts
  packages/model/src/standard/elements/ColorControl.ts
  packages/model/src/standard/elements/CommissionerControl.ts
  packages/model/src/standard/elements/EcosystemInformation.ts
  packages/model/src/standard/elements/LevelControl.ts
  packages/types/src/clusters/commissioner-control.ts
  packages/types/src/clusters/ecosystem-information.ts
Labels: review - approved

#1810 [NIGHTLY DEV RELEASE] 0.13.0-alpha.0-20250323-770919c6a
  version.txt
Labels: automated pr

#1811 Allow Clients to never read remote
  CHANGELOG.md
  packages/protocol/src/cluster/client/AttributeClient.ts
  packages/protocol/src/interaction/InteractionClient.ts
Labels: review - approved

#1817 [NIGHTLY DEV RELEASE] 0.13.0-alpha.0-20250324-d7b7d9731
  version.txt
Labels: automated pr

#1819 Ignore missing IPv4 addresses if enabled
  CHANGELOG.md
  packages/general/src/net/Network.ts
  packages/general/src/net/UdpMulticastServer.ts
  packages/matter.js/src/CommissioningController.ts
  packages/node/src/behavior/system/network/ServerNetworkRuntime.ts
  packages/nodejs/src/net/NodeJsUdpChannel.ts
  packages/react-native/src/net/UdpChannelReactNative.ts
Labels: review - approved, automerge

#1820 [NIGHTLY DEV RELEASE] 0.13.0-alpha.0-20250325-ddb67eace
  version.txt
Labels: automated pr

#1822 Chip apps and fixes
  .vscode/launch.json
  chip-testing/package.json
  chip-testing/test/app-fast/FLABEL.test.ts
  chip/Dockerfile
  chip/README.md
  chip/bin/build
  chip/bin/load
  chip/bin/publish
  chip/bin/pull
  chip/bin/rebuild
  chip/bin/shell
  chip/bin/tool
  chip/support/build-one
  chip/support/generate-test-descriptor
  chip/support/ubuntu-arm64.sources
  codegen/src/generate-vscode.ts
  packages/testing/src/chip/container-command-pipe.ts
  packages/testing/src/chip/state.ts
  packages/testing/src/cli.ts
  packages/testing/src/docker/container.ts
  packages/testing/src/global-declarations.ts
  packages/testing/src/mocha.ts
  packages/testing/src/nodejs.ts
  packages/testing/src/print-report.ts
  packages/testing/src/test-descriptor.ts
  packages/tools/src/util/progress.ts
Labels: review - approved

#1823 [NIGHTLY DEV RELEASE] 0.13.0-alpha.0-20250327-8b06e5a79
  version.txt
Labels: automated pr

#1825 Remove OnOffServer "Lighting " feature enablement
  .github/workflows/chip-tool-tests.yml
  CHANGELOG.md
  packages/examples/src/device-onoff-advanced/DeviceNodeFull.ts
  packages/node/src/behaviors/mode-select/ModeSelectServer.ts
  packages/node/src/behaviors/on-off/OnOffServer.ts
Labels: review - approved

#1826 Rename Base classes for Server implementations
  packages/node/src/behaviors/color-control/ColorControlServer.ts
  packages/node/src/behaviors/electrical-energy-measurement/ElectricalEnergyMeasurementServer.ts
  packages/node/src/behaviors/level-control/LevelControlServer.ts
  packages/node/src/behaviors/mode-select/ModeSelectServer.ts
  packages/node/src/behaviors/on-off/OnOffServer.ts
  packages/node/src/behaviors/power-source/PowerSourceServer.ts
  packages/node/src/behaviors/power-topology/PowerTopologyServer.ts
  packages/node/src/behaviors/switch/SwitchServer.ts
  packages/node/src/behaviors/window-covering/WindowCoveringServer.ts
  packages/node/test/behaviors/level-control/LevelControlServerTest.ts
Labels: review - approved, automerge

#1827 Accept UDP traffic from unknown interfaces
  CHANGELOG.md
  packages/general/src/net/UdpChannel.ts
  packages/general/src/net/UdpMulticastServer.ts
  packages/nodejs/src/net/NodeJsUdpChannel.ts
  packages/react-native/src/net/UdpChannelReactNative.ts
Labels: review - approved

#1828 CHIP testing updates & fixes
  chip-testing/test/core/Discovery.test.ts
  chip/Dockerfile
  chip/bin/build
  chip/bin/load
  chip/bin/publish
  chip/bin/pull
  chip/bin/rebuild
  chip/bin/shell
  chip/bin/tail-mdns
  chip/bin/tool
  chip/support/mdns-clear
  chip/support/mdns-run
  packages/node/src/behaviors/general-diagnostics/GeneralDiagnosticsServer.ts
  packages/node/src/node/NodeLifecycle.ts
  packages/testing/src/chip/chip.ts
  packages/testing/src/chip/state.ts
  packages/testing/src/mocha.ts
Labels: review - approved, automerge

#1829 Chip info
  chip/bin/info
  packages/testing/src/chip/state.ts
  packages/testing/src/docker/container.ts
Labels: review - approved

#1830 [NIGHTLY DEV RELEASE] 0.13.0-alpha.0-20250328-6dde053de
  version.txt
Labels: automated pr

#1831 Test suite fixes
  chip-testing/src/simulators/SwitchSimulator.ts
  packages/testing/src/nodejs.ts
  packages/tools/src/ansi-text/wrapper.ts
  packages/tools/src/util/progress.ts
Labels: review - approved

#1835 [NIGHTLY DEV RELEASE] 0.13.0-alpha.0-20250329-cd36948da
  version.txt
Labels: automated pr

#1838 Fix level control with features disabled
  packages/node/src/behaviors/level-control/LevelControlServer.ts
  packages/node/test/behaviors/level-control/LevelControlServerTest.ts
Labels: review - approved, automerge

#1802 Add Matter.js Dockerized Chiptests in CI
  .github/workflows/chip-tool-tests.yml
  .github/workflows/docker-build.yml
  CHANGELOG.md
  chip-testing/package.json
  chip-testing/test/app-slow/CC.test.ts
  chip-testing/test/core/SC.test.ts
  chip/bin/info
  packages/node/src/behaviors/color-control/ColorControlServer.ts
  packages/testing/src/chip/chip.ts
  packages/testing/src/chip/state.ts
  packages/testing/src/cli.ts
Labels: review - approved, automerge

#1842 [NIGHTLY DEV RELEASE] 0.13.0-alpha.0-20250330-df5a17eba
  version.txt
Labels: automated pr

#1841 Fix bit range parsing
  codegen/src/mom/spec/html-translators.ts
  models/src/v1.4/spec.ts
Labels: review - approved

#1840 Improve version information for CHIP image
  .github/workflows/docker-build.yml
  chip/Dockerfile
  chip/bin/build
  chip/bin/info
  packages/testing/src/chip/state.ts
  packages/testing/src/docker/container.ts
  packages/testing/src/docker/image.ts
Labels: review - approved

#1843 Fix upper bound when parsing bit ranges
  codegen/src/mom/spec/html-translators.ts
  models/src/local/ThermostatOverrides.ts
  models/src/local/WindowCoveringOverrides.ts
  models/src/v1.4/spec.ts
Labels: review - approved, automerge

#1850 [NIGHTLY DEV RELEASE] 0.13.0-alpha.0-20250331-ae2df3e19
  version.txt
Labels: automated pr
