Repository matter-js/matter.js, pull requests merged in 2025-04, with the labels that each got.

#1851 [NIGHTLY DEV RELEASE] 0.13.0-alpha.0-20250401-82b90831a
  version.txt
Labels: automated pr

#1854 Fixes & cosmetics for test reporting
  packages/testing/src/cli.ts
  packages/testing/src/nodejs.ts
  packages/testing/src/print-report.ts
  packages/testing/src/runner.ts
  packages/tools/src/util/progress.ts
Labels: review - approved, automerge

#1855 [NIGHTLY DEV RELEASE] 0.13.0-alpha.0-20250402-672547f02
  version.txt
Labels: automated pr

#1857 Add UDP send guard
  CHANGELOG.md
  packages/nodejs/src/net/NodeJsUdpChannel.ts
Labels: review - approved, automerge

#1859 ColorControl moved to Transitions ... including enhancements
  .github/workflows/chip-tool-tests.yml
  .github/workflows/nightly-dev-release.yml
  CHANGELOG.md
  chip-testing/package.json
  chip-testing/test/app-slow/CC.test.ts
  packages/general/src/util/Number.ts
  packages/node/src/behavior/Transitions.ts
  packages/node/src/behaviors/color-control/ColorControlServer.ts
  packages/node/src/behaviors/level-control/LevelControlServer.ts
  packages/node/test/behaviors/color-control/ColorControlServerTest.ts
  packages/node/test/behaviors/level-control/LevelControlServerTest.ts
Labels: review - approved, automerge

#1861 Fix interface for OnOffBehavior with no features
  packages/node/src/behaviors/on-off/OnOffServer.ts
  packages/node/test/behaviors/fan-control/FanControlTest.ts
  packages/node/test/behaviors/on-off/OnOffServerTest.ts
  packages/types/test/clusters/administrator-commissioningTest.ts
  packages/types/test/clusters/window-coveringTest.ts
Labels: review - approved, automerge

#1863 LevelControl testing tweak and Advertiser shutdown fix
  .github/workflows/chip-tool-tests.yml
  packages/node/test/behaviors/level-control/LevelControlServerTest.ts
  packages/protocol/src/protocol/DeviceAdvertiser.ts
Labels: review - pending

#1866 Updates and fixes
  packages/general/src/util/Mutex.ts
  packages/node/src/behavior/Events.ts
  packages/node/src/endpoint/properties/Behaviors.ts
  packages/protocol/src/interaction/InteractionServer.ts
  packages/protocol/src/protocol/DeviceAdvertiser.ts
  packages/testing/src/cli.ts
  packages/testing/src/failure-reporter.ts
  packages/testing/src/nodejs-reporter.ts
  packages/tools/src/ansi-text/wrapper.ts
Labels: review - approved

#1870 Handle conformance groups with an "optional if"
  packages/model/src/logic/cluster-variance/IllegalFeatureCombinations.ts
  packages/types/src/clusters/door-lock.ts
  packages/types/src/clusters/switch.ts
Labels: review - approved, automerge

#1871 Partial arm64 support for CHIP container
  chip/bin/build
  chip/bin/config.sh
  chip/bin/info
  chip/bin/load
  chip/bin/publish
  chip/bin/pull
  chip/bin/rebuild
  chip/bin/shell
  chip/bin/tail-mdns
  chip/bin/tool
  packages/testing/src/chip/config.ts
  packages/testing/src/chip/state.ts
Labels: review - approved, automerge

#1873 [NIGHTLY DEV RELEASE] 0.13.0-alpha.0-20250405-5f5f0caa
  version.txt
Labels: automated pr

#1872 Matter 1.4 Cluster and Doscs finalization
  .github/workflows/chip-tool-tests.yml
  CHANGELOG.md
  chip-testing/src/AllClustersTestInstance.ts
  chip-testing/src/NamedPipeCommandHandler.ts
  chip-testing/src/cluster/TestWaterTankLevelMonitoringServer.ts
  chip-testing/src/simulators/SwitchSimulator.ts
  chip-testing/test/app-fast/FLABEL.test.ts
  chip-testing/test/app-fast/SWTCH.test.ts
  chip-testing/test/app-fast/ULABEL.test.ts
  docs/CLUSTER_DEFAULT_IMPLEMENTATIONS.md
  docs/MATTER_COMPATIBILITY.md
  packages/node/src/behaviors/occupancy-sensing/OccupancySensingServer.ts
  packages/node/src/behaviors/switch/SwitchServer.ts
  packages/node/test/behaviors/switch/SwitchServerTest.ts
Labels: review - approved, automerge

#1874 [NIGHTLY DEV RELEASE] 0.13.0-alpha.0-20250405-7fc7db48
  version.txt
Labels: automated pr

#1876 Fix typo for running multidevice example
  package.json
Labels: review - approved, automerge

#1877 [rebuild-docker] Patch Docker PICS for removed LVL attributes
  chip-testing/src/AllClustersTestInstance.ts
  packages/testing/src/chip/matter-js-pics.properties
Labels: review - approved

#1884 [NIGHTLY DEV RELEASE] 0.13.0-alpha.0-20250408-c916c7e8
  version.txt
Labels: automated pr

#1885 Fix for command handling in derived clusters
  .vscode/launch.json
  codegen/src/clusters/generate-cluster.ts
  codegen/src/endpoints/InterfaceFile.ts
  codegen/src/generate-vscode.ts
  codegen/src/util/finalize-model.ts
  packages/model/src/models/ClusterModel.ts
  packages/model/src/models/CommandModel.ts
  packages/node/src/behaviors/device-energy-management-mode/DeviceEnergyManagementModeInterface.ts
  packages/node/src/behaviors/dishwasher-alarm/DishwasherAlarmInterface.ts
  packages/node/src/behaviors/dishwasher-mode/DishwasherModeInterface.ts
  packages/node/src/behaviors/energy-evse-mode/EnergyEvseModeInterface.ts
  packages/node/src/behaviors/laundry-washer-mode/LaundryWasherModeInterface.ts
  packages/node/src/behaviors/oven-cavity-operational-state/OvenCavityOperationalStateInterface.ts
  packages/node/src/behaviors/oven-mode/OvenModeInterface.ts
  packages/node/src/behaviors/refrigerator-and-temperature-controlled-cabinet-mode/RefrigeratorAndTemperatureControlledCabinetModeInterface.ts
  packages/node/src/behaviors/rvc-clean-mode/RvcCleanModeInterface.ts
  packages/node/src/behaviors/rvc-operational-state/RvcOperationalStateInterface.ts
  packages/node/src/behaviors/rvc-run-mode/RvcRunModeInterface.ts
  packages/node/src/behaviors/water-heater-mode/WaterHeaterModeInterface.ts
  packages/node/test/behaviors/energy-evse-mode/EnergyEvsModeServerTest.ts
  packages/node/test/behaviors/rvc-operational-state/RvcOperationalStateServerTest.ts
  packages/types/src/clusters/oven-cavity-operational-state.ts
  packages/types/src/clusters/rvc-operational-state.ts
Labels: review - approved

#1886 Fix behaviors with only inherit commands
  codegen/src/endpoints/BehaviorFile.ts
  packages/node/src/behaviors/device-energy-management-mode/DeviceEnergyManagementModeBehavior.ts
  packages/node/src/behaviors/dishwasher-alarm/DishwasherAlarmBehavior.ts
  packages/node/src/behaviors/dishwasher-mode/DishwasherModeBehavior.ts
  packages/node/src/behaviors/energy-evse-mode/EnergyEvseModeBehavior.ts
  packages/node/src/behaviors/laundry-washer-mode/LaundryWasherModeBehavior.ts
  packages/node/src/behaviors/oven-mode/OvenModeBehavior.ts
  packages/node/src/behaviors/refrigerator-and-temperature-controlled-cabinet-mode/RefrigeratorAndTemperatureControlledCabinetModeBehavior.ts
  packages/node/src/behaviors/rvc-clean-mode/RvcCleanModeBehavior.ts
  packages/node/src/behaviors/rvc-run-mode/RvcRunModeBehavior.ts
  packages/node/src/behaviors/water-heater-mode/WaterHeaterModeBehavior.ts
  packages/node/test/behaviors/energy-evse-mode/EnergyEvsModeServerTest.ts
Labels: review - approved, automerge

#1887 Fix responses for commands with overrides
  codegen/src/clusters/ClusterComponentGenerator.ts
  codegen/src/clusters/generate-cluster.ts
  packages/model/src/logic/ModelTraversal.ts
  packages/model/src/models/CommandModel.ts
  packages/node/src/behaviors/oven-cavity-operational-state/OvenCavityOperationalStateInterface.ts
  packages/node/src/behaviors/rvc-operational-state/RvcOperationalStateInterface.ts
  packages/node/test/behaviors/rvc-operational-state/RvcOperationalStateServerTest.ts
  packages/types/src/clusters/oven-cavity-operational-state.ts
  packages/types/src/clusters/rvc-operational-state.ts
Labels: review - approved, automerge

#1888 [NIGHTLY DEV RELEASE] 0.13.0-alpha.0-20250411-da7e9c43c
  version.txt
Labels: automated pr

#1891 Conformance fixes
  packages/model/src/aspects/Conformance.ts
  packages/model/src/logic/Scope.ts
  packages/node/src/behavior/cluster/ClusterBehavior.ts
  packages/node/src/behavior/cluster/ClusterBehaviorUtil.ts
  packages/node/src/behavior/state/validation/conformance-compiler.ts
  packages/node/src/behavior/state/validation/conformance-util.ts
  packages/node/test/behavior/cluster/ClusterBehaviorTest.ts
  packages/node/test/behavior/cluster/ClusterEventsTest.ts
  packages/node/test/behavior/cluster/cluster-behavior-test-util.ts
Labels: review - approved, automerge

#1893 [NIGHTLY DEV RELEASE] 0.13.0-alpha.0-20250412-5fad64e7b
  version.txt
Labels: automated pr

#1895 Always close PASE server when ending commissioning
  packages/protocol/src/protocol/DeviceCommissioner.ts
  packages/protocol/src/session/pase/PaseServer.ts
Labels: review - approved

#1897 Inform Device when controller cancels pairing
  CHANGELOG.md
  packages/protocol/src/session/pase/PaseClient.ts
Labels: review - approved

#1899 [NIGHTLY DEV RELEASE] 0.13.0-alpha.0-20250413-d5a27700d
  version.txt
Labels: automated pr

#1912 [NIGHTLY DEV RELEASE] 0.13.0-alpha.0-20250415-475996bb5
  version.txt
Labels: automated pr

#1913 Add another DNS decoding test
  packages/general/test/codec/DnsCodecTest.ts
Labels: review - approved

#1914 patch BINFO test case because of SDK 1.5 preps
  README.md
  chip-testing/PATCHED_TESTS_INFO.md
  chip-testing/patched-test-files/certification/Test_TC_BINFO_2_1.yaml
  chip-testing/test/core/BINFO.test.ts
Labels: review - pending

#1907 Make link in quasi-deprecated package
  .github/dependabot.yml
  packages/matter.js/README.md
Labels: review - approved, automerge

#1915 Remove Sync Storage and other dependency cleanups
  .mergify.yml
  CHANGELOG.md
  package-lock.json
  packages/examples/package.json
  packages/main/package.json
  packages/matter.js/package.json
  packages/model/package.json
  packages/node/package.json
  packages/nodejs-shell/src/MatterNode.ts
  packages/nodejs/package.json
  packages/nodejs/src/environment/NodeJsEnvironment.ts
  packages/nodejs/src/storage/StorageBackendDisk.ts
  packages/nodejs/src/storage/StorageBackendDiskAsync.ts
  packages/nodejs/src/storage/index.ts
  packages/nodejs/test/storage/StorageBackendDiskAsyncTest.ts
  packages/nodejs/test/storage/StorageBackendDiskTest.ts
  packages/protocol/package.json
  packages/types/package.json
Labels: review - approved, automerge

#1908 Sync shell help order with positional order
  packages/nodejs-shell/src/shell/cmd_cluster-attributes.ts
  packages/nodejs-shell/src/shell/cmd_cluster-commands.ts
  packages/nodejs-shell/src/shell/cmd_cluster-events.ts
Labels: review - approved, automerge

#1909 change controller example pin->passcode
  packages/examples/src/controller/ControllerNode.ts
  packages/examples/src/controller/README.md
Labels: review - approved, automerge

#1911 Add SmokeCO-Alarm & Air Quality examples
  packages/examples/package.json
  packages/examples/src/device-air-quality-sensor/AirQualitySensorDeviceNode.ts
  packages/examples/src/device-air-quality-sensor/README.md
  packages/examples/src/device-onoff-advanced/DeviceNodeFull.ts
  packages/examples/src/device-smoke-co-alarm/README.md
  packages/examples/src/device-smoke-co-alarm/SmokeCOAlarmDeviceNode.ts
  packages/node/src/behaviors/smoke-co-alarm/SmokeCoAlarmServer.ts
Labels: review - approved, automerge

#1927 Optimize BLE
  packages/examples/src/controller/ControllerNode.ts
  packages/examples/src/device-onoff-advanced/DeviceNodeFull.ts
  packages/nodejs-ble/src/BlenoBleServer.ts
  packages/nodejs-ble/src/NobleBleClient.ts
  packages/nodejs-ble/src/NodeJsBle.ts
  packages/nodejs-shell/src/app.ts
  packages/protocol/src/protocol/ChannelManager.ts
  packages/protocol/src/protocol/ExchangeManager.ts
  packages/protocol/src/session/SecureSession.ts
Labels: review - approved, automerge

#1928 increase some deps ourself
  package-lock.json
  package.json
  packages/examples/src/tsconfig.json
  packages/matter.js/tsconfig.json
Labels: review - approved, automerge

#1929 Update Bleno
  package-lock.json
  packages/nodejs-ble/package.json
  packages/nodejs-ble/src/BlenoBleServer.ts
Labels: review - approved, automerge

#1931 Patch/Exclude some ACL tests
  .github/workflows/chip-tool-tests.yml
  CHANGELOG.md
  chip-testing/PATCHED_TESTS_INFO.md
  chip-testing/patched-test-files/certification/Test_TC_ACL_2_3.yaml
  chip-testing/patched-test-files/certification/Test_TC_ACL_2_4.yaml
  chip-testing/patched-test-files/certification/Test_TC_ACL_2_5.yaml
  chip-testing/patched-test-files/certification/Test_TC_ACL_2_6.yaml
  chip-testing/patched-test-files/certification/Test_TC_ACL_2_8.yaml
  chip-testing/src/RvcTestInstance.ts
  chip-testing/test/core/ACE.test.ts
  chip-testing/test/core/ACL.test.ts
  chip-testing/test/core/IDM.test.ts
Labels: review - approved, automerge

#1932 [NIGHTLY DEV RELEASE] 0.13.0-alpha.0-20250418-8cfc0b832
  version.txt
Labels: automated pr

#1933 Clear out convenient entries from log
  packages/protocol/src/endpoint/EndpointStructureLogger.ts
Labels: review - approved

#1935 Upgrade Noble
  package-lock.json
  packages/nodejs-ble/package.json
  packages/nodejs-ble/src/BleScanner.ts
  packages/nodejs-ble/src/NobleBleChannel.ts
  packages/nodejs-ble/src/NobleBleClient.ts
Labels: review - approved, automerge

#1934 Exclude ACL test too for releases till we fixed it
  .github/workflows/nightly-dev-release.yml
  .github/workflows/official-release.yml
Labels: review - approved, automerge

#1936 Controller enhancements
  CHANGELOG.md
  packages/matter.js/API.md
  packages/matter.js/src/CommissioningController.ts
  packages/matter.js/src/device/DeviceInformation.ts
  packages/matter.js/src/device/PairedNode.ts
  packages/protocol/src/cluster/client/ClusterClient.ts
  packages/protocol/src/cluster/client/ClusterClientTypes.ts
Labels: review - approved, automerge

#1937 [NIGHTLY DEV RELEASE] 0.13.0-alpha.0-20250420-9f45e4f77
  version.txt
Labels: automated pr

#1942 Allow to override createTransitions method in LVL/CC
  packages/node/src/behaviors/color-control/ColorControlServer.ts
  packages/node/src/behaviors/level-control/LevelControlServer.ts
  packages/node/src/behaviors/window-covering/WindowCoveringServer.ts
Labels: review - approved

#1943 [NIGHTLY DEV RELEASE] 0.13.0-alpha.0-20250422-0d27f26be
  version.txt
Labels: automated pr

#1944 [NIGHTLY DEV RELEASE] 0.13.0-alpha.0-20250423-8917d1d1d
  version.txt
Labels: automated pr

#1945 Fix Wifi naming in Thread configuration output
  packages/nodejs-shell/src/shell/cmd_config.ts
Labels: review - approved, automerge

#1946 [NIGHTLY DEV RELEASE] 0.13.0-alpha.0-20250424-4760af1f3
  version.txt
Labels: automated pr

#1948 BLE Upgrades, Optimizations and fixes
  package-lock.json
  packages/nodejs-ble/package.json
  packages/nodejs-ble/src/BleBroadcaster.ts
  packages/nodejs-ble/src/BleScanner.ts
  packages/nodejs-ble/src/BlenoBleServer.ts
  packages/nodejs-ble/src/NobleBleChannel.ts
  packages/nodejs-ble/src/NobleBleClient.ts
  packages/nodejs-shell/src/MatterNode.ts
  packages/nodejs-shell/src/app.ts
Labels: review - approved, automerge

#1949 Ensure unique NodeIds on commissioning
  packages/matter.js/src/MatterController.ts
  packages/protocol/src/peer/ControllerCommissioner.ts
Labels: review - approved, automerge

#1950 Patch tests back to Matter 1.4
  chip-testing/PATCHED_TESTS_INFO.md
  chip-testing/patched-test-files/TestOperationalCredentialsCluster.yaml
Labels: review - pending, automerge

#1951 Finalize Changelog for 0.13 release
  CHANGELOG.md
Labels: review - pending, automerge

#1952 [NIGHTLY DEV RELEASE] 0.13.0-alpha.0-20250425-94b33ff98
  version.txt
Labels: automated pr

#1954 Address some Prototype-polluting assignment issues
  packages/general/src/environment/VariableService.ts
Labels: review - approved, automerge

#1955 Adjust strange chip parsing case
  codegen/src/mom/chip/translate-chip.ts
Labels: review - approved, automerge

#1956 Exposing the current Subscription Interval on PairedNode
  CHANGELOG.md
  packages/matter.js/src/device/PairedNode.ts
  packages/protocol/src/interaction/InteractionClient.ts
Labels: review - approved, automerge

#1957 Remove commissionedNode on recommissions in controller tests
  chip-testing/src/handler/LegacyControllerCommandHandler.ts
Labels: review - approved, automerge

#1958 [NIGHTLY DEV RELEASE] 0.13.0-alpha.0-20250427-e7df8aa45
  version.txt
Labels: automated pr

#1959 Expose subscription alive info on PairedNode
  CHANGELOG.md
  packages/matter.js/src/device/PairedNode.ts
  packages/protocol/src/interaction/InteractionClient.ts
Labels: review - approved

#1960 [NIGHTLY DEV RELEASE] 0.13.0-alpha.0-20250427-b7d4121bb
  version.txt
Labels: automated pr

#1961 Fix Subscription Alive wiring in PairedNode
  packages/matter.js/src/device/PairedNode.ts
Labels: review - approved, automerge

#1962 [NIGHTLY DEV RELEASE] 0.13.0-alpha.0-20250427-275b73b4f
  version.txt
Labels: automated pr

#1966 [OFFICIAL RELEASE] 0.13.0
  CHANGELOG.md
  version.txt
Labels: automated pr

#1968 [NIGHTLY DEV RELEASE] 0.13.1-alpha.0-20250429-fd3557399
  version.txt
Labels: automated pr

#1969 Validate Message encryption as expected by protocol
  CHANGELOG.md
  packages/protocol/src/interaction/InteractionServer.ts
  packages/protocol/src/interaction/SubscriptionClient.ts
  packages/protocol/src/protocol/ExchangeManager.ts
  packages/protocol/src/protocol/ProtocolHandler.ts
  packages/protocol/src/securechannel/SecureChannelProtocol.ts
  packages/protocol/src/session/case/CaseServer.ts
  packages/protocol/src/session/pase/PaseServer.ts
Labels: review - approved, automerge

#1970 First Refactor-Step: Interactionserver merge and read wire-in
  CHANGELOG.md
  packages/model/src/common/DataModelPath.ts
  packages/node/src/behavior/context/server/OnlineContext.ts
  packages/node/src/behavior/system/controller/ControllerBehavior.ts
  packages/node/src/behavior/system/network/ServerNetworkRuntime.ts
  packages/node/src/behavior/system/subscription/SubscriptionBehavior.ts
  packages/node/src/node/server/InteractionServer.ts
  packages/node/src/node/server/ProtocolService.ts
  packages/node/src/node/server/TransactionalInteractionServer.ts
  packages/node/src/node/server/index.ts
  packages/node/test/endpoint/server/BehaviorServerTest.ts
  packages/node/test/endpoint/server/InteractionProtocolTest.ts
  packages/node/test/endpoint/server/InteractionTestUtils.ts
  packages/node/test/node/AttributeResponseTest.ts
  packages/node/test/node/mock-server-node.ts
  packages/node/test/node/node-helpers.ts
  packages/protocol/src/action/response/ReadResult.ts
  packages/protocol/src/action/server/AttributeResponse.ts
  packages/protocol/src/interaction/AttributeDataEncoder.ts
  packages/protocol/src/interaction/InteractionEndpointStructure.ts
  packages/protocol/src/interaction/InteractionMessenger.ts
  packages/protocol/src/interaction/ServerSubscription.ts
  packages/protocol/src/interaction/index.ts
Labels: review - approved
