Repository matter-js/matter.js, pull requests merged in 2025-08, with the labels that each got.

#2306 Controller fixes
  CHANGELOG.md
  packages/matter.js/src/device/CachedClientNodeStore.ts
  packages/matter.js/src/device/PairedNode.ts
  packages/protocol/src/interaction/InteractionClient.ts
Labels: automerge

#2307 Dep update
  package-lock.json
  package.json
Labels: automerge

#2279 Remove SyncStorage and add Blob Storage support
  .github/workflows/build-test.js.yml
  .github/workflows/release-npm.yml
  CHANGELOG.md
  README.md
  package-lock.json
  packages/create/package.json
  packages/examples/package.json
  packages/general/src/storage/Storage.ts
  packages/general/src/storage/StorageBackendMemory.ts
  packages/general/src/storage/StorageContext.ts
  packages/general/src/storage/StorageManager.ts
  packages/general/test/storage/StorageBackendMemoryTest.ts
  packages/general/test/storage/StorageContextTest.ts
  packages/main/README.md
  packages/matter.js/src/CommissioningController.ts
  packages/matter.js/src/cluster/server/ClusterServerTypes.ts
  packages/matter.js/src/cluster/server/EventServer.ts
  packages/matter.js/src/device/CachedClientNodeStore.ts
  packages/node/src/storage/NodeStore.ts
  packages/nodejs-ble/package.json
  packages/nodejs-shell/package.json
  packages/nodejs/package.json
  packages/nodejs/src/net/NodeJsNetwork.ts
  packages/nodejs/src/storage/StorageBackendDisk.ts
  packages/nodejs/test/storage/StorageBackendDiskTest.ts
  packages/nodejs/test/storage/StorageBackendJsonFileTest.ts
  packages/react-native/src/storage/StorageBackendAsyncStorage.ts
  packages/tools/README.md
  support/chip-testing/src/storage/StorageBackendAsyncJsonFile.ts
  support/codegen/package.json
Labels: review - approved

#2309 [NIGHTLY DEV RELEASE] 0.16.0-alpha.0-20250802-1af103e3d
  version.txt
Labels: automated-npm-release

#2324 Add Buffer dep for react-native
  package-lock.json
  packages/react-native/package.json
Labels: automerge

#2330 Make ProtocolStatus extensible
  packages/protocol/src/protocol/ProtocolHandler.ts
  packages/protocol/src/protocol/ProtocolStatusMessage.ts
  packages/protocol/src/securechannel/SecureChannelMessenger.ts
  packages/protocol/src/securechannel/SecureChannelProtocol.ts
  packages/protocol/src/securechannel/SecureChannelStatusMessageSchema.ts
  packages/protocol/test/protocol/ProtocolStatusCodeTest.ts
  packages/types/src/protocol/definitions/bdx.ts
  packages/types/src/protocol/definitions/index.ts
Labels: automerge

#2332 Tweak StandardCrypto initialization
  packages/general/src/crypto/StandardCrypto.ts
  packages/general/src/crypto/WebCrypto.ts
  packages/general/src/crypto/index.ts
  packages/react-native/src/crypto/ReactNativeCrypto.ts
Labels: automerge

#2334 [NIGHTLY DEV RELEASE] 0.16.0-alpha.0-20250812-285b75d83
  version.txt
Labels: automated-npm-release

#2333 Add devcontainer configuration
  .devcontainer/devcontainer.json
  CHANGELOG.md
Labels: automerge

#2339 [NIGHTLY DEV RELEASE] 0.16.0-alpha.0-20250815-ac9fd6eb0
  version.txt
Labels: automated-npm-release

#2342 Seems quick crypto does support importKey
  packages/react-native/src/crypto/ReactNativeCrypto.ts
Labels: automerge

#2343 [NIGHTLY DEV RELEASE] 0.16.0-alpha.0-20250816-d22ad240d
  version.txt
Labels: automated-npm-release

#2359 [NIGHTLY DEV RELEASE] 0.16.0-alpha.0-20250819-0a388db8b
  version.txt
Labels: automated-npm-release

#2358 ClientNode networking updates (take 2)
  CHANGELOG.md
  packages/node/src/behavior/system/commissioning/CommissioningClient.ts
  packages/node/src/behavior/system/network/ClientNetworkRuntime.ts
  packages/node/src/behavior/system/network/NetworkBehavior.ts
  packages/node/src/behavior/system/network/NetworkClient.ts
  packages/node/src/behavior/system/network/NetworkRuntime.ts
  packages/node/src/behavior/system/network/ServerNetworkRuntime.ts
  packages/node/src/node/ClientNode.ts
  packages/node/src/node/Node.ts
  packages/node/test/node/ClientNodeTest.ts
  packages/node/test/node/mock-site.ts
  packages/protocol/src/peer/PeerAddress.ts
  packages/protocol/src/securechannel/SecureChannelMessenger.ts
  packages/protocol/src/session/NodeSession.ts
  packages/protocol/src/session/case/CaseClient.ts
  packages/protocol/src/session/case/CaseServer.ts
  packages/protocol/src/session/pase/PaseClient.ts
  packages/protocol/src/session/pase/PaseServer.ts
Labels: automerge

#2362 [NIGHTLY DEV RELEASE] 0.16.0-alpha.0-20250820-24939dd26
  version.txt
Labels: automated-npm-release

#2365 [NIGHTLY DEV RELEASE] 0.16.0-alpha.0-20250821-dd03e1003
  version.txt
Labels: automated-npm-release

#2366 CHIP testing fixes pass n of ∞
  support/chip-testing/test/core/ACL.test.ts
  support/chip/sha.txt
  support/chip/support/generate-test-descriptor
Labels: automerge

#2367 [CHIP BUILD] a2a07d48317b5b59192e5cc751f9f06c660f9ff4
  support/chip/sha.txt
Labels: automated-docker-release

#2372 [NIGHTLY DEV RELEASE] 0.16.0-alpha.0-20250822-523588650
  version.txt
Labels: automated-npm-release

#2371 [CHIP BUILD] ad7752d087b356cb8329f6502a8bd66bf57667a8
  support/chip/sha.txt
Labels: automated-docker-release

#2374 [CHIP BUILD] 71aed779041a42accb4b449a43dd6db38b073e21
  support/chip/sha.txt
Labels: automated-docker-release

#2389 [NIGHTLY DEV RELEASE] 0.16.0-alpha.0-20250826-531401faa
  version.txt
Labels: automated-npm-release
